### ISSUE TITLE
Implement instructions needed for storing small ints in the tagged pointer

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#100]
This is a follow-on from #90 and a prerequisite for #99. Only instruction needed is:

- [ ] sext: needed to sign extend from small ints to 64-bit ints

**Comment by heshanpadmasiri** [comment]
@jclark for this I am thinking of adding new function `public function sext(Value val, IntType destTy, string? name=()) returns Value` (similar to [`LLVMBuildSExt`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga1c17766d2faab1903b336c306ab3ce9f)) to `Builder`

**Comment by jclark** [comment]
Should be `sExt`. Note that I did `zExt` already.
