### ISSUE TITLE
`is-expr` must accept any expression not just `shift-expr`

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1000]
Our definition of `is-expr` : https://github.com/ballerina-platform/nballerina/blob/e41b7cbcbd8725fb32761044a3567bd89d9380f1/docs/subset14.md?plain=1#L278
Spec definition : https://ballerina.io/spec/lang/2022R1/#is-expr
lhs of the expression can be any expression according to spec

**Comment by jclark** [comment]
It's defined this way because the grammar in the subset is making precedence explicit, whereas the grammar in the spec isn't. Please create an issue saying with an example that you think nballerina is handling wrong.
