### ISSUE TITLE
Error when creating `anydata|anydata[]` type variables

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1001]
Fallowing code should not cause an error:
```
public function main() {
    anydata|anydata[] a5 = [1, 2, 3];   
}
```
But gives error message:
```
ambiguous inherent type for list constructor
```

**Comment by jclark** [comment]
Please check the spec https://ballerina.io/spec/lang/2022R1/#section_6.7.1 and make sure that this a bug.

**Comment by heshanpadmasiri** [comment]
This is not a bug (This leads to 2 type descriptors as the inherent type)
