### ISSUE TITLE
Implement type system in DWARF

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1006]
﻿Fallowing #935 in order for us to properly view variables in a debugger we need to
1. Port our type system to DWARF
        DWARF has its own type system described under section 5 [here](https://dwarfstd.org/doc/DWARF4.pdf). We have the necessary functions to build those types using the DIBuilder ([ref](https://llvm.org/doxygen/group__LLVMCCoreDebugInfo.html))
2. (most probably) Add a pretty printer to show values nicely
        We will need something similar to rust-gdb / rust-lldb (relevant part of the code lives [here](https://github.com/rust-lang/rust/tree/master/src/etc ) and is shipped with the rust compiler) so our values are easier to read. Found an easier to follow guide on how to make a simple pretty priter [here](https://undo.io/resources/gdb-watchpoint/here-quick-way-pretty-print-structures-gdb/ ).
3. Integrate VS code 
        We can directly plug GDB/LLDB to the VS code debugger using the launcher.json similar to the following. After that as long as break points and values properly work in the gdb side they should work in VS code side as well. (Confirmed to work with base types)
```
{
        // Use IntelliSense to learn about possible attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        // ref: https://code.visualstudio.com/docs/cpp/launch-json-reference
        "version": "0.2.0",
        "configurations": [
            {
                "name": "GDB test",
                "type": "cppdbg", // GDB
                "request": "launch",
                "program": "${workspaceFolder}/1-v.exe", // exe name here
                "cwd": "${workspaceFolder}",
                "stopAtEntry": false,
                "linux": {
                    "MIMode": "gdb",
                    "miDebuggerPath": "/usr/bin/gdb"
                }
            }
        ]
}
```

**Comment by heshanpadmasiri** [comment]
When it comes to implementing our type system in DWARF it can be broken down to two main groups
1. Untagged values (WIP)
        These can be represented using `Base Type Entries` (section 5.1 in the [spec](https://dwarfstd.org/doc/DWARF4.pdf)). For integer type this is all we need. For others (boolean, null) we will need the help of a pretty printer to properly show the “value” (ex: true instead of 1)
2. Tagged values (TBD)
Attempts at directly porting the c definition of tagged ptr as
```
#define GC /* as nothing */
#define NODEREF __attribute__((noderef))


typedef GC char NODEREF *TaggedPtr;
```
Leads to following debug info
```
!26 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !27, size: 64)
!27 = !DIDerivedType(tag: DW_TAG_typedef, name: "TaggedPtr", file: !6, line: 5, baseType: !28)
!28 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !29, size: 64)
!29 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
```

However using this directly so far we couldn’t get dwarf to read any thing from the tagged ptr. Instead of this we may need a more complicated typing system that has different type definitions for each type (example one for tagged int another for tagged float)


Special case will be narrowed variables whose type changes at each narrowing. This is expected to be dealt with a strategy similar to how shadowing is implemented in rust (so far confirmed to work with base types)

**Comment by heshanpadmasiri** [comment]
Regarding VS code debug architecture, VS code can be extended using Debug Adapters.

![debug-arch](https://user-images.githubusercontent.com/17991461/166436951-a18d56a7-58f9-4495-9325-656156387272.png) [source](https://vscode-docs.readthedocs.io/en/stable/extensions/example-debuggers)

 These are stand alone executable that talks to the real debugger (how is left to the debug adapter). Every debug adapter defines a debug `type` which is referenced from the launch configuration. (In the configuration provided above it is `cppdbg` which is the debugger adapter define in [cpptools](https://github.com/microsoft/vscode-cpptools)). VS code communicates with these adapters using the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol). The particular debug adapter we have selected uses the [MIEngine](https://github.com/Microsoft/MIEngine) to communicate with gdb (or lldb). MIEngine uses the [MI interface](https://developer.apple.com/library/archive/documentation/DeveloperTools/gdb/gdb/gdb_25.html#SEC236) to communicate with GDB.
![breakpoint](https://user-images.githubusercontent.com/17991461/166437213-65a66564-2990-46e8-a786-f81ec06b32f0.png) [source](https://code.visualstudio.com/blogs/2018/08/07/debug-adapter-protocol-website/)

**Comment by heshanpadmasiri** [comment]
Therefore regarding formatting values (point 2 [above](https://github.com/ballerina-platform/nballerina/issues/1006#issue-1223675821)) we actually have 2 options 

1. We can have our own debug adapter that will communicate directly with GDB and return the expected output.
2. We can have a gdb pretty printer for ballerina similar to rust-gdb and reuse an existing debug adapter. To integrate this with VS code we need two things
    1. Enable pretty printing in the debug adapter (for `cppdbg` this is done by adding the setup command `-enable-pretty-printing` to `lauch.json`)
    2. Register our pretty printer with GDB. This is done by adding line 
    ```
    source path_to_pretty_printer.py
    ```
    to the ~/.gdbinit file (each project directory can have it's own gdbinit file as well but needs special permission). (In the future when we have a installer we could automate this step with something like rust does for [gdb](https://github.com/rust-lang/rust/blob/master/src/etc/rust-gdb) and [lldb](https://github.com/rust-lang/rust/blob/master/src/etc/rust-lldb))

**Comment by jclark** [comment]
My understanding is that what we need to represent in DWARF is not our type system, but the different kinds of value representation that the LLVM backend uses.

**Comment by heshanpadmasiri** [comment]
> My understanding is that what we need to represent in DWARF is not our type system, but the different kinds of value representation that the LLVM backend uses.

Yes in the sense of "nature" of the type (number of bits, is it a pointer etc.) but should use the ballerina name.
