### ISSUE TITLE
Implement logical expressions `&&` and `||` in the front-end

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#101]
Specified in

https://ballerina.io/spec/lang/2021R1/#section_6.31

I don't think they need anything from the backend.

**Comment by jclark** [comment]
Better to do #129 first.

**Comment by jclark** [comment]
This will need doc added to subset13.

**Comment by manuranga** [comment]
@jclark Should following code compile ?
```ballerina
function f(int|string x) {
    if false || x is string {
        string _ = x;
        return;
    }
    int _ = x;
}
```

** Edit: There was a mistake in the sample, changed `true` to `false`

**Comment by jclark** [comment]
Please explain the issue.

**Comment by manuranga** [comment]
Following shouldn't compile, but I think the above should. Since spec doesn't explicitly mention constants, can I still infer above should compile, or do I need to create a spec issue.

```ballerina
function f(boolean b, int|string x) {
    if b || x is string {
        string _ = x; // @error
        return;
    }
    int _ = x;
}
```

**Comment by jclark** [comment]
By explain the issue, I mean explain why you think it should or should not compile.

Expression typing is based on singleton types not constants.

**Comment by manuranga** [comment]
Created [ballerina-spec#1029](https://github.com/ballerina-platform/ballerina-spec/issues/1029)  to track above.

**Comment by manuranga** [comment]
I need to move `env` back out of the the `ExprContext` into a parameter.
Consider `x is string && isEmptyString(x)`, env created by `x is string` needs to pass to `isEmptyString(x)`. Another option is to update (push/pop) in the `ExprContext`, but extra state is undesirable.
I'll send this as a separate pr.

**Comment by jclark** [comment]
You don't need to do that: just create a new ExprContext with different env.
