### ISSUE TITLE
Rename `args` field in  CallInsn to `operands`

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/nballerina#1021]
**Description:**
The field `args` in CallInsn in `bir.bal` should be changed to `operands` for consistency with other instructions.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by heshanpadmasiri** [comment]
Fixed with #1213
