### ISSUE TITLE
Construct decimal constants at compile-time

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1025]
Currently we are using `decQuadFromString` at runtime in places such as [creating decimal constants](https://github.com/ballerina-platform/nballerina/blob/fe0ed4185c12e259c27e2841a3fae959772706e9/runtime/decimal.c#L255) in order to create the runtime representation of decimal constants. It would be better to construct the native decQuad representation  (which is a 16-byte Densely Packed Decimal format) at compile time.

**Comment by jclark** [comment]
We don't want to have to call any function at runtime.

**Comment by jclark** [comment]
Look at 

http://speleotrove.com/decimal/DPDecimal.html
