### ISSUE TITLE
Check and align mapping `isEmpty` function with the solution for exercise 10 in Cov-Contra paper (10/Apr/22)

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/nballerina#1027]
**Description:**
[Cov-Contra paper](https://www.irif.fr/~gc/papers/covcon-again.pdf)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by heshanpadmasiri** [comment]
I think there is an edge case where our current algorithm is not behaving as intended. I believe we should pass the following test (but we don't)
```
// @type pos < neg
type pos record {
    0|1|2 a;
    float b;
};

type R_1 record {
    2 a;
    float b;
};

type R_2 record {
    0|1 a;
    string b;
};

type neg R_1|R_2;
```
I believe the reason for this is, in our algorithm following line
https://github.com/ballerina-platform/nballerina/blob/4ea04d25b468f5553577f597daae4b9122973435/compiler/modules/types/mapping.bal#L236
is not doing the same thing as the highlighted section of the algorithm
![image](https://user-images.githubusercontent.com/17991461/173226182-2df59120-bd7e-45a6-8692-8e01d609022e.png)
There the next negative atoms are checked against only the "part" of the field that didn't match (i.e remove the other fields from the positive) whereas we leave the other fields intact (and change only the field that didn't match).

**Comment by jclark** [comment]
A value `{ a: 0, b: 1.0 }`  belongs to pos, but not R_1 nor to R_2, so why is `pos` smaller than `neg`?

**Comment by jclark** [comment]
@heshanpadmasiri If you find an example where you think we are doing the wrong thing, check it with CDuce.

**Comment by heshanpadmasiri** [comment]
> A value `{ a: 0, b: 1.0 }` belongs to pos, but not R_1 nor to R_2, so why is `pos` smaller than `neg`?

@jclark I was under the wrong impression that R_1|R_2 is field wise union. But in that case, should we be passing the following test  (we are passing this currently, note R_2 doesn't have a string b)?
```
// @type pos < neg
type pos record {
    0|1|2 a;
    float b;
};

type R_1 record {
    2 a;
    float b;
};

type R_2 record {
    0|1 a;
};

type neg R_1|R_2;
```

**Comment by jclark** [comment]
I suggest you use `{| |}` rather than `{ }` in tests, so the openness is explicit.

**Comment by jclark** [comment]
R2 means `record {| 0|1 a; anydata...; |}`.

`|` always means set union (that is really what semantic subtyping means).

**Comment by heshanpadmasiri** [comment]
Proof that both are the [same](https://docs.google.com/document/d/e/2PACX-1vS6LgPZ6DbyeAw-m6eE50h1r21npTO9-uK1_R3hCfHf2ZBq6NUuQb4cEiUhLNC7E9FpkWREIm-CxzH7/pub)
[prove_isEmpty.pdf](https://github.com/ballerina-platform/nballerina/files/8937481/prove_isEmpty.pdf)
