### ISSUE TITLE
Bug in subtype relation between `map` and `record`

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1049]
**Description:**
Fallowing type relation should be correct
```
// @type Cood < IntMap
type Cood record {| int x; int...; |};
type IntMap map<int>;
```
But currently it think `Cood = IntMap`

**Comment by heshanpadmasiri** [comment]
This problem seems to be caused by a subtle difference in how `MappingPairing` deal with the default value of the records. In the paper, the default value is ANY|⊥ for open records as shown below.
![image](https://user-images.githubusercontent.com/17991461/180740020-689a9e39-4a4b-456f-ab0d-6f99b0534a0c.png)

In our context (allowing for openness to be controlled) I believe this should be rest|NEVER (given that NEVER corresponds to ⊥). However since our NEVER is meant to be 0, rest|NEVER is the same as rest, and I think this is the reason `MappingPairing` consider the default value to be just rest (such as [here](https://github.com/ballerina-platform/nballerina/blob/d7edbaa22e790bc9b13d1d25f52da264f981a1fb/compiler/modules/types/mapping.bal#L341)).

However, this behavior messes up the highlighted section of the algorithm 
![image](https://user-images.githubusercontent.com/17991461/180741678-ab415ab2-01a1-4628-89bf-a4e91093c4c8.png)
under the following situation

1. l is not in R_0
2. rest type of R_0 is the same as R(l)

In the paper, if l is not in R_0 highlighted section will never be true, while in our implementation currently this is not going to be the case

**Comment by manuranga** [comment]
> NEVER corresponds to ⊥

No. This is a special value called `undef` which we don't have yet.

**Comment by jclark** [comment]
`undef` is implicit in our representation. If an identifier `x` is allowed by the rest field (i.e. there's a rest field and `x` is not an individual field), then its value can be `undef`. When we have optional fields, it will also be possible for them to be `undef`.

**Comment by jclark** [comment]
When pairing up individual fields, if there's a positive that allows undef (because it comes from the rest field), and the negative doesn't (which will always be the case until we allow optional fields), then the negative cannot cancel out the positive, and so the negative can be skipped.
