### ISSUE TITLE
Report all jBallerina bugs

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#105]
There are quite a number of bugs that I have found but not reduced to a test case.

These all have a JBUG comment on them without a bug number.

This issue is to report all these and add a bug number to the comment.

**Comment by jclark** [comment]
Maybe tackle this after jBallerina beta2

**Comment by manuranga** [comment]
@gimantha is working on this
https://github.com/ballerina-platform/ballerina-lang/issues?q=is%3Aissue+is%3Aopen+label%3ANBalNeeds

**Comment by jclark** [comment]
@gimantha If you have any problems reproducing, please let me know.

**Comment by gimantha** [comment]
> @gimantha If you have any problems reproducing, please let me know.

@jclark I was able to reproduce most of the issues, but I cannot reproduce the issue here: https://github.com/ballerina-platform/ballerina-lang/issues/31327

For a simple case, I cannot reproduce this. I will have a look again, once I create issues for other comments

**Comment by gimantha** [comment]
@jclark Also, if i revert this commit locally, will I be able to reproduce this distinct error related issue(bug is mentioned in the commit itself) ? https://github.com/ballerina-platform/nballerina/commit/0ac7b5532e628028d41a4e1f1b06b9c10bd14803

**Comment by jclark** [comment]
@gimantha The problem is that with

```
public type Syntax error<Detail> & distinct error;
public type Semantic error<Detail> & distinct error;
public type Unimplemented error<Detail> & distinct error
```

it doesn't make these distinct errors: the `is` tests in testSuite.bal don't work.

I think there is a misunderstanding about how distinct types work: https://github.com/ballerina-platform/ballerina-spec/issues/864

I will explain there.
