### ISSUE TITLE
Uncertainty about `decimal` remainder output

### ISSUE THREAD

**Issue by poorna2152** [ballerina-platform/nballerina#1054]
**Description:**

Example testcase:
```
import ballerina/io;
public function main() {
    decimal d1 = 9.0E32d;
    decimal d2 =  1E-2d;
    io:println(d1 % d2); // @panic not a valid decimal
}
```
This outputs `0` in JBallerina

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by poorna2152** [comment]
The reason decimal remainder on above two numbers is giving `not a valid is decimal` is due to the `Division impossible` exception is `decNumber`.
http://speleotrove.com/decimal/daexcep.html
Quoting Division Impossible definition.

> **Division impossible**
This occurs and signals invalid-operation if the integer result of a divide-integer or remainder operation had too many digits (would be longer than precision). The result is [0,qNaN].

The lines in `decNumber `which this exception is set is, https://github.com/ballerina-platform/nballerina/blob/main/runtime/third-party/decNumber/decBasic.c#L591-L596

When a decimal remainder operation is performed `_bal_decimal_rem`  function is called  in the runtime. From there onwards the call stack until exception is set is, (bolding the functions defined in `decNumber`)
1. `_bal_decimal_rem`
2. **`decQuadRemainder`**
3. **`decFloatRemainder`**
4. **`decDivide`**


So looking at the call stack what I think is happening here is when calculating decimal remainder decNumber is going to do a division operation first. In this case if a division is performed on above two number the result is `9E34` which is 35 digits and is too many digits for decNumber. That might be the reason that `not a valid decimal` panic is occurs here

**Comment by jclark** [comment]
I get DivisionImpossible in Python (3.10.4) also

```
from decimal import Decimal
Decimal('9.0e32') % Decimal('1e-2')
```

gives

```
decimal.InvalidOperation: [<class 'decimal.DivisionImpossible'>]
```

**Comment by jclark** [comment]
Looks like Python is using https://www.bytereef.org/mpdecimal/

**Comment by jclark** [comment]
We should give a better error message. Currently panic strings have to be between 13-19 characters, which is a limitation we should get rid of.

Maybe better to change message from "not a valid decimal" to "invalid operation" for now.

**Comment by poorna2152** [comment]
After taking the look at the spec. I think answer should not be `0` and `not a valid decimal` is correct in this case.
Quoting the spec

> remainder takes two operands; it returns the remainder from integer division. If either operand is a special value then the general rules apply.
Otherwise, the result is the residue of the dividend after the operation of calculating integer division as described for divide-integer, rounded to precision digits if necessary. The sign of the result, if non-zero, is the same as that of the original dividend.
This operation will fail under the same conditions as integer division (that is, if integer division on the same two operands would fail, the remainder cannot be calculated).

As per the last sentence since division is failing here, the remainder should also fail. So nBallerina output is correct. jBallerina and wasm output is wrong.

Link for doc:
http://speleotrove.com/decimal/daops.html#refremain

**Comment by jclark** [comment]
The Ballerina spec references IEEE 754-2008 spec (which covers both decimal and binary floating point), and I don't see anything corresponding to this in that. Not sure why.

**Comment by jclark** [comment]
The Ballerina `%` operator performs the speleotrove remainder operation (same as `%` operator in C family languages). But the IEEE remainder operation is different (and corresponds to Speleotrove remainder-near operation). For remainder-near, the last sentence is the same as for remainder,

> This operation will fail under the same conditions as integer division (that is, if integer division on the same two operands would fail, the remainder cannot be calculated), except when the quotient is very close to 10 raised to the power of the precision.

But it has a [footnote](http://speleotrove.com/decimal/daops.html#footnote.10)

> This is a deviation from IEEE 754, necessary to assure realistic execution times when the operands have a wide range of exponents.

So Ballerina spec does not say enough about how decimal remainder should be performed.  Then the question is whether should it require but the speleotrove doc required, even though that has no foundation in IEEE 754.

**Comment by jclark** [comment]
@poorna2152 Please separate out the tests that generate this division impossible error into a separate files and put in a comment explaining the situation. Then we can close this issue.

**Comment by poorna2152** [comment]
To clarify what needs to be done, there are currently only two test files that comes across this ([rem6-p.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/12-decimal/rem6-p.bal), [rem7-p.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/12-decimal/rem7-p.bal)) and they only contain a single remainder operation in each one of them. Then I dont have to seperate them out right. I just have to add a comment there explaining the issue.

**Comment by poorna2152** [comment]
Also in the decimalJS library that I am using I can set the operating mode of the remainder function. If I set the operating mode to `ROUND_HALF_EVEN` then the remainder function corresponds to IEEE 754. This gives output 0 in above case
https://mikemcl.github.io/decimal.js/#modulo
