### ISSUE TITLE
SemType recursive types failure

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#1065]
If the following is added as a test case to e.g. `compiler/testSuite/semtype/recurse-t.bal`

```
type T_str ["a", T4] & readonly;
type T4 ["d", ()] & readonly;

// @type T_str < T_regex
type T_regex ["a", T2] & readonly;
type T2 (["b", T3] & readonly)| (["d", ()] & readonly);
type T3 ["c", T2] & readonly;
```

then it fails with the error:

```
                [fail] testSemTypes#'semtype/recurse-t.bal':

                    T_str is not a proper subtype of T_regex

                        expected: <anydata[]> '[true,false]'
                        actual  : <boolean[2]> '[true,true]'

                        at ballerina.test.0:createBallerinaError(assert.bal:43)
                        ballerina.test.0:assertEquals(assert.bal:112)
                        wso2.nballerina$test.0.tests.testSuite:testSubtypes(tests/testSuite.bal:210)
                        wso2.nballerina$test.0.tests.testSuite:testSemTypes(tests/testSuite.bal:38)
```

But when run with `--showTypes` it shows the correct relationships

```
T4<:T2
T_str<:T_regex
```

This test comes from translating the regex test

```
"ad" < "a(bc)*d"
```

and adding `readonly`.

The same thing happens when `readonly` is replaced by `!readonly`.  The error also happens with the tuple is replaced by a closed record with two fields.

Deepening the mystery further, if `readonly` is replaced by `any|error`, the test passes.

**Comment by jclark** [comment]
This shows up while doing #1063, because that it effectively turns each atomic list type T into `T & !readonly`.

**Comment by heshanpadmasiri** [comment]
This seems to happen only when there is more than one character inside the star e.g. `"ad" < "a(b)*d"` is working correctly

**Comment by jclark** [comment]
With #1066, we can now reproduce easily with 

```
java -jar ../../build/extra/bin/nballerina.regex.jar "ad" "a(bc)*d"
```

in `nballerina/extra/regex`

**Comment by jclark** [comment]
I tried this to fix it:

```
function listSubtypeIsEmpty(Context cx, SubtypeData t) returns boolean {
    Bdd b = <Bdd>t;
    BddMemo? mm = cx.listMemo[b];
    BddMemo m;
    if mm == () {
        m = { bdd: b };
        cx.listMemo.add(m);
    }
    else {
        m = mm;
        boolean? res = m.isEmpty;
        if res == () {
            // we've got a loop
            if cx.provisionallyEmpty == () {
                io:println("setting provisionally empty to true");
                cx.provisionallyEmpty = b;
            }
            io:println("provisionally true");
            return true;
        }
        else {
            io:println("memoize hit");
            return res;
        }
    }
    boolean isEmpty = bddEvery(cx, b, (), (), listFormulaIsEmpty);
    if cx.provisionallyEmpty != () {
        if cx.provisionallyEmpty != b {
            io:println("not memoizing because of provisionally empty");
            _ = cx.listMemo.remove(b);
            return isEmpty;
        }
        io:println("clearing provisionally empty");
        cx.provisionallyEmpty = ();
    }
    io:println("memoizing");
    m.isEmpty = isEmpty;
    return isEmpty;    
}
```

This fixes the `regex.jar "ad" "a(bc)*d"` case, but I haven't tried the rest.

I didn't realize we needed the `remove` at first, and it didn't work.  But given that we need to do the `remove`, I feel like there should be a better way to do this.

Note that proper fix needs provisionallyEmpty to hold both Bdd and which memo table (list/mapping/function) it's in.

**Comment by jclark** [comment]
@heshanpadmasiri Can you see what logic CDuce uses for this?

**Comment by jclark** [comment]
I am thinking maybe 5 values for memo.isEmpty

- true - known empty
- false - know non-empty
- "computing" - currently computing whether it is empty or not
- "provisional" - provisonally decided its empty (because of recursive call)
- nil - none of the above apply

Then we have a field provisionalCount in Context that starts at 0 and is equal to the number of memos that have value "provisional".

An isEmpty field gets set to true and false only when provisionalCount will become 0.

Not sure if it's possible for provisionalCount to become more than 1.

**Comment by heshanpadmasiri** [comment]
> @heshanpadmasiri Can you see what logic CDuce uses for this?

I couldn't figure out what CDuce does exactly. However in the [Frish thesis](http://www.cduce.org/papers/frisch_phd.pdf) section 7.1.2 (page 131) he talks about a Cache (which I presumed what CDuce does but couldn't find in the code). If I understand that correctly what we need is something like
```
function listSubtypeIsEmpty(Context cx, SubtypeData t) returns boolean {
    Bdd b = <Bdd>t;
    BddMemo? mm = cx.listMemo[b];
    BddMemo m;
    if mm == () {
        m = { bdd: b };
        cx.listMemo.add(m);
    }
    else {
        m = mm;
        boolean? res = m.isEmpty;
        if res == () {
            // Add to N and keep evaluating
            m.isEmpty = true;
            // return true;
        }
        else {
            return res;
        }
    }
    boolean isEmpty = bddEvery(cx, b, (), (), listFormulaIsEmpty);
    m.isEmpty = isEmpty;
    // Clean up if guess is wrong
    return isEmpty;    
}
```
This gets the regex relation write and also pass all of our tests

**Comment by jclark** [comment]
Interesting! Can you explain why that gets the regex relation right?

**Comment by jclark** [comment]
It is starting to make sense: it no longer returns a possibly incorrect answer that might lead to the wrong answer being cached.

Assuming this works, it's a much better fix that I was suggesting.

**Comment by jclark** [comment]
We can write this

```
        boolean? res = m.isEmpty;
        if res == () {
            // Add to N and keep evaluating
            m.isEmpty = true;
            // return true;
        }
        else {
            return res;
        }
```

as

```
        boolean? res = m.isEmpty;
        if res is boolean {
            return res;
        }
        m.isEmpty = true;
```

**Comment by heshanpadmasiri** [comment]
@jclark I made a draft PR with (#1067) which at the moment has only the changes to list memo and revert the change to regex. 
As I [mentioned](https://github.com/ballerina-platform/nballerina/pull/1067#discussion_r962262790) in the PR I am not sure this is the way we want to go.

**Comment by jclark** [comment]
You seem to be saying the algorithm here https://github.com/ballerina-platform/nballerina/issues/1065#issuecomment-1236092188 is not correct.

It seems like it has the same problem: even though we continue on rather than return, some subsequent computation may use a memoized true value, before it gets corrected to false.

**Comment by jclark** [comment]
I think I need to study the relevant part of the Frisch thesis.

**Comment by heshanpadmasiri** [comment]
If I understood the algorithm correctly, it is suppose to work as fallows

1. We will maintain two disjoint sets, named N and P in the thesis. Here P is the set of types for which we have proven to be not empty. N is the set of types we have already considered (but not proven to be not empty). (As far as I can understand this is doing 2 things as a buffer of things that we think is empty and things we have proven to be empty)
2. When we come across a new type t if it is in P it returns `true` and in N it return `false`.
3. If it come across a type not in either N or P (i.e a new type which we haven't considered so far), it will add the type N and start evaluating the `bddListFormulaIsEmpty` (in our case) to see if any other type can show t is not empty. I believe the rational behind this is if something else doesn't prove type to be non empty, then type is empty.
4. Note that while we trying to see if the type t is empty (after adding it to N) all the new types we are adding to N are conditioned to t being empty (since t is already in N) where as those added to P are not conditioned on t (since something empty can't prove something to be not empty)
5. After we have completed our evaluation if we get t as empty (from bddListFormulaIsEmpty) then our guess is right and by 4 everything new we added is correct as well
6. However in the process of evaluation we found out t is not empty by 4 everything we added to N is potentially wrong so we need to clear them from the memo


Change I did to this is instead of keeping separate datastructures for `N` and `P` I thought of using the isEmpty field in BddMemo to represent to which set they belong to (false -> N, true -> P, () -> not considered yet)

**Comment by heshanpadmasiri** [comment]
> You seem to be saying the algorithm here [#1065 (comment)](https://github.com/ballerina-platform/nballerina/issues/1065#issuecomment-1236092188) is not correct.
> 
> It seems like it has the same problem: even though we continue on rather than return, some subsequent computation may use a memoized true value, before it gets corrected to false.

Yes. Any type we have decided to be empty after starting to continue could be because we have said our type is empty (where as types we have decided to be non empty should not be affected). So we need to correct them as unknown

**Comment by jclark** [comment]
What I describe in https://github.com/ballerina-platform/nballerina/issues/1065#issuecomment-1236061588 is effectively maintaining three disjoint sets:

1. Set of types proven to be empty (isEmpty == true)
2. Set of types proven to be non-empty (isEmpty == false)
3. Set of types being considered (isEmpty == "provisional" or "computing"), but not yet proven empty/non-empty.

I don't understand why the thesis algorithm, as you describe it, has 2 sets rather than 3.

I don't understand this:

> When we come across a new type t if it is in P it returns true and in N it return false.

If it's in N, it means we are still considering it. So why return false?

**Comment by jclark** [comment]
> I thought of using the isEmpty field in BddMemo to represent to which set they belong to

Bottom of page 133, top of page 134, Frisch suggests something like this.

I still don't understand the terminology/notation of the algorithm. It's presented in a very abstract way, and I'm not sure how this maps onto our specific case.

**Comment by jclark** [comment]
Does it say anywhere that Phi corresponds to isEmpty (rather than, say, isInhabited)?

**Comment by jclark** [comment]
Compared to what I suggest here https://github.com/ballerina-platform/nballerina/issues/1065#issuecomment-1236061588, one insight is that this is not optimal

> An isEmpty field gets set to true and false only when provisionalCount will become 0.

It's only setting isEmpty to true that is provisional. Setting isEmpty to false is always correct.

Another key difference between what I suggested and what is in the Frisch thesis is that:

- Frisch removes cache entries that turn out to be invalid
- I suggest not caching entries that may turn out to be invalid

Frisch's description does not make the distinction between "computing" and "provisional" sets. I think because in Frisch's account there are multiple N sets at different levels of recursion.

**Comment by jclark** [comment]
At the top of page 134, he suggests

> il suﬃt de garder dans une pile l’historique des éléments ajoutés à N

I believe "pile"  is French for stack.

**Comment by jclark** [comment]
I think the overall structure of the algorithm we want is

- Context should have a field `BddMemo[] memoStack;`. We add to this memo's that we provisionally found to be empty.
- At the start of the listSubtypeIsEmpty function, we remember the current size of the memoStack. At the end of the function, if we discover the Bdd to be non-empty, then for all entries in the stack added since the beginning of the function, we set isEmpty to nil.
- Possibly add some new possible values for isEmpty: true should mean proven empty; false should mean proven non-empty. We need at least one possible value to mean currently being processed. Not yet sure whether we need other values. If we do, then probably better for nil to mean the same as not having an entry in the table (so we avoid removing and re-adding hash entries, which is a relatively expensive operation).

**Comment by heshanpadmasiri** [comment]
> * Context should have a field `BddMemo[] memoStack;`. We add to this memo's that we provisionally found to be empty.
> * At the start of the listSubtypeIsEmpty function, we remember the current size of the memoStack. At the end of the function, if we discover the Bdd to be non-empty, then for all entries in the stack added since the beginning of the function, we set isEmpty to nil.

Would it make sense to separate out types that are proven not empty from the rest in the memorization logic. I can think of two benefits of such an approach
1. Even if we discover at the end of the function that bdd is non-empty these values will remain non-empty. So no need to throw these results away (we only need to throw away types that we have found to be empty since they can now become non-empty, This is what Frisch does by correcting only N)
2. In theory proof that type is non-empty can be conditioned purely on types that are non-empty already. (We can't show type is non-empty using types that are being processed or once we have proven to be empty, (though a type having only latter is empty)). So having faster lookup on these (along with an algorithm that can benefit from it) may be a good optimisation combined with the first point.

**Comment by heshanpadmasiri** [comment]
@jclark I think our algorithm should be something like this (updated #1067 to match)
```
// listMemo is P
// memoStack is N
function listSubtypeIsEmpty(Context cx, SubtypeData t) returns boolean {
    Bdd b = <Bdd>t;
    BddMemo? mm = cx.listMemo[b];
    if mm !is () {
        // TODO see if we can use listMemo to tell us something is in memostack (set isEmpty to ()) for faster lookup
        // Everything in listMemo is known for sure so can't be optional
        boolean res = <boolean>mm.isEmpty;
        return res;
    }
    else {
        // this is a type we don't yet know the answer to
        if cx.isInStack(b) {
            // this is a type we are computing (so we assume it is empty) (type is in N)
            return true;
        }
        // this is completely new to us so put in in the computing stack and continue
        BddMemo m = { bdd: b };
        int initialStackSize = cx.memoStack.length();
        cx.memoStack.push(m);
        boolean isEmpty = bddEvery(cx, b, (), (), listFormulaIsEmpty);
        if !isEmpty {
            // move t to P and clear the stack
            cx.listMemo.add({ bdd: b, isEmpty });
            cx.memoStack.setLength(initialStackSize);
        }
        // else {
            // do nothing (we don't change N)
        // }
        return isEmpty;
    }
}
```

**Comment by jclark** [comment]
In the isEmpty case, things will get pushed on the memoStack but not popped off.

**Comment by jclark** [comment]
I also think (as you suggest in the TODO) that we should continue to use an isEmpty value of () to capture whether it is on the stack.

**Comment by jclark** [comment]
Can we clear the stack when initialStackSize is 0?

**Comment by jclark** [comment]
Another problem with this approach is that we are not memoizing in the case where isEmpty == true.

**Comment by jclark** [comment]
Here's another attempt:

```ballerina
function listSubtypeIsEmpty(Context cx, SubtypeData t) returns boolean {
    Bdd b = <Bdd>t;
    BddMemo? mm = cx.listMemo[b];
    BddMemo m;
    if mm == () {
        m = { bdd: b };
        cx.listMemo.add(m);
    }
    else {
        m = mm;
        boolean? res = m.isEmpty;
        if res is boolean {
            return res;
        }
        else if m.recurseLevel > 0 {
            if m.recurseLevel == 1 {
                m.recurseLevel = 2;
                cx.loopCount += 1;
            }
            return true;
        }
        // recurseLevel == 0 is same as not having an entry
    }
    m.recurseLevel = 1;
    boolean isEmpty = bddEvery(cx, b, (), (), listFormulaIsEmpty);
    if cx.loopCount > 0 {
        if m.recurseLevel == 2 {
            cx.loopCount -= 1;
        }
        if isEmpty && cx.loopCount > 0 {
            m.recurseLevel = 0;
            return isEmpty;
        }
    }
    m.recurseLevel = 0;

    m.isEmpty = isEmpty;
    return isEmpty;    
}:
```

This assumes a field in BddMemo (which would be combined with isEmpty)

```ballerina
    // 0 means no recursion active
    // 1 means active
    // 2 means we got a loop
    int recurseLevel = 0;
```

and a field in Context:

```ballerina
    // number of memos with recurseLevel == 2
    int loopCount = 0;
```

The concept is that when `cx.loopCount > 0` we are depending on an assumption that may turn out to be invalid and so we do not cache any results that turn out as isEmpty.

**Comment by heshanpadmasiri** [comment]
I think the main advantage of this approach over any implementation I can think of from the Frishes approach is that this doesn't need to undo anything.

**Comment by jclark** [comment]
One could argue that it is inefficient because when the assumption of emptiness turns out to be correct, it will sometimes not memoize things that it could have memoized.  But I suspect it wouldn't be a net win to do such memoization.

**Comment by heshanpadmasiri** [comment]
Updated version of my implementation based on what we discussed
```
// listMemo is P
// memoStack is N
// maintain invariant that isEmpty is () iff it is on the memoStack
// no duplicates on stack
function listSubtypeIsEmpty(Context cx, SubtypeData t) returns boolean {
    Bdd b = <Bdd>t;
    BddMemo? mm = cx.listMemo[b];
    BddMemo m;
    int initialStackSize = cx.memoStack.length();
    if mm == () {
        // this is completely new to us so put it in the computing stack and continue
        m = { bdd: b };
        cx.memoStack.push(m);
        cx.listMemo.add(m);
    }
    else {
        m = mm;
        boolean? res = m.isEmpty;
        if res is boolean {
            // This is a type is know for sure
            return res;
        }
        // this is a type we are computing(ie. type is in N). So we assume it is empty
        return true;
    }
    boolean isEmpty = bddEvery(cx, b, (), (), listFormulaIsEmpty);
    if !isEmpty || initialStackSize == 0 {
        // if initialStackSize == 0 we should not have any pending types
        // is isEmpty is false (i.e type is non-empty) it safe to move it to P (only something that is empty can change to non-empty)
        // in both cases type is no longer pending so we move it from N to P and clear the stack (up to level when we pushed t)
        m.isEmpty = isEmpty;
        reduceStackLength(cx, initialStackSize);
    }
    return isEmpty;    
}

function reduceStackLength(Context cx, int newLength) {
    foreach int i in newLength ..< cx.memoStack.length() {
        _ = cx.listMemo.remove(cx.memoStack[i].bdd);
    }
    cx.memoStack.setLength(newLength);
}
```

**Comment by jclark** [comment]
This one seems to be inconsistently mixing using a nil value for isEmpty and a stack.

**Comment by jclark** [comment]
I think I prefer the approach in https://github.com/ballerina-platform/nballerina/issues/1065#issuecomment-1237745628

* it needs only an additional integer variable in context, plus some additional possible values for isEmpty
* it changes the current behaviour only in the case where there's a recursive loop

**Comment by heshanpadmasiri** [comment]
Agreed. In the meantime I will look in to #1069 to better test recursive types

**Comment by jclark** [comment]
I think more testing (specifically #1076) is showing that this isn't right.

**Comment by jclark** [comment]
Specifically we need to memoize while `provisionalEmptyCount > 0`.
