### ISSUE TITLE
Stress recursive type implementation by generating regex pairs

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1069]
Currently we are using regular expressions to test and validate recursive list type implementation. Therefore it is useful if we have some system that will generate such tests. We could use a somewhat simpler version of the approach used for [property based testing](https://github.com/ballerina-platform/nballerina/issues/877) to do that.

**Comment by jclark** [comment]
I would like to find some cases where cx.provisionalEmptyCount is greater than 1. I think it is possible but not 100% sure.
