### ISSUE TITLE
Implement the getelementptr instruction in nback.llvm

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#107]
@jclark for this I am planning to add the fallowing functions to the builder:
1.`gep(Value ptr, Value[] indices, string? name=()) returns Value` similar to https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gaf392c575dd594d83894d3e71a520ffa4 
2. `inBoundsGep(Value ptr, Value[] indices,string? name=()) returns Value` similar to https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gae4f1ccf18cdf461af2e5d36178464d80 
(I am not sure if we need 2 at the moment.) We can also combine the 1 and 2 as `gep(Value prt, Value[] indices, bool? isInBound)`

**Comment by jclark** [comment]
We don't need the `inbounds` case.

We should follow the name of the instruction: so `getElementPtr`. We only need a simple version for now: `getElementPointer(PointerValue ptr, Value index)`

**Comment by jclark** [comment]
@heshanpadmasiri Note that GEP returns a pointer (it's like pointer addition in C). I fixed your code in https://github.com/ballerina-platform/nballerina/commit/8e6d26a8cdf50382cd86f432d1bb3988bf716965

Please use clang to check that your `.ll` test outputs are correct.
