### ISSUE TITLE
Incorrect regular expression relations

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1075]
Following regular expression relations will produce an incorrect relationship (not equal) when the expected relationship is less than (tested both inside testerina and by directly running regex jar file)

1. `(JRBB(U(yeNTW)*W)*mlJQv)*xIZVP`, `(JRBB(U(yeNTW(CoePqmjQbZ)*)*W)*mlJQv)*xIZVP`
2. `(JRBB(U(yeNTW(CoePqmjQbZ)*)*W)*mlJQv)*xIZVP`,  `(JRBB(U(yeNTW(C(KCQCY)*oePqmjQbZ)*)*W)*mlJQv)*xIZVP`

I haven't confirmed whether regex produces the correct types and the type checker is failing or regex is producing the wrong type. I will update this comment as new pairs are discovered with the same error

**Comment by jclark** [comment]
You could try the types with CDuce.

**Comment by heshanpadmasiri** [comment]
I think this is a bug in regex not in subtyping (confirmed by passing the expected semtype tests)
