### ISSUE TITLE
Integrate cells into mapping type

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/nballerina#1079]
**Description:**
$subject.

**Comment by jclark** [comment]
I suggest we adopt the convention that functions operating on a mapping type that dereference the cell have `deref` in the name.

For every (or almost every) existing public function in the types module that looks inside a MappingAtomicType and returns a SemType for the member(s), we will need to a `deref` variant that returns the type inside the cell.  In most cases, we will need just the deref variant.  In some cases, the deref version can be written in terms of the existing version; in other cases it cannot.

The changes outside the types module should mostly consist of changing to call `deref` variant.
