### ISSUE TITLE
Implement llvm.ptrmask intrinsic in nback.llvm

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#108]
@jclark  with regards to the api we can add a new `IntrinsicFunctionName` as `ptrmask` and modify the `getIntrinsicDeclaration` to handle this. I am also thinking of modifying `getIntrinsicDeclaration` so it adds the relevant function attributes inside the `getIntrinsicDeclaration` function itself without relying on the user to use the `addEnumAttribute` for intrinsics.

**Comment by jclark** [comment]
The function name would need to be the right overload `ptrmask.p0i8.i64`.

I agree with adding the attributes automatically.

**Comment by heshanpadmasiri** [comment]
I'll use the `ptrmask.p0i8.i64` as the `IntrinsicFunctionName`
