### ISSUE TITLE
Implement ptrtoint instruction in nback.llvm

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#109]
@jclark for this I am planning to add a new function to the builder as `ptrToInt(Value ptr, IntType destinationType, string? name=()) returns Value` similar to https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gadc4471c1a7c0a701adcf601af1e87b7f. If the destination is always going to be `i64` perhaps we can remove that parameter from the function or make it optional (if not defined it will take the base type from the `ptr`)

**Comment by jclark** [comment]
Shouldn't type of first arg be PointerValue?

**Comment by heshanpadmasiri** [comment]
> Shouldn't type of first arg be PointerValue?

Yes that's my bad the function signature should be `ptrToInt(PointerValue ptr, IntType destinationType, string? name=()) returns Value`

**Comment by jclark** [comment]
LGTM
