### ISSUE TITLE
Integrate cells into table type

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/nballerina#1095]
**Description:**
$subject.

**Comment by lochana-chathura** [comment]
Sample:
```bal
type X1 record {|
    int id;
|};

type X2 record {|
    string id;
|};

type T1 table<X1>;
type T2 table<X2>;
type T3 T1|T2;
type T4 table<X1|X2>;
```
With adding cells into the table type, T3 and T4 are no longer equivalent.

**Comment by jclark** [comment]
In `table<T>` the T is working like with `...` in mappings or lists e.g. `record {| T...;  |}`  or `[T...]`. When we have readonly tables, then it's like `record {| readonly T...; |}`.

When you do `table:put` and the keys are the same, then you are effectively mutating a cell.

**Comment by pcnfernando** [comment]
Clarification regarding the immutability when we are referring to **read-only tables**;
Isn't `table<T>  & readonly` is equivalent to `table<T & readonly> & readonly` same as how `map<T> & readonly` is equivalent to `map<T & readonly> & readonly`?

**Comment by jclark** [comment]
> Isn't `table<T>  & readonly` is equivalent to `table<T & readonly> & readonly` same as how `map<T> & readonly` is equivalent to `map<T & readonly> & readonly`?

Sure.
