### ISSUE TITLE
Change the references going from top to bottom

### ISSUE THREAD

**Issue by shubhamnarlawar** [ballerina-platform/nballerina#11]
**Description:**
It's better if we can have the references going from top to bottom, (eg Module->Function->BB->Instruction) but not the other way around.

**Comment by Kishanthan** [comment]
@shubhamnarlawar @ruvi-d can this be closed?

**Comment by ruvi-d** [comment]
Yes +1

**Comment by shubhamnarlawar** [comment]
Yes +1
