### ISSUE TITLE
Implement the bitcast instruction in nback.llvm

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#110]
@jclark  for this I am planning to add a new function to the builder as `bitcast(Value val, IntType destType, string? name=()) returns Value` similar to https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga1d8e6d373823d51438bf4889af6ff08a.

**Comment by jclark** [comment]
Shouldn't destType be a PointerType?

**Comment by heshanpadmasiri** [comment]
> Shouldn't destType be a PointerType?

Bitcast don't necessarily has to be to a pointer type if I understand it correctly (things like `%X = bitcast i8 255 to i8` are valid) but if in our case we are going to stick to pointers to destination I'll change the destination type

**Comment by jclark** [comment]
So far we only need pointers, so let’s stick to that for now.
