### ISSUE TITLE
Invalid code generation in type narrowing

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1114]
In the llvm-ir generated for the following two test cases, there is a call for `_bal_tagged_to_float` that is getting called even if the type check shows the value is not a `float`. (I believe what is happening here is that the (implicit) else part that narrows the type to be float if the type check fails is getting merged into rest of the code)
1. [12-narrow/if21-v.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/12-narrow/if21-v.bal)
2. [14-bug/loopassign-v.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/14-bug/loopassign-v.bal)

Corresponding function calls
1. [12-narrow/if21-v.ll](https://gist.github.com/heshanpadmasiri/7f1d61f5a369659cefe01169e60e02e2#file-if21-v-ll-L57)
2. [14-bug/loopassign-v.ll](https://gist.github.com/heshanpadmasiri/7f1d61f5a369659cefe01169e60e02e2#file-loopassign-v-ll-L48)

It seems these function calls are getting optimized away under the default optimization setting (`-O2`) we are using but if we use (`-O0`) we will get a segfault.

[Link to the original comment that discusses this issue](https://github.com/ballerina-platform/nballerina/issues/1082#issuecomment-1306998115)

**Comment by jclark** [comment]
Looking at 12-narrow/if21-v.ll, I suspect a bug in the front-end related to type narrowing and joining. The call to _bal_tagged_top_float happens in block 30. There's one branch to that from line 38, which happens after a type test that x's basic type is not in the set int|boolean|string (which is represented by the 38 in line 36); this looks OK.  But there's another branch from line 95, which can happen when the type is something else.  That doesn't look right to me.

**Comment by manuranga** [comment]
2-narrow/if21-v visualized https://bit.ly/3hz20Ru

**Comment by manuranga** [comment]
Found the issue.
We create new narrowed register for each outcome of a type branch. Narrowed register is just a read-only copy.
They are blindly injected at the top of each target block. 
```ballerina
function f(int|float x) {
    if x is int {
        printInt(x);
        return;
    }
    printFloat(x)
}
```
![init-narrow](https://user-images.githubusercontent.com/1686124/201093326-426e40be-301d-4259-bc64-edf4ecd284c3.png)

This has an issue if the given target block is reachable via some other path

```ballerina
function f(int|float|boolean x) {
    if x is int|float
        if x is int {
            printInt(x);
            return;
        }
    }
    print("float or bool");
}
```
![init-narrow-unusable](https://user-images.githubusercontent.com/1686124/201095867-dfdcd6e0-2e03-4cce-8c9a-f1cd0fe8ae1b.png)

**Comment by manuranga** [comment]
Solutions

1) Initialize narrow registers just before (each) first use.
We did discuss this approach when first implemented but ruled out due to complexity.

![init-narrow-muliple](https://user-images.githubusercontent.com/1686124/201109504-a7807845-9ef1-440a-8d20-7ffc08cac879.png)

2) Create additional llvm basic blocks to initialize narrow registers.
![init-narrow-pre-bb](https://user-images.githubusercontent.com/1686124/201110313-5a296ff9-8630-45d8-8259-aa0f088904a1.png)

**Comment by manuranga** [comment]
3. Initialize narrow registers just after TypeMerge instructions. Skip any registers that got merged.
