### ISSUE TITLE
Update llvm backends to use opaque pointers

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1116]
As of LLVM 16,  C API no longer has [`LLVMConstGEP`](https://github.com/ballerina-platform/nballerina/blob/b349ae2f4540b260650271f7891403dae012c370/llvm_jni/modules/jni.llvm/Context.bal#L125) and [`LLVMConstInBoundsGEP`](https://github.com/ballerina-platform/nballerina/blob/b349ae2f4540b260650271f7891403dae012c370/llvm_jni/modules/jni.llvm/Context.bal#L131) functions, instead, it has [`LLVMConstGEP2`](https://llvm.org/doxygen/group__LLVMCCoreValueConstantExpressions.html#gae355c965dacae2f840ad9c1e8b60f885) and [`LLVMConstInBoundsGEP2`](https://llvm.org/doxygen/group__LLVMCCoreValueConstantExpressions.html#ga7bd51db0c1eec33d38b10cccc356d35f). Once [bytedeco llvm presets](https://github.com/bytedeco/javacpp-presets/tree/master/llvm) has been updated to llvm 16 we will need to rewrite those functions in `jni.llvm`

**Comment by jclark** [comment]
Maybe related https://bugs.llvm.org/show_bug.cgi?id=41362

**Comment by heshanpadmasiri** [comment]
Things I have managed to confirm so far are as follows

1. llvm C-API for llvm 15 does have the newer `LLVMConstGEP2` and `LLVMConstInBoundsGEP2` functions ([ref](https://web.archive.org/web/20220521225015/https://llvm.org/doxygen/group__LLVMCCoreValueConstantExpressions.html#gae355c965dacae2f840ad9c1e8b60f885))
2. [Above bug](https://bugs.llvm.org/show_bug.cgi?id=41362l) seems to have been fixed (at least in the code base not sure if change is in the release) with [this](https://reviews.llvm.org/D115787)
3. The change in function signature seems to accommodate [opaque pointers](https://llvm.org/docs/OpaquePointers.html), which is a [new feature in llvm 15](https://llvm.org/docs/OpaquePointers.html).

**Comment by jclark** [comment]
We are definitely going to need to update to use opaque pointers.

**Comment by jclark** [comment]
If I am understanding correctly, the difference with the GEP2 functions is that you have to explicitly specify the type of the thing pointed to.  Do we have that information conveniently available?

**Comment by jclark** [comment]
Does byte-deco have the GEP2 functions for llvm15?

**Comment by heshanpadmasiri** [comment]
One small addition for [this](https://llvm.org/doxygen/group__LLVMCoreValueConstantGlobalAlias.html#gad4dfb6341f8c010227673b2756d09aeb) all the following functions have changed (as far as I can work out every function that takes a pointer)
+ `LLVMBuildLoad` -> [`LLVMBuildLoad2`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga025026f91ebe29901a52f5f261f3fc57)
+ `LLVMBuildCall` -> [`LLVMBuildCall2`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga821864790c90dc5193078c4e17b8cb09)
+ `LLVMBuildGEP` -> [`LLVMBuildGEP2`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gacaeda0ff783160af64d0d27a5dc2c836)
+ `LLVMBuildInBoundsGEP` -> [`LLVMBuildInBoundsGEP2`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gaa67a3cd902bea7e7c1b8185f0c23fc13)
+ `LLVMConstGEP` -> [`LLVMConstGEP2`](https://llvm.org/doxygen/group__LLVMCCoreValueConstantExpressions.html#gae355c965dacae2f840ad9c1e8b60f885)
+ `LLVMConstInBoundsGEP` -> [`LLVMConstInBoundsGEP2`](https://llvm.org/doxygen/group__LLVMCCoreValueConstantExpressions.html#ga7bd51db0c1eec33d38b10cccc356d35f)
+ `LLVMAddAlias` -> [`LLVMAddAlias2`](https://llvm.org/doxygen/group__LLVMCoreValueConstantGlobalAlias.html#gad4dfb6341f8c010227673b2756d09aeb)

However, bytedeco is missing the ConstGEP2 and ConstInboundsGEP2 functions (it has all the other changes)

**Comment by jclark** [comment]
I am guessing the missing functions in bytedeco is just a bug, which we should report.

**Comment by jclark** [comment]
It seems to me the issue here is really opaque pointers rather than constant expressions.

**Comment by heshanpadmasiri** [comment]
> If I am understanding correctly, the difference with the GEP2 functions is that you have to explicitly specify the type of the thing pointed to. Do we have that information conveniently available?

Yes that is the change (+ possible changes in the actual IR generated)
At the moment no but I think we can easily do that with either,
1. When we create the `Value` we can have an additional field that holds onto the type (we already do this in [print.llvm ](https://github.com/ballerina-platform/nballerina/blob/7a4c8f93f8d4fec3e6cb1dc831f68cf10a7664dc/compiler/modules/print.llvm/llvm.bal#L31), `jni.llvm` currently ignore this since so far it didn't need to know)
2. We can use [`LLVMTypeOf`](https://llvm.org/doxygen/group__LLVMCCoreValueGeneral.html#ga12179f46b79de8436852a4189d4451e0) function to get the type of `LLVMValue`

**Comment by jclark** [comment]
Will approach 2 work when we switch to opaque pointers? I guess not, since it will be a type-less, opaque pointer.

**Comment by heshanpadmasiri** [comment]
> Will approach 2 work when we switch to opaque pointers? I guess not, since it will be a type-less, opaque pointer.

I don't think it will work at that point, I believe what they recommend in the [migration guide](https://llvm.org/docs/OpaquePointers.html#migration-instructions) (2 was based on that) is for people still not using opaque pointers.
