### ISSUE TITLE
Fix the way the nback.llvm API handles alignment

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#112]
At the moment alignment is part of PointerType, which is not how the LLVM API does things, and is also not conceptually right.

**Comment by jclark** [comment]
@heshanpadmasiri Any ideas how to fix this?

**Comment by jclark** [comment]
See https://github.com/ballerina-platform/nballerina/commit/ac0f9a0f64fd8645d42e0a3f6576622d8db9dfae for an example of where things are not working right.

**Comment by heshanpadmasiri** [comment]
@jclark  can't we infer the alignment based on the type it pointsTo? If so we can have separate function (not part of the public API) that does that and where we need it (I assume this is only for the builder at the moment) we can pass the `PointerValue` directly to that function and have it return the alignment

**Comment by jclark** [comment]
@heshanpadmasiri There must be something in the C API that allows control over alignment.

But perhaps we can just leave it out from the `.ll`. It's not required and will be defaulted by the target, so perhaps that's the best thing to do.

**Comment by jclark** [comment]
This makes it clear what is going on:

https://llvm.org/doxygen/IR_2Core_8cpp_source.html#l02064

The alignment is associated with the store/load/alloca, but it can be left out.

**Comment by jclark** [comment]
I fixed this in b068365d00a1af27951f29bd6de5496b38ed1a83

@heshanpadmasiri I wasn't very careful in fixing up the test cases. Should probably have some test cases for explicit alignment (which we will use for heap alignment)
