### ISSUE TITLE
Change `jni.llvm` to use TypeInContext

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1138]
In order to translate [our representations of llvm types](https://github.com/ballerina-platform/nballerina/blob/6710eabe3f50bdb5105dd319200893e3c110b1ec/compiler/modules/print.llvm/common.bal#L55) to `LLVMTypeRef` jni.llvm uses [`typeToLLVMType`](https://github.com/ballerina-platform/nballerina/blob/6710eabe3f50bdb5105dd319200893e3c110b1ec/llvm_jni/modules/jni.llvm/Type.bal#L3) function which optionally takes a `Context`. We need to make `Context` required so we can use `LLVM{TypeName}TypeInContext` over `LLVM{TypeName}Type` [here](https://github.com/ballerina-platform/nballerina/blob/6710eabe3f50bdb5105dd319200893e3c110b1ec/llvm_jni/modules/jni.llvm/Type.bal#L29). (This is required for #1116)

Apart from the following 3 cases, we can do this simply due to the fact types are used with other llvm constructs such as `Builder`, `Module`, etc. all of which have a reference to the `Context`
1.[ `constInt`](https://github.com/ballerina-platform/nballerina/blob/6710eabe3f50bdb5105dd319200893e3c110b1ec/compiler/modules/print.llvm/llvm.bal#L70)
2.[ `constFloat`](https://github.com/ballerina-platform/nballerina/blob/6710eabe3f50bdb5105dd319200893e3c110b1ec/compiler/modules/print.llvm/llvm.bal#L79)
3. [`constNull`](https://github.com/ballerina-platform/nballerina/blob/6710eabe3f50bdb5105dd319200893e3c110b1ec/compiler/modules/print.llvm/llvm.bal#L109)

With regard to refactoring the above functions, the fallowing ideas have been discussed.
1. In most cases we are using these functions (especially `constInt`) we are using it to create either `i64` (primarily for ballerina integer values), `i32` (indices since GEP instructions don't support `i64`), `i1` (represent booleans). Therefore create dedicated helper functions for these common cases such as `constInt64`
2. Have these helper functions take a `Builder` as an argument (in most cases we call the above 3 functions we don't have direct reference to `Context` but we have a reference to `Builder`), and the function will get the `Context` via `Builder`

One problem with 2 is in the [`init.bal`](https://github.com/ballerina-platform/nballerina/blob/main/compiler/modules/nback/init.bal) we don't use a `Builder` in most functions (but in all those cases we have access to `Context` via the `InitModuleContext` so one workaround would be for 2 to take `Builder|Context` instead of `Builder`) 

Another option for 2 is to take the `Context` itself instead of `Builder`. For this `Scaffold` will have something like `function llContext() returns llvm:Context => self.mod.llContext` (and `int.bal` will get the context via `InitModuleContext`)

**Comment by jclark** [comment]
I note we have `buildConstNil` and `buildBoolean` functions.

**Comment by heshanpadmasiri** [comment]
It seems to me that we can replace many of the calls to `constNull` (with the exception of cases where the pointer type is not `i8 ` in address space 1) and replace all the calls to `constInt` with `LLVM_BOOLEAN` as the type. That being said maybe it is better to have these helper functions in llvm (and perhaps make the general cases not visible outside of the llvm modules) so we won't forget to use the helper functions down the line.
