### ISSUE TITLE
Add support for context in nback.llvm

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#114]
@jclark for this I am thinking of adding fallowing to the public API

1. Public record type `Context` to represent [LLVMContextRef](https://llvm.org/doxygen/group__LLVMCSupportTypes.html#ga9c43e01525516ff6b4feab5166c5b1da). Initially this can be an empty place holder since we only need this to have API similar to what we get with #19.
2. Public function `createContext() returns Context` similar to https://llvm.org/doxygen/group__LLVMCCoreContext.html#gaac4f39a2d0b9735e64ac7681ab543b4c.
3. All public constructors ([`Module`](https://llvm.org/doxygen/group__LLVMCCoreModule.html#ga6bf4a0a387cf7fe04cbe0438cdb36a51), [`Builder`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga720a9461e32f7c3d72011bfd6724f92f)) will take `Context` as their first argument(Java api needs a name for module as well so I'll modify our constructor to take an optional name parameter)
4. Other constructors such as those for functions will get the context from the parent (module in the case of function)

I am assuming when it comes for types we can ignore the context even though we use it in other places (ex for `i64` use [`LLVMInt64Type`](https://llvm.org/doxygen/group__LLVMCCoreTypeInt.html#ga0a46c5d828749b932cc728159fcf129a) instead of [`LLVMInt64TypeInContext`](https://llvm.org/doxygen/group__LLVMCCoreTypeInt.html#ga213ec0fe49543773320798d7cb619746) in the C api. If not constant constructors (ex:`intConst`) will also need `Context` as an argument. (In otherplaces we should be able to get the context from parent (In most cases builder)).

**Comment by jclark** [comment]
Sorry, I didn't get to this earlier: I was busy with  #94.

This is not quite right:

- item 1 should be a class (not distinct)
- item 2 should be a public constructor of the class
- items in 3 should be done by createXXX method calls on Context, with the corresponding constructor no longer public

For types, you would need to make the appropriate calls to the C api with a context to construct the Ballerina type values.
