### ISSUE TITLE
Result type of shift operators is incorrect

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1145]
Currently, the result type for shift expression is the union of type of the two operands (according to code [here](https://github.com/ballerina-platform/nballerina/blob/016c743511e152dc889e9e6b11c3481c742fbed3/compiler/modules/front/expr.bal#L839)). However according to [spec](https://ballerina.io/spec/lang/master/#section_6.25) "If the operator is >> or >>> and the left hand operand is a subtype of int:UnsignedK when K is 8, 16 or 32, then the static type of the result is int:UnsignedN where N is the smallest such K; otherwise, the static type of the result is int. In all cases the static type of the result is modified by the usual singleton typing rules."

This leads to invalid results in cases such as,
```
import ballerina/io;
public function main() {
    int:Unsigned8 x = 250;
    int:Signed8 a = 2;
   
    int:Unsigned8 x1 = x >> a; // error: value is not a subtype of the LHS
}
```
```
import ballerina/io;
public function main() {
    int:Unsigned8 a = 255;
    int:Unsigned8 b = 63;
    io:println(a << b); // should be -9223372036854775808 but gets 0
}
```

**Comment by jclark** [comment]
Implement last paragraph of this:

https://ballerina.io/spec/lang/2022R4/#section_6.25

**Comment by jclark** [comment]
Currently computed as union of operand types, which is completely wrong.
