### ISSUE TITLE
Extend BIR to support closures

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1224]
Required for #908 and #909

# BIR instructions
## `ConstructLocalFunction` 
+ I think this should take as the operand some sort of handle that points to the `FunctionCode` for the lambda.
+ Then `nback` will lift the function to the module scope (see LLVM representation of closures)

# LLVM representation of closures
- LLVM doesn't have a concept of nested functions*, therefore we have to lift the function to the module level. 
  - LLVM has the[ `trampoline` intrinsic ](https://llvm.org/docs/LangRef.html#trampoline-intrinsics) which are used to support [GCC nested functions ](https://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html). But I don't think this is what we need since we want our closures to be in the heap not stack.
- Typically (I check c++ and rust) this lifted function will take a struct that "holds the closure" as the first argument and the rest will be the arguments to the lambda
  - In cpp this is the `%class.anon` part  
- Then at the beginning of the lambda you load each value in the closure struct to separate registers
- [examples](https://github.com/heshanpadmasiri/closure-tests)

cc @manuranga @jclark

**Comment by jclark** [comment]
I suggest we change FunctionDefn to Function, where a Function is either a FunctionDefn or an AnonFunction. AnonFunction has a ref to its parent, which for now is either an AnonFunction or a FunctionDefn, but could allow another top-level construct in the future. Then we replace getFunctionDefns by getFunctions returniing Function[]. The index into this is a handle for the FunctionCode. FunctionCode then includes an int[] giving the indices of the child AnonFunctions.  We have a FunctionConstructInsn which has gives a handle to the AnonFunction.

We then have CaptureRegister which is an additional kind of register used for references to captured variables (analogous to NarrowRegister). It always refers to the parent and has an int giving the index in the parent.

For nested capturing, every level captures. For example:

```
function foo() returns int {
  int x = 1;
  var f = function() returns int {
    var g = function() returns int { return x; }
    return g();
  }
  return f();
}
```

The function f has a CaptureRegister that refers to x in foo. Then g has a CaptureRegister that refers to the CaptureRegister in the function bound to f.

If you think about it, evaluating the outer anon function expression does not evaluate the inner anon function expression, so the evaluation of the outer function expression has to capture x so it can be captured when `f()` is evaluated (which will cause evaluation of the inner anon function expression). Phew!

**Comment by jclark** [comment]
Variables that are captured may need to be stored on the heap. But there's an optimization called "escape analysis" that is typically done to allow some captured variables to be stored on the stack. So it's probably best to leave analysis of capturing to the backend. In the BIR captured variables are not treated specially in the function that declares them. So in the above example, `x` in foo is just a VarRegister as normal. The backend will need to determine that it's captured. Note that in this case, it's not actually necessary to store x on the heap, because the f's lifetime does not extend past x's lifetime. But that's an optimization that the backend may or may not want to do.

**Comment by heshanpadmasiri** [comment]
> Variables that are captured may need to be stored on the heap. But there's an optimization called "escape analysis" that is typically done to allow some captured variables to be stored on the stack. So it's probably best to leave analysis of capturing to the backend. In the BIR captured variables are not treated specially in the function that declares them. So in the above example, `x` in foo is just a VarRegister as normal. The backend will need to determine that it's captured. Note that in this case, it's not actually necessary to store x on the heap, because the f's lifetime does not extend past x's lifetime. But that's an optimization that the backend may or may not want to do.

LLVM has an analysis pass called [`CaptureTracking`](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/CaptureTracking.cpp) which is used by other optimization passes (though I don't think llvm has optimizers can move values from heap to stack).
