### ISSUE TITLE
Make it possible for older jBallerina versions to use nBallerina for validation

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1227]
Currently for jBallerina versions 2201.4.x to 2201.7.x being able to run ballerina tests (i.e. running `bal test` in the compiler directory) is used as a validation step. When we update our jBallerina dependencies and remove workarounds this step fails for older versions of jBallerina. There are several ways we can avoid this
1. Have separate branches in nBallerina repo for each jBallerina version with the corresponding workarounds
2. Create patch files for each of the jBallerina versions to revert the workaround removals

**Comment by manuranga** [comment]
> 2. Create patch files for each of the jBallerina versions to revert the workaround removals

and keep them in respective jBallerina test workflows.

**Comment by heshanpadmasiri** [comment]
Resolved with https://github.com/ballerina-platform/ballerina-release/pull/2505
