### ISSUE TITLE
Moving to rust strings

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/nballerina#125]
**Description:**

- [x]  move plain strings to rust

ie:
```ballerina
string s = "hello";
```
Above should call rust and get a pointer to the rust string. Try to use `from_raw_parts` to avoid unnecessary memory allocations.

- [ ] Migrate existing rust functions to use string  

functions such as print and map get needs to be migrated.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shubhamnarlawar** [comment]
For this feature, is there such conversion present at rust side? Can anyone point it out the scenario?

For the typechecker, I am receiving a NULL terminated string pointer from LLVM side. I am converting it to Rust string and operating on it.

@ruvi-d - Does bal map consist any such string on which `std::sllice::from_raw_parts` can be applied?

**Comment by ruvi-d** [comment]
> For this feature, is there such conversion present at rust side? Can anyone point it out the scenario?
> 
> For the typechecker, I am receiving a NULL terminated string pointer from LLVM side. I am converting it to Rust string and operating on it.
> 
> @ruvi-d - Does bal map consist any such string on which `std::sllice::from_raw_parts` can be applied?

Let me try to clarify the requirement. Currently we handle Ballerina strings types as C style char* arrays. But we should be modelling Ballerina strings as a Rust type that exposes Ballerina string features. e.g. When we are doing codegen for Ballerina `string val = "hello";` we need to pass "hello" to Rust and get back an opaque pointer to Ballerina String type object. So, in LLVM IR val will now hold a pointer to Rust object. It is this opaque pointer that we will use for things like map and print. The suggestion to use `from_raw_parts`, is to prevent unnecessary copies of "hello".

This does not apply to typecheker's mangled type string, which is an internal implementation detail for nBallerina. That should continue to use the current c-style char*. 

Hope it's clear?

**Comment by shubhamnarlawar** [comment]
> > For this feature, is there such conversion present at rust side? Can anyone point it out the scenario?
> > For the typechecker, I am receiving a NULL terminated string pointer from LLVM side. I am converting it to Rust string and operating on it.
> > @ruvi-d - Does bal map consist any such string on which `std::sllice::from_raw_parts` can be applied?
> 
> Let me try to clarify the requirement. Currently we handle Ballerina strings types as C style char* arrays. But we should be modelling Ballerina strings as a Rust type that exposes Ballerina string features. e.g. When we are doing codegen for Ballerina `string val = "hello";` we need to pass "hello" to Rust and get back an opaque pointer to Ballerina String type object. So, in LLVM IR val will now hold a pointer to Rust object. It is this opaque pointer that we will use for things like map and print. The suggestion to use `from_raw_parts`, is to prevent unnecessary copies of "hello".
> 
> This does not apply to typecheker's mangled type string, which is an internal implementation detail for nBallerina. That should continue to use the current c-style char*.
> 
> Hope it's clear?

Got it. Now, it is clear. 
Thanks for the detailed explanation!

**Comment by shubhamnarlawar** [comment]
> **Description:**
> 
>     * [x]   move plain strings to rust
> 
> 
> ie:
> 
> ```ballerina
> string s = "hello";
> ```
> 
> Above should call rust and get a pointer to the rust string. Try to use `from_raw_parts` to avoid unnecessary memory allocations.
> 
>     * [ ]  Migrate existing rust functions to use string
> 
> 
> functions such as print and map get needs to be migrated.
> 
> **Suggested Labels:**
> 
> **Suggested Assignees:**
> 
> **Affected Product Version:**
> 
> **OS, DB, other environment details and versions:**
> 
> **Steps to reproduce:**
> 
> **Related Issues:**

Created an issue #216 for second subtask.
