### ISSUE TITLE
Design of Error type

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/nballerina#126]
**Description:**
Start the design discussions for error type.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shubhamnarlawar** [comment]
Started a discussion here - https://github.com/ballerina-platform/nballerina/discussions/183

**Comment by Kishanthan** [comment]
This currently captures only the basic error construction. But we need to comeback and think about the design when constructing error with detailed type.
