### ISSUE TITLE
Add support for global variables in nback.llvm

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#127]
This is to support #91.

@jclark for this I am thinking of adding a new function `getOrInsertGlobal(string name, Type ty) returns Value` similar to [`getOrInsertGlobal`](https://llvm.org/doxygen/classllvm_1_1Module.html#a1ec20a6f23ced1a328d4b1223fa22d96) in C api

**Comment by jclark** [comment]
@heshanpadmasiri The link you gave is the C++ API. What is the C API?

**Comment by heshanpadmasiri** [comment]
C API
Add global variable: [`LLVMAddGlobal` ](https://llvm.org/doxygen/group__LLVMCoreValueConstantGlobalVariable.html#ga4ea6995aa41031588c639c2681f2323b)
Get global variable:[`LLVMGetNamedGlobal`](https://llvm.org/doxygen/group__LLVMCoreValueConstantGlobalVariable.html#gafb8efc9027c1b70a7185c45baa8191ea)

**Comment by jclark** [comment]
I think we should follow the C API and add methods to Module corresponding to those two functions.

Be careful about types: I believe if you add a global `x` of type `i8`, then `@x` is of type `i8*`. Please test with LLVM.

**Comment by jclark** [comment]
@heshanpadmasiri You shouldn't rely on iteration order over a map. I fixed this. I also cleaned up getIntrinsicDeclaration and tweaked a few other things.  Please try to follow my style. https://github.com/ballerina-platform/nballerina/commit/2b3629c42ce6864d9c9cfc079ae11fe0d7fd352e
