### ISSUE TITLE
Generic array type support 

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#129]
**Description:**
Add support for generic array type support 

**Suggested Labels:**

Type/Feature

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Kishanthan** [comment]
Closing this as a duplicate of https://github.com/ballerina-platform/nballerina/issues/124
