### ISSUE TITLE
Add test cases in a test directory with assertions

### ISSUE THREAD

**Issue by shubhamnarlawar** [ballerina-platform/nballerina#14]
**Description:**
Write testcases with assertions to test the nballerina compiler.

**Comment by ruvi-d** [comment]
Since we added LIT testing in #47 I think we can close this.
Going forward we will require LIT tests for new feature additions and optional unit tests where applicable.

**Comment by shubhamnarlawar** [comment]
Yes, LIT does this job. +1 to close
