### ISSUE TITLE
Implement `foreach` with `..<`

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#141]
Implement a subset of `foreach` that uses `..<` e.g.

```
foreach int i in 0 ..< v.length() {
   //...
}
```
This can turn into the same as a `while`, but for incrementing the loop variable, we can use an addition without the need to check for overflow.

This is useful with #130 or #135

**Comment by jclark** [comment]
According to https://llvm.org/docs/Frontend/PerformanceTips.html#restricted-operation-semantics we should also use `nsw` on the addition.

**Comment by jclark** [comment]
We really need three different varieties of add:

1. may panic on overflow
2. guaranteed by compiler not to overflow
3. wrap on overflow

The NO_PANIC BIR instructions should be type 2 and should generate LLVM IR with `nsw`. We can have langlib functions to explicitly generate type 3.

**Comment by manuranga** [comment]
With addition of `nsw` (and other optimized instructions) it'll be useful to incorporate `opt -passes=poison-checking`. Otherwise tests can pass due to undefined behavior.

**Comment by jclark** [comment]
@manuranga Is there a clang argument to do that?

**Comment by manuranga** [comment]
> Is there a clang argument to do that?

Couldn't find a way to directly do it. Running though `opt -S` command and then passing the output to `clang` works.

**Comment by manuranga** [comment]
What would be the best way to code gen foreach:

## 1) Desuger and call codeGenStmts
```ballerina
function codeGenForeachStmt(⋯, ForeachStmt stmt) returns CodeGenError|bir:BasicBlock? {
    Stmt[] desugared = check desugerForeachStmt(cx, stmt);
    return check codeGenStmts(⋯, desugared);
}
```
### Pro:
We could formalize desguring pattern and have a set of unit tests, similar to how LLVM tests passes.

### Con:
Need new AST elements to represent non-panicking add in addition to new bir instruction
Need check how to deal with scope leak

## 2) Desuger and codeGen each
```ballerina
function codeGenRangedForeachStmt(⋯, ForeachStmt stmt) returns CodeGenError|bir:BasicBlock? {
    VarDeclStmt varDecl = {⋯, stmt.varName};
    var [curBlock, inner] = check codeGenVarDeclStmt(⋯, varDecl);
    ⋯
    WhileStmt loop = { condition, body };
    return codeGenWhileStmt(⋯, loop);
}
```
### Pro:
More control over scopes ect.

## 3) Directly code gen
### Con:
Foreach and while will have slimier code

**Comment by jclark** [comment]
Code gen directly. If there's significant common code between foreach and while, then we can factor that out in due course (you can leave that to me.)

I view BIR as the desugared form of the syntax.
