### ISSUE TITLE
Replace the use of mutable strings with string_view

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#143]
**Description:**

std::string class members are currently being used to hold object invariant properties such as names. These properties are currently being pass as values via getters. As such we are making a lot of redundant string copies and it has lead to one bug on Windows targets #95. 
Suggest that we replace the use of `std::string` with `std::string_view`, which is acts like a `const string &` 

**Suggested Labels:**

Type/Improvement 

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Kishanthan** [comment]
Not applicable anymore.
