### ISSUE TITLE
New structure BIR is used to create a map types

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#145]
**Description:**

This is to follow up on this issue that was raised in #102 

There is no "new map" instruction as per the BIR spec listed here: https://github.com/ballerina-platform/ballerina-lang/blob/bd8e12ac24a70079247d1b178de888cb0e76a96a/docs/bir-spec/src/main/resources/kaitai/bir.ksy#L988
We get new struct instruction with a LHS value of type Map for new Maps

_Question_: Is this the expected behavior?

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by manuranga** [comment]
This is not guaranteed to be correct.

New structure's RHS argument is of type `typedesc`. Currently all new structure instructions will appear immediately after new typedesc instruction. (Even though vice-versa is not guaranteed). The new typedesc instruction is the one with the real type.

So we need to get the type from the previous instruction (which is a little bit ugly). In jvm side it actually happening in two steps.

Background on why it's implemented this way : https://github.com/ballerina-platform/ballerina-lang/issues/20851

**Comment by ruvi-d** [comment]
Summary of the conclusion following our discussion : stick with the current implementation of using lhs to infer type till we need to support a use case that breaks. At which point we will use the type information from the proceeding typedesc command
