### ISSUE TITLE
Use non-integral address space for heap pointers

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#149]
In order to take advantage of LLVM's support for garbage collection, pointers in the heap should be in a non-integral address space.

This requires at a minimum:
1. declaring address space 1 as non-integral
2. specifying an address space in the pointer type
3. using address space casts before doing ptrtoint/inttoptr

**Comment by jclark** [comment]
@KavindoZoysa To start with I suggest we take an example of code generated by the compiler now that uses the heap (i.e. for boxing and unboxing `int`s), and then figure out the modifications needed to use a non-integral address space.

**Comment by KavinduZoysa** [comment]
@jclark, 
`%_7 = getelementptr i8, i8* %_5, i64 144115188075855872 ; adding the TAG_INT`

You have mentioned that doing this way helps to work with non-integral pointers. That is not clear to me. Can you help me to understand this?

**Comment by jclark** [comment]
@KavinduZoysa I believe `getelementptr` works with NI pointers. The other way to do it would be with a ptrtoint/inttoptr pair, which would not work with NI pointers.

**Comment by KavinduZoysa** [comment]
Thank you, I understood the reason. 
```
public function main() {
    any v = 1;
    int n = <int>v;
}
```

For the above example, initially, I came up with [this llvm IR](https://github.com/KavinduZoysa/llvm/blob/with-addrspace/with-addrspace.ll). 

Currently, I am working on understanding other languages' implementations, to figure out what they have done for this use case.

**Comment by jclark** [comment]
Thanks. That's very helpful.  Can you check this in the main repo in experiments/addrspace? It would be helpful to have both the original version and your hand modified .ll, so I can diff them. Also can you do something including the io:println so we can see it's working?

When you compile with -O3, do you get the same `.s` as with the original version without address spaces?

**Comment by KavinduZoysa** [comment]
> Thanks. That's very helpful. Can you check this in the main repo in experiments/addrspace? It would be helpful to have both the original version and your hand modified .ll, so I can diff them. Also, can you do something including the io:println so we can see it's working?

Sure, I will work on this.

> When you compile with -O3, do you get the same `.s` as with the original version without address spaces?

 Yes, both are same.

**Comment by jclark** [comment]
I'm surprised by this:

```
declare i8 addrspace(1)* @llvm.ptrmask.p0i8.i64 (i8 addrspace(1)*, i64)
```

I would have expected a different name for the overload i.e. `llvm.ptrmask.p1i8.i64`: I thought `p0i8` meant pointer in address space 0 to i8.

**Comment by jclark** [comment]
The declaration of _bal_alloc raises the interesting question (related to #147) on how we are going to deal with address space 1 in the runtime library. I am nervous about declaring it as addrspace(1) when we use it, but defining it as addrspace(0) and just linking together.

I think what we're doing here is the same as gollvm.

**Comment by jclark** [comment]
@KavinduZoysa If you run `opt` on the IR with address space 1, does that transform to address space 0 or is that done later? Is there some way to run the pass that does this?

**Comment by KavinduZoysa** [comment]
> @KavinduZoysa If you run `opt` on the IR with address space 1, does that transform to address space 0, or is that done later? Is there some way to run the pass that does this?

@jclark, Sorry I did not understand what you expect here. What you mean here is, finding a pass that transforms IR with address space 1 to address space 0?

**Comment by jclark** [comment]
@KavinduZoysa At some point address space 1 gets lowered to address space 0. I am trying to understand when that happens. Is it part of the optimization pipeline or does it happen later?

**Comment by KavinduZoysa** [comment]
According to address space usage of Julia language, it does not happen in the optimization phase. Because they use address spaces to preserve GC roots in the optimization phase. http://mortenpi.eu/gsoc2019-mockups/bulma/v10/julia/devdocs/llvm.html#Representation-1

I am currently trying to find out exact place of this address space lowering happens.

**Comment by jclark** [comment]
That makes sense. I remember now reading that the statepoint stuff needs target-specific support.

Is there a way to get `llc` to show the IR after lowering the non-integral address spaces?

**Comment by KavinduZoysa** [comment]
> Is there a way to get `llc` to show the IR after lowering the non-integral address spaces?

@jclark, I tried but still did not find a way to generate IR after lowering the ni address space. I generated the .bc(LLVM Byte Code) from .ll using `llvm-as` and used that .bc to generate the .ll back(`llvm-dis`). Compared those llvm IRs and still, the address spaces are there. I am investigating more to find a way.

**Comment by jclark** [comment]
Remaining thing I am not clear about is what we need in the datalayout. Can we just have this?

```
target datalayout = "ni:1"
```

If not, what's the minimum we need and will it work for all our targets (x86_64 and ARM, Linux, Mac and Windows)?

**Comment by KavinduZoysa** [comment]
Except `ni:1` part in the data layout string, the rest of the part is auto-generated and `ni:1` was added manually. Therefore we only need to specify `ni:1` to mark the pointer types of particular address space as non-integral. I was able to test (i.e. `target datalayout = "ni:1"`) this only with linux. Also according to the [datalayout document](https://llvm.org/docs/LangRef.html#langref-datalayout), there is not a special mention about adding `ni` for different platforms.

**Comment by KavinduZoysa** [comment]
@jclark, I have a concern regarding this address space example.
https://github.com/ballerina-platform/nballerina/blob/main/experiment/addrspace/with_addrspace.ll

Since we only need to push heap pointer to ni address space, we do not need to push `%v` to ni address space as shown in [here](https://github.com/ballerina-platform/nballerina/blob/main/experiment/addrspace/with_addrspace.ll#L10).
If so we can simplify the example bit more. WDYT?

**Comment by jclark** [comment]
Hmm.  My understanding is that address space is associated with the thing you're pointing to.  (It works like `const` in C.) So

- `i8 addrspace(1)` is a byte on the heap and
- `i8 addrspace(1)*` is a pointer on the stack pointing to an a byte on the heap
- `i8 addrspace(1)* addrspace(1)` is a pointer on the heap pointing to a byte on the heap

So this example needs the addrspace as it.

Try an example with creating a list. I believe you will need `i8 addrspace(1)* addrspace(1) *`.

**Comment by jclark** [comment]
Another part of this problem is how to make address spaces work with runtime functions written in C. It turns out that clang has an (undocumented) `address_space` attribute that allows you to write:

```
long foo(char __attribute__((address_space(1))) *p1) {
    char *p0 = (char *)p1;
    return (long)p0;
}
```

and the IR gets `i8 addrspace(1)*` in it and has the appropriate `addrspacecast`!

This should make it quite a bit easier to get our runtime code to work with GC.

**Comment by KavinduZoysa** [comment]
Some useful information.

This is the commit for adding non-integral pointer support in gollvm https://go.googlesource.com/gollvm/+/69a2c98b2992aff8efc4e4195b8b319a361cae97%5E%21/

- It categorizes each pointer type for address space 0 and 1
- It adds a pass to remove addrspacecast after the statepoint insertion pass

This is the Julia lang commit for remove address spaces.
https://github.com/JuliaLang/julia/commit/87e7a33816be856e3c722029a89e409815c0fc5a
- Julia remove address spaces after the optimization phases
- It defines address spaces as shown [here](https://github.com/JuliaLang/julia/blob/master/src/codegen_shared.h#L9)

**Comment by jclark** [comment]
The gollvm approach makes good sense to me.

Why does Julia need all these address spaces?

**Comment by KavinduZoysa** [comment]
> Why does Julia need all these address spaces?

AFAIU, those are Julia specific address spaces that are defined to hold GC tracked pointers, in order to preserve after optimizations.

**Comment by jclark** [comment]
That much I understand. But why does it need *multiple* such address spaces?

**Comment by KavinduZoysa** [comment]
This Julia documentation explain about the selection about their address spaces.
https://docs.julialang.org/en/v1/devdocs/llvm/#Representation

**Comment by jclark** [comment]
Closing this in favour of #199 and #200.
