### ISSUE TITLE
Figure out what code to generate for bounds checking

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#157]
In implementing #135, we will need to generate code for `E[i]` that checks that `i` is >= 0 and < length of the array. I am wondering whether we can just generate the obvious code or whether there's something special we need to do to allow LLVM to optimize.

I suspect we need an attribute on __bal_alloc that says that the return value does not refer to any existing object.

@KavinduZoysa Can you investigate what Rust does here?

**Comment by KavinduZoysa** [comment]
Sure @jclark, I will check

**Comment by KavinduZoysa** [comment]
```
fn getVec() -> Vec<i32> {
    let mut vec = Vec::new();
    vec.push(1);
    vec.push(2);
    return vec;
}

fn main()  {  
    let vec = getVec();   
    let _x = vec[3]; 
}
```
For the above example, I have generated the llvm IR and the relevant part for us is added below. So they are compare the index and length as ususal.

```
define internal i32* @getElement(i64 %index, [0 x i32]* %slice.0, i64 %length, %"std::panic::Location"* %0) {
start:
  %_5 = icmp ult i64 %index, %length
  %1 = call i1 @llvm.expect.i1(i1 %_5, i1 true)
  br i1 %1, label %bb1, label %panic

bb1:                                              
  %2 = getelementptr inbounds [0 x i32], [0 x i32]* %slice.0, i64 0, i64 %index
  ret i32* %2

panic:                                            
  call void @panic_bounds_check(i64 %self, i64 %length, %"std::panic::Location"* %0)
  unreachable
}
```
Also for an example like this, They are doing the same this, which means compare the index and length.

```
#[no_mangle]
fn bar(slice: &[i32]) {
    let _e = slice[34];
}

fn main() {  
    let slice = [101, 200, 330, 450];
    bar(&slice);
}
```

**Comment by KavinduZoysa** [comment]
Also, for an example something like this (iterate over the slice), they are checking the index for each iteration as shown above. I am still investigation more on this because the checking the lower bound and upper bound is enough for an example like this.

```
fn bar(slice: &[i32]) {
    for n in 1..200 {
        let _z = slice[n];
    }
}

fn main() {  
    let slice: [i32; 100] = [0; 100];
    bar(&slice);
}
```

**Comment by jclark** [comment]
There is an important detail here.

The obvious thing would be to check that the index (which is a signed int) is both less then the length and, greater than or equal to 0 (i.e. do *two* compares) but instead they are doing it only *one* compare, by doing an *unsigned* compare of the index against the length.
