### ISSUE TITLE
Refactor BIRReader.h/.cpp into smaller files

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#158]
**Description:**

Refactor BIRReader.h and cpp files into multiple smaller files similar to what #114 did for BIR.h.
These new files can be moved in to a sub directory inside the compiler folder.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Kishanthan** [comment]
@heshanpadmasiri
