### ISSUE TITLE
Add option to set GC strategy

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#164]
This would be an additional command-line option on the driver that takes the name of the strategy e.g. `--gc "example"`

If this is used then, the compiler will call `F.setGC(strategy)` on each function definition, which will result in  the LL IR including `gc "example"`, e.g.

```
define void @foo() gc "example" { ... }
```

as described here: https://llvm.org/docs/GarbageCollection.html#quick-start

**Comment by jclark** [comment]
@heshanpadmasiri Is there a way to do this through the JNI/LLVM C interface?

**Comment by heshanpadmasiri** [comment]
> @heshanpadmasiri Is there a way to do this through the JNI/LLVM C interface?

Yes it has a function `public static native void LLVMSetGC(LLVMValueRef Fn, String Name)` that does this.

**Comment by jclark** [comment]
@heshanpadmasiri Great! At some point, can you add this to nback.llvm? (No urgency.)
