### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#169]
**Description:**

Revisit existing LIT tests and improve coverage; including negative test cases where applicable 

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

Ruvi-d

**Comment by ruvi-d** [comment]
Blocked on #188

**Comment by manuranga** [comment]
We need to replicate the same erors as jballerina side https://docs.google.com/document/d/1qjQTIMjpedZTGTNVXRg3WggmmjcAS23SkY4yxn_teDQ/edit
