### ISSUE TITLE
jBallerina compiler frontend call into nBallerina

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#17]
**Description:**
Have jBallerina compiler call into compiled version of nBallerina with a BIR object.

**Comment by manuranga** [comment]
At the beginning I imagine this working in two steps. Later we can have it as a single cmd if needed.
```cli
/manu/nballerina> bal build
/manu/nballerina> bal build test.bal --with-backend target/bin/nballerina.jar
```

**Comment by ushirask** [comment]
The current implementation passes the test cases except for bellow conditions due to JBallerina bugs.
1.  Using `toHexString` directly with an int (ex : - `0.toHexString()`) [Can be tested by wrapping the integer in parenthesis]
2. Using  5 digit Unicode characters (ex:- `u{1F600}`)
 @manuranga @jclark

**Comment by manuranga** [comment]
Above case 1 is not a bug per se, It's just that jBallerina is bases on 2021R1 and this (ballerina-platform/ballerina-spec#905) was proposed later. So I suggest duplicating hex string tests and add wrapping (eg - `(0).toHexString()`)  until jBallerina caches up.

**Comment by jclark** [comment]
It's great that it's all working now.  For 1, you can just put a space after the `0`.

Where's the code?

I wonder what we can compile that goes beyond what our front end does. For example:

1. `&&` or `||` operators
2. compound assignment e.g. `+=`, `-=`

**Comment by ushirask** [comment]
For 1, binary expression can be extended to handle those operators as well in the frontend.  Will look into 2.  
The code is available at https://github.com/ballerina-platform/ballerina-lang/pull/31350, might have to create a new PR from beta2 since this PR was created from beta1 and the beta2 changes were merged later.

**Comment by manuranga** [comment]
You could try git rebase, but given the size it thinks that would be difficult especially if you don't use git tricks like `git rerere`. Give it a try and see, if it doesn't work, I would go for a low tech solution, do a git merge and use regular `diff` to create a patch file and reapply it in a clean branch.

**Comment by jclark** [comment]
My question is if you try a .bal file that uses our subset but also `&&` and `||` does it work with the jBallerina front end used with the nballerina backend?

(Implementing `&&` and `||` is quite difficult, different from all the other binary operators, because (a) the second operand is not always evaluated and (b) type narrowing.)

**Comment by ushirask** [comment]
> My question is if you try a .bal file that uses our subset but also `&&` and `||` does it work with the jBallerina front end used with the nballerina backend?

It will be parsed as a binary expression with operator `&&` or `||` in  jBallerina front end which we can use to pass an instruction to nballerina backend

**Comment by jclark** [comment]
There's no `&&` or `||` BIR instruction (at least in nBallerina) and no need for one. These operators would turn into the existing BIR instructions (as would `+=` or `-=`).   How does jBallerina implement `&&` and `||`? I suspect there's a fundamental issue here.

Does the jBallerina/nBallerina combo report errors for all the E test cases? Are they all reported by jBallerina or does the BIR verifier catch them?

Can we get a clean diff that just shows what you've changed? What's in https://github.com/ballerina-platform/ballerina-lang/pull/31350 does not allow for convenient review.

**Comment by ushirask** [comment]
I'll clean the PR and give an update

**Comment by ushirask** [comment]
https://github.com/ballerina-platform/ballerina-lang/pull/32060/files

**Comment by jclark** [comment]
That diff is much more comprehensible, thanks.

It looks to me like the code is duplicating a lot of the logic of codeGen.bal.  Maybe we need to rethink the approach. @manuranga Please have a look and see what you think.  We could convert into our `ast.bal`, but then what are really gaining from using jBallerina?

**Comment by manuranga** [comment]
- Cost of converting to AST will be, having to grow codeGen.bal not just BIR, to reap benefits from jBallerina. But I think this will be better than replicating codeGen.bal on the Java side.
I think we'll primarily get two benefits for jBallerina.
  a) multi-module support
  b) desugarings -
    - syntactical  (string template, `+=` ect)
    - conditionals (`check` `&&` `||` `?:` `?.`)
    - default values in function calls
    - query
    - closure (maybe this is not useful in native world)
Looks like the cost to benefit ratio is not that great.

- If we want to convert jBallerina backend to work with new-BIR or jBallerina frontend produce new-BIR, as part of the re-prioritizing effort, then we can justify the effort.

**Comment by manuranga** [comment]
No longer planing to do the, instead jBallerina will migrate to SymTypes, allowing potential future integration.
