### ISSUE TITLE
Make outputs from `jni.llvm` and `print.llvm` comparable

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#174]
C-API perform constant folding on generated code while our API does not for example:
```
%_73 = icmp sge i64 9223372036854775806, 9223372036854775806
store i1 %_73, i1* %_0, align 1
```
in our API will be 
```
 store i1 true, i1* %1, align 1
```
in C API. This will prevent validation by comparing generated codes.

**Comment by heshanpadmasiri** [comment]
This also need to address more complex situations such as 
```
%_11 = zext i1 true to i64
%_12 = or i64 %_11, 72057594037927936
%_13 = getelementptr i8, i8* null, i64 %_12
call void @_Bio__println(i8* %_13)
```
to 
```
call void @_Bio__println(i8* getelementptr (i8, i8* null, i64 72057594037927937))
```

**Comment by jclark** [comment]
Diff cases here
[print-jni-diff.txt](https://github.com/ballerina-platform/nballerina/files/6762160/print-jni-diff.txt)

**Comment by jclark** [comment]
I wonder if there is a way to make the C API not do this constant folding.

Edited: I found this suggestion online:

> In LLVM 11 you can use `IRBuilder<llvm::NoFolder>` instead of `IRBuilder<>`. 

The issue then is to get to this using the C API.

**Comment by jclark** [comment]
Things we've tried that don't work:

- use` ll-as | ll-dis` to canonicalize
- use `clang -c -emit-llvm` to try to canonicalize

**Comment by jclark** [comment]
Another possibility is to compile both .ll files to .s (with `clang -O2 -S`) and see if we get identical results.

**Comment by heshanpadmasiri** [comment]
Running `opt -instcombine` on both will make them comparable
