### ISSUE TITLE
Implement non-panicking integer addition

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#180]
Implement non-panicking integer addition

Originally part of  #141. See [comment](https://github.com/ballerina-platform/nballerina/issues/141#issuecomment-873401106)

**Comment by jclark** [comment]
I am not completely clear about whether for non-panicking add we want `nsw` or both `nuw` and `nsw`. Does it make a difference?

**Comment by manuranga** [comment]
Let's consider `i4` for simplicity. So the valid numbers are 0 to 7 (unsigned) or -4 to 3 (signed).
LLVM doesn't know if they are signed or not, but that's OK, because in two's complement you don't need to know that to do operations. But what overflow means changes depending on if it's signed or not.

Eg: 
Signed
 -1 + 1 = 0b111 + 0b001 = 0b000 = 0  - shouldn't be considered overflow,  can claim `nsw`
unsigned (same bits)
7 + 1 =  0b111 + 0b001 = 0b000 = 0 - overflowed, can't claim `nuw`
Signed
 -1 + -4 = 0b111 + 0b100 = 0b011 = 3  - overflowed, can't claim `nsw`
unsigned (same bits)
7 + 4 =  0b111 + 0b100 = 0b011 = 3 - overflowed, can't claim `nuw`

Conclusion:
In Ballerina foreach loops, we can always claim `nsw`. But we can only claim both `nsw nuw` if we statically know the lower bound to be non-negative. This is what I observed Clang doing as well.

**Comment by jclark** [comment]
Thanks for figuring this out.  Since the C API does not appear to support nsw+nuw, I suggest

- we make the non-panicking BIR instructions compile into LLVM instructions with just nsw for now
- we create an issue to add `nuw` for loops with non-negative lower bounds in the (distant) future

**Comment by manuranga** [comment]
I tested the merge sort case with these options. I don't see any difference between`add` vs `add nsw`. Perhaps these only matter in C where automatic integer promotions need to happen.

Even more surprisingly, even though it produces inconsequentially different assembly, there is no improvement over the panicking version. Looks like llvm good at getting rid of `@llvm.sadd.with.overflow.i64`s.

**Comment by jclark** [comment]
That is surprising.
