### ISSUE TITLE
Report unreported compiler bugs still present in slbeta2

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#191]
There are some unreported bugs (marked with JBUG comments).

Find out which of these still apply in slbeta2 and report as necessary, adding bug numbers.

**Comment by jclark** [comment]
@gimantha There seem to be quite a few bugs relating to the new implementation of `string:Char`.

**Comment by manuranga** [comment]
I reported some of them (31668 31673 31660), @gimantha please use those numbers when appropriate.

**Comment by gimantha** [comment]
@jclark @manuranga We will try to get the fixes in this sprint. These are planned to be fixed in this sprint (31668 31673 31660)

**Comment by jclark** [comment]
@gimantha I've found a bunch more bugs. Could you have a look please?

**Comment by gimantha** [comment]
> @gimantha I've found a bunch more bugs. Could you have a look please?

Sure. I will have a look.

**Comment by jclark** [comment]
Better to wait now for slbeta3.
