### ISSUE TITLE
Incorrect output from float value

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/nballerina#192]
**Description:**
$subject. 

**Steps to reproduce:**
```
public function printf32(float val) = external;


public function main() {
    printf32(2.2); // prints wrong value like 4612136000000000000
}
```

**Comment by Kishanthan** [comment]
Related test cases are also disabled. Let prioritize this.

**Comment by ramakotareddy** [comment]
We need to update casting/multipleStringBuilderEntries.bal test with float print after fix float print issue.

**Comment by shubhamnarlawar** [comment]
> We need to update casting/multipleStringBuilderEntries.bal test with float print after fix float print issue.

The testcase prints a string value. Do we want to print float value there?

Now, float printing support is enabled in PR #196
