### ISSUE TITLE
Boolean values appear to be always evaluated as true

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#199]
**Description:**

The following test fails
```
// RUN: "%testRunScript" %s %nballerinacc "%java_path" | filecheck %s

public function print_str(string val) = external;

public function printu32(int val) = external;

public function main() {
    boolean f = false;
    print_str("RESULT=");
    if (f) {
        printu32(0);
    }
    else {
        printu32(42);
    }
}
// CHECK: RESULT=42
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

Priority/Blocker

**Suggested Assignees (optional):**

**Comment by shubhamnarlawar** [comment]
In BIRReader, while fetching `BooleanCp` - 

https://github.com/ballerina-platform/nballerina/blob/a969374bf4ee1f76fc4a33de052c35646010b2e2/compiler/BIRReader.cpp#L152

**Comment by ruvi-d** [comment]
Found the issue at https://github.com/ballerina-platform/nballerina/blob/a969374bf4ee1f76fc4a33de052c35646010b2e2/compiler/BIRReader.cpp#L304

The "valueCpIndex" is not an index. It's the actual value of the bool constant
