### ISSUE TITLE
Make address space 1 non-integral

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#200]
This builds on #199 to make address space 1 non-integral.

This requires:

- changing the data layout to specify that address space 1 is non-integral
- ensuring that we generated LL IR for address space 1 in a way that works when address space 1 is non-integral

**Comment by jclark** [comment]
We can make the address space 1 non-integral by adding to the sed script in `runtime/Makefile` for creating `.ll` from `.bc`.

**Comment by KavinduZoysa** [comment]
@jclark, I have changed the sed command as follows, and I generated the `.bc` with ni addrspace 1 (confirmed by generating .ll using llvm-dis command) 

`sed -e '/define .*@_B[a-zA-Z]/s/^define /define linkonce_odr /' -e '/target datalayout/ s/.$$/-ni:1"/' $< | $(LLVM_AS) >$@`

**Comment by jclark** [comment]
OK. I suggest `-e '/target datalayout/ s/"$$/-ni:1"/'` (with a `"` instead of a `.` for slightly better robustness.

**Comment by jclark** [comment]
I tested it and it seems to work OK with the code I am generating now.

That was easier than I expected!
