### ISSUE TITLE
Support LTO between Codegen C and Rust runtime lib

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#209]
**Description:**

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ruvi-d** [comment]
References:
https://blog.llvm.org/2019/09/closing-gap-cross-language-lto-between.html
https://blog.haoxp.xyz/posts/cross-lang-lto-guide/

**Comment by ruvi-d** [comment]
ThinLTO References:
https://clang.llvm.org/docs/ThinLTO.html
ThinLTO Whole Program Optimization - Meeting C++ 2020 Center Keynote: https://youtu.be/VAMvr1rXmg8

**Comment by ruvi-d** [comment]
Linux and Windows support should be possible provided that we use clang and ldd instead of the platform's default C++ compiler and linker. ref: https://clang.llvm.org/docs/ThinLTO.html#clang-bootstrap

**Comment by ayonam** [comment]
> Linux and Windows support should be possible provided that we use clang and lld instead of the platform's default C++ compiler and linker. ref: https://clang.llvm.org/docs/ThinLTO.html#clang-bootstrap

Yes, you necessarily need to use clang/lld in order to get LTO to work on Windoze.  The IR from LLVM will not be compatible with the one generated by the MSVC compiler to do an LTO.  (That is if the LTO on Windoze is stable __and__ anything worth the salt.)

**Comment by ayonam** [comment]
@ruvi-d I will post the exact sequence of things that you need to do for this task.  Just remind me once mid-week.

**Comment by ruvi-d** [comment]
Sure. Let me know what you have in mind. I was thinking to do the following:
1. Setup a demo C++ app with Rust static lib (with trivial functions)
    * Enable ThinLTO
    * Disassemble binaries to check whether functions are getting in-lined  
2. Enable ThinLTO for nBallerina's ubuntu build (change compiler to clang, etc)
    * Disassemble binaries to check whether functions are getting in-lined
    * Benchmark nBallerina execution speed with and without ThinLTO enabled
    * Benchmark nBallerina build time with and without ThinLTO enabled

Not in scope : Windows build target

**Comment by ruvi-d** [comment]
Need to also check whether hoisting is happening as expected

**Comment by ruvi-d** [comment]
Was able to enable ThinLTO for ballerina apps in this branch: https://github.com/ruvi-d/nballerina/tree/ruvi/task/enable-cross-lto

I managed to notice about a x2.5 improvement in execution time for this particular test when run 10,000 times: https://github.com/ruvi-d/nballerina/blob/ruvi/task/enable-cross-lto/test/functions/lto_test.bal

These are the compiled binaries with and without LTO enabled: https://drive.google.com/drive/folders/1GT9GlWtCGBVQ79FLFOsWecD7uGQiQ3CI?usp=sharing
(PS: they are statically linked with the runtime)

@ayonam : please disassemble and verify

**Comment by ruvi-d** [comment]
![image](https://user-images.githubusercontent.com/6542630/113591700-dd0bfd80-9651-11eb-9533-34b21e592fc2.png)

Runtime (LTO disabled) vs Runtime with LTO vs Implementing same logic in LLVM
