### ISSUE TITLE
Add more float tests

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#215]
**Description:**

Enable currently disable float type related tests and add move tests that covers:
* Negative values
* Comparison operators
* Casting to int

Depends on #157, #192

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shubhamnarlawar** [comment]
Testcases to be added - 

- [ ] Float arithmetic (addition, subtraction,  multiplication, division, unary ops, etc)
- [ ] Float comparison ( greater or equal, etc)
- [ ] Casting from float to int

**Comment by shubhamnarlawar** [comment]
Float arithmetic and Float comparision tests are present in #271.

**Comment by jclark** [comment]
**Edited: ignore this**

Actually, I think a better interface is for it to take a Ballerina string:

```
function constString(string str) returns Value
```

and then convert to bytes using string:toBytes only if the string has a code point >= 128.
