### ISSUE TITLE
LLVM interface needs support for `signext` and `zeroext` attributes on arguments/returns values

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#227]
We need this to get compatibility with clang for boolean arguments.

This requires extending attributes to support applying to argument/return value rather than to function.

**Comment by heshanpadmasiri** [comment]
@jclark  for this I can think of two options

1. extend the current `addEnumAttribute` function to be `public function addEnumAttribute(EnumAttribute attribute, *AttributeIndex index)` and introduce new record type (similar to `GlobalProperties`) which will have attributes for where it must be set (return value, function or argument) and optional index value (in the case of argument)
2. Add 3 (including the current `addEnumAttribute`) functions one for function, return value and argument (this one will take a second argument for index and all others will be same as current `addEnumAttribute`)

**Comment by jclark** [comment]
The validity of the AttributeIndex depends on the EnumAttribute and vice-versa, so I think it's better to group the Attribute with the AttributeIndex into a tuple so we can type-check this:

```
type EnumAttribute FunctionEnumAttribute | (readonly & [int, ParamEnumAttribute]) | (readonly & ["return", ReturnEnumAttribute]);
```

so I would say:

```
f.addEnumAttribute(["return", "noalias"]);
```

The int in the ParamEnumAttribute tuple should be 0-based.
