### ISSUE TITLE
LLVM module support for const expressions

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#234]
In the initializer of a global we need to be able to have at least:

- getElementPtr
- bitCast
- addressSpaceCast

**Comment by heshanpadmasiri** [comment]
@jclark for this I am thinking of adding fallowing functions to `Context` (assuming we may need to share constants among modules)

- `function getElementPtr(ConstValue ptr, ConstValue[] indices, "inbounds"? inbounds=()) returns ConstValue` similar to [`LLVMConstGEP`](https://llvm.org/doxygen/group__LLVMCCoreValueConstantExpressions.html#ga297cf7ec9e5b39e6ae47a834d1a84bfb)
- `function bitCast(ConstValue val, PointerType destTy) returns ConstValue` similar to [`LLVMConstBitCast`](https://llvm.org/doxygen/group__LLVMCCoreValueConstantExpressions.html#gacc93f3057e4c29da885d8a83bbb11406)
- `function addrSpaceCast(ConstValue val, PointerType destTy) returns ConstValue` similar to [`LLVMConstAddrSpaceCast`](https://llvm.org/doxygen/group__LLVMCCoreValueConstantExpressions.html#ga7e2b37a49214564b69cba3c115136f06)

Currently we have only one type for constants `ConstValue` perhaps we can split it in to two as `ConstValue` and `ConstPointerValue` to make these more type safe as well.

**Comment by jclark** [comment]
Looks good but I think the names should start with `const` e.g. `constBitCast`.

I don't think PointerValue is working very well - it requires a lot of casting - so let's not do that for ConstValue.

**Comment by heshanpadmasiri** [comment]
@jclark if we are planning to use `addrspacecast` const expressions we may need to update to llvm-12. At least in llvm-11 for ubuntu there seems to be a bug throwing in `llc`
```
LLVM ERROR: Unsupported expression in static initializer: addrspacecast (i32* @g4 to i32 addrspace(1)*)
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
```
(`LLVMVerifyModule` doesn't detect any issues so I assume this is a bug in the compiler)
The issue does not exists with llvm-12 for ubuntu.

Sample code causing issue:
```
@g4 = external global i32
@g5 = addrspace(1) global i32 addrspace(1)* addrspacecast (i32* @g4 to i32 addrspace(1)*)
```

**Comment by jclark** [comment]
We should switch to LLVM 12 then.

(I remember one of the Go LLVM projects having a pass to fix this.)

**Comment by jclark** [comment]
I gave the wrong answer https://github.com/ballerina-platform/nballerina/issues/234#issuecomment-883055527

Given that we already have PointerValue, we have to have ConstPointerValue or the typing doesn't work out at all.

**Comment by jclark** [comment]
I am now generating code for strings using this https://github.com/ballerina-platform/nballerina/commit/44fb94e357037981fc79a1176521a00000bf49d2

The code compiles fine with LLVM 11 on Ubuntu.

@heshanpadmasiri Please see whether this works with LLVM 11 through JNI
