### ISSUE TITLE
LLVM module support for named structs

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#237]
LLVM allows you to give names for structs.  It would be useful to be able to take advantage of that.

**Comment by heshanpadmasiri** [comment]
@jclark for this I am thinking of adding a new function to `Context` as `structCreateNamed(string name, Type[] elementTypes) returns StructType` combining the [`LLVMStructCreateNamed`](https://llvm.org/doxygen/group__LLVMCCoreTypeStruct.html#gaf3bed4d4b79664d613acf8b9dbfbccb7) and [`LLVMStructSetBody`](https://llvm.org/doxygen/group__LLVMCCoreTypeStruct.html#ga0969f946bdec1ddb160530e12097da3e) to a single function.

**Comment by jclark** [comment]
Looks good. Will this emit the definition of the type if it is not used?

**Comment by heshanpadmasiri** [comment]
I think we can make it not so by

1. Add a boolean `isReferred` flag to `StructType`
2. Have that flag updated in `typeToString` function (When you use some value of this type in builder it inevitably call this function)
3. When we make the output we only do so if that flag is up

**Comment by jclark** [comment]
I just want to know how the LLVM C API behaves if you define a type but do not refer to it.

It's fine for our API do the same.

**Comment by jclark** [comment]
The way we've done this isn't satisfactory because it doesn't support recursive types. For example, the C struct

```
struct X {
   struct X *p
   int n;
};
```

would turn into 

```
%struct.X = type { %struct.X*, i32 }
```

So we shouldn't combine [`LLVMStructCreateNamed`](https://llvm.org/doxygen/group__LLVMCCoreTypeStruct.html#gaf3bed4d4b79664d613acf8b9dbfbccb7) and [`LLVMStructSetBody`](https://llvm.org/doxygen/group__LLVMCCoreTypeStruct.html#ga0969f946bdec1ddb160530e12097da3e).

We also want to support something like:

```
struct V {
   int (*foo)(struct V *this);
};
```

(clang doesn't use a recursive struct for this: not sure why.)

**Comment by jclark** [comment]
@heshanpadmasiri Please prioritize this. It is blocking my work.

**Comment by jclark** [comment]
Keeping open to fix a couple of minor things: https://github.com/ballerina-platform/nballerina/pull/546#pullrequestreview-775835550
