### ISSUE TITLE
Implement nback.llvm support for struct types

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#24]
Add support for:

- Define structure types (minimally `{i64, i1}`) and use them as a type of a value / return type of function 
- Use `extractvalue` so we can get values out of them by index

**Comment by jclark** [comment]
@heshanpadmasiri Please 
1. Propose API design in the issue before implementing
2. Talk to me about the right order to implement things in, so I can sync things up across the pipeline

**Comment by jclark** [comment]
Can you write in this issue the declarations for the functions you are proposing to add to the public API?

For point (i), we need something like https://llvm.org/doxygen/group__LLVMCCoreTypeStruct.html#ga76526e252ad17fb9744f473be8df36ba

This can be a module-level function (not on Module):

```
function structType(IntType[] memberTypes) returns StructType;
```

Ballerina terminology is to use `member` not `element` when talking about members of structures.

**Comment by jclark** [comment]
Sounds good.
