### ISSUE TITLE
Implement nback.llvm support for conditionals

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#25]
Add support for:

- `br` (we need both conditional and unconditional variants) [`LLVMBuildBr`, `LLVMBuildCondBr`]
- `icmp` (strictly speaking we may not need all the possible predicates but I think we can support all similar to how we do `binaryInt`) [`LLVMBuildICmp`]
- `unreachable` (I think this is optional but better if we can add this after calling abort and should be trivial to implement)[`LLVMBuildUnreachable`]

**Comment by jclark** [comment]
I don’t think we should have unreachable yet

https://llvm.org/docs/LangRef.html#unreachable-instruction

> The ‘unreachable’ instruction has no defined semantics.

**Comment by jclark** [comment]
@manuranga I was wrong about unreachable: LLVM actually requires it: otherwise you have a basic block that does not end with a terminator.
