### ISSUE TITLE
Update to LLVM 12

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#250]
Given https://github.com/ballerina-platform/nballerina/issues/234#issuecomment-883795856 we should update to LLVM 12

I see LLVM has its own apt repo:

https://apt.llvm.org/

Looks like for Ubuntu 20.04, we can use:

```
deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main
```

**Comment by jclark** [comment]
@heshanpadmasiri Do the bytedeco LLVM JNI packages support LLVM 12?

**Comment by heshanpadmasiri** [comment]
Version in maven central (stable version) is still LLVM 11. But their repository and version in Nexus has been updated to LLVM 12  recently so probably maven central may be in the process of getting updated as well. 
As long as we are not using the LLVM JNI to compile the code affected by it we are not affected by  [#234 (comment](https://github.com/ballerina-platform/nballerina/issues/234#issuecomment-883795856) in LLVM JNI. Code generation works without a issue.

**Comment by jclark** [comment]
OK, then we can hold off on #240 until maven central gets updated to LLVM 12.

**Comment by jclark** [comment]
The way I am using addrSpaceCast right now doesn't seem to trigger this problem, e.g.

```
call void @_bal_mapping_init_member(i8 addrspace(1)* %27, i8 addrspace(1)* getelementptr(i8, i8 addrspace(1)* addrspacecast(i8* bitcast({i8, [7 x i8]}* @.str2 to i8*) to i8 addrspace(1)*), i64 720575940379279360), i8 addrspace(1)* %28)
```

I think we'll only hit this when we have list or mapping constants.

Anyway, we don't need to worry about this for a bit.

**Comment by jclark** [comment]
I will update the Makefiles.

@manuranga Please update GitHub actions
@heshanpadmasiri Please update JNI

**Comment by jclark** [comment]
I think we're best off using the LLVM apt repo on Ubuntu 20.04: the version in universe is 12.0.0 rather than 12.0.1.
