### ISSUE TITLE
Migrate int-to-any and any-to-int to BalValue representation

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#252]
**Description:**
Remove fat-pointer (`smtPtr`) usage when compiling int to any casting

**Describe your problem(s)**
Below code should work without any usage of fat pointer and external type checker.

```ballerina
function any_to_int(any a) returns int{
     int i = <int> a;
     return i;
}

function int_to_any(int i) returns any {
     any a = i;
     return a;
}

function test(int i) {
   if (any_to_int(int_to_any(i)) != i) {
        panic error(i.toString());
   }
}

public function main() {
     test(1);
     test(-1);
     test(12147483647);
}
```

**Describe your solution(s)**

Equivalent C++ code to the generated code should look as follows

```C++

unsigned long int_to_any(long i) {
  //  if in immediate mode range :
  //    left shift, or with 1, return
  // else :
  //    allocate on heap and return pointer
}

long any_to_int(unsigned long i) {
   // if ends with 1 :
   //      right shift by 1, return
   // else :
   //     if ends with 00 :
   //          read from heap, return
   //     else:
   //          throw type cast error
}

```
Will add more implementation details instead above pseudo-code as we flesh out this design.

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ayonam** [comment]
Just one small correction.  The left shift and right shift in the pseudo code above needs to interchanged.

**Comment by ayonam** [comment]
Also, the immediate mode range in the pseudo code above can be set to a 61-bit signed integer.  So the range will be   -(2^60)  to  (2^60) - 1.

This is because we expect 64-bit pointers to have their lowest three bits to be zeros.  So we want to use those three bits to denote various things in our scheme of type representation.  Hence, we can represent integers only within the 61-bits that are left.  

In fact, I'd suggest that we do the left/right shifting by 3 bits and use the result as needed.  So replace all the shifts in the pseudo code above with shift by 3 bits.

**Comment by manuranga** [comment]
> Just one small correction. The left shift and right shift in the pseudo code above needs to interchanged.
Ahh yes.

>we can represent integers only within the 61-bits that are left.
I am not seeing the advantage of keeping integers looking the same as the pointers, in fact this can negatively impact by fooling the garbage collector.

**Comment by manuranga** [comment]
I have tested following equivalent C++ code. 
Generated LLVM/x86 can be views form : https://godbolt.org/z/nq6nGMGes
```C++

size_t HEADER_SIZE_IN_BYTES = 1;
typedef uint64_t BalValue;
typedef int64_t BalInt;
uint64_t TAG_MASK = 0b11;

BalValue int_to_any(BalInt i) {
    if (0x3FFFFFFFFFFFFFFF >= i && i >= -0x4000000000000000) {
        return (i << 1) | 1;
    } else {
        auto *boxHeader = static_cast<uint8_t *>(malloc(sizeof(BalValue) + HEADER_SIZE_IN_BYTES));
        // casted to unit8 so we can do pointer arithmetic in byte sizes, necessary for HEADER_SIZE_IN_BYTES addition
        BalInt *boxBody = reinterpret_cast<BalInt *>(boxHeader + HEADER_SIZE_IN_BYTES);
        *boxBody = i;
        return reinterpret_cast<BalValue>(boxHeader);
    }
}

BalInt any_to_int(BalValue i) {
    if (i & 1) {
       return (static_cast<BalInt>(i) >> 1);
    } else {
        if ((i & TAG_MASK) == 0) {
            BalInt *p = reinterpret_cast<BalInt *>(i + HEADER_SIZE_IN_BYTES);
            return *p;
        } else {
            abort(); // type cast panic
        }
    }
}
```
Some samples:
Int | Binary | BalValue 
---|------- | ----------
`0`|`0000000000000000000000000000000000000000000000000000000000000000`|`0000000000000000000000000000000000000000000000000000000000000001`
`1`|`0000000000000000000000000000000000000000000000000000000000000001`|`0000000000000000000000000000000000000000000000000000000000000011`
`2`|`0000000000000000000000000000000000000000000000000000000000000010`|`0000000000000000000000000000000000000000000000000000000000000101`
`3`|`0000000000000000000000000000000000000000000000000000000000000011`|`0000000000000000000000000000000000000000000000000000000000000111`
`100`|`0000000000000000000000000000000000000000000000000000000001100100`|`0000000000000000000000000000000000000000000000000000000011001001`
`1024`|`0000000000000000000000000000000000000000000000000000010000000000`|`0000000000000000000000000000000000000000000000000000100000000001`
`-1`|`1111111111111111111111111111111111111111111111111111111111111111`|`1111111111111111111111111111111111111111111111111111111111111111`
`-2`|`1111111111111111111111111111111111111111111111111111111111111110`|`1111111111111111111111111111111111111111111111111111111111111101`
`-3`|`1111111111111111111111111111111111111111111111111111111111111101`|`1111111111111111111111111111111111111111111111111111111111111011`
`-4611686018427387906`|`1011111111111111111111111111111111111111111111111111111111111110`|`0000000000000000011111111100000100111001010000000101100011100000` (a pointer)
`-4611686018427387905`|`1011111111111111111111111111111111111111111111111111111111111111`|`0000000000000000011111111100000100111001010000000101100011110000` (a pointer)
`-4611686018427387904`|`1100000000000000000000000000000000000000000000000000000000000000`|`1000000000000000000000000000000000000000000000000000000000000001`
`4611686018427387902`|`0011111111111111111111111111111111111111111111111111111111111110`|`0111111111111111111111111111111111111111111111111111111111111101`
`4611686018427387903`|`0011111111111111111111111111111111111111111111111111111111111111`|`0111111111111111111111111111111111111111111111111111111111111111`
`4611686018427387904`|`0100000000000000000000000000000000000000000000000000000000000000`|`0000000000000000011111111100000100111001010000000101100100000000` (a pointer)

**Comment by jclark** [comment]
Even though we have 3 tag bits, we can (and should) still support 63-bit ints:

- 000 means a pointer
- XX1 means an int, and XX are the two lo bits of the int

This is the normal way of doing things.

This still leaves us three tags:

- 010
- 100
- 110

which is more than enough:

- we can (if need be) use the same tag for nil, true and false, since the high 61 bits can distinguish between them
- heap objects have their own tag byte

**Comment by manuranga** [comment]
please send the pr to add `BalValue` type first.

**Comment by manuranga** [comment]
To clarify above comment:
What i meant was to add a llvm type, with the goal of catching potential type errors

```llvm
%BalValue = type i64
define %BalValue @int_to_any(i64) {
    …
    ret %BalValue %0  ; I expected this to fail, but it dosn't
}
```
After a little bit of testing I realized this doesn't add much value since llvm is a structurally typed language, it will ignore the name `BalValue`.


But let's add anyway, for us to keep track.

**Comment by ayonam** [comment]
Actually, we can add a derived type in the LLVM type system which will create a distinct type.  The operational details are given here:

https://llvm.org/docs/ExtendingLLVM.html#adding-a-derived-type

But this would mean that we have to ship our version of LLVM with the nballerina compiler.  The question that we need to answer here is whether we are game for that?  Our current approach is to make the user install the standard LLVM and then install nballerina on top of it.

**Comment by ruvi-d** [comment]
> But this would mean that we have to ship our version of LLVM with the nballerina compiler. The question that we need to answer here is whether we are game for that? Our current approach is to make the user install the standard LLVM and then install nballerina on top of it.

Correction here. We are statically linking LLVM libs with the nBallerina compiler. As such, only nBallerina developers need to install LLVM. As it is right now, users will not have to install any dependencies on any of the platforms we plan to support.

**Comment by ayonam** [comment]
Okay.  Then this should be fine.  But it would mean that we now have to build the llvm sources along with our builds.  Alternately, we can make this implementation and create installable binaries with this change.  We all can install those binaries and continue with the development.  We only go back to building the sources when we need to debug something in this implementation.

**Comment by manuranga** [comment]
@jclark has suggested using custom address spaces to represent pointers, we'll need to do this inorder to add precise GC support.

So it's better to represent `BalValue` as a pointer
```llvm
%BalValue = type i8*
```
So in the future we can change it to
```llvm
%BalValue = type i8 addrspace(1)*
```

Here `i8*` is used because llvm does not have `void*`

**Comment by ayonam** [comment]
@jclark 
If we are going to use custom address spaces, then we would need to modify the linker in order to handle linkages across address spaces, don't we?  Or is it that these address spaces will be only heap regions and hence we would not need to have any static linking?

**Comment by jclark** [comment]
@ayonam I would not expect to have to modify the linker. LLVM "address spaces" aren't what I would call address spaces: rather they are a way to tell LLVM that a pointer type is special in some way and that LLVM should not make the assumptions that it usually does.

**Comment by ayonam** [comment]
@jclark Ah! You meant address spaces in the LLVM context.  I didn't know that they don't necessarily map to a physical address space as we know in processor terminology.  I read it up just now that they are an artifact only within the LLVM context for the purposes of alias analysis and other such memory access optimizations.  In fact, they can be used to represent the physical address spaces also, but the existence of such separate physical address spaces is not a necessity.  Thanks.

**Comment by ramakotareddy** [comment]
Code with pointer(i8*) balValue:
-----------------------------------------

#include <iostream>

size_t HEADER_SIZE_IN_BYTES = 1;
//typedef uint64_t BalValue;
typedef int64_t BalInt;
uint64_t TAG_MASK = 0b11;

uint8_t * int_to_any(BalInt i) {
    if (0x3FFFFFFFFFFFFFFF >= i && i >= -0x4000000000000000) [[likely]] {
        return reinterpret_cast<uint8_t *>((i << 1) | 1);
    } else {
        auto *boxHeader = static_cast<uint8_t *>(malloc(sizeof(uint8_t *) + HEADER_SIZE_IN_BYTES));
        // casted to unit8 so we can do pointer arithmetic in byte sizes, necessary for HEADER_SIZE_IN_BYTES addition
        BalInt *boxBody = reinterpret_cast<BalInt *>(boxHeader + HEADER_SIZE_IN_BYTES);
        *boxBody = i;
        return reinterpret_cast<uint8_t *>(boxHeader);
    }
}

BalInt any_to_int(uint8_t * i) {
    if (reinterpret_cast<BalInt>(i) & 1) [[likely]] {
       return (reinterpret_cast<BalInt>(i) >> 1);
    } else {
        if ((reinterpret_cast<BalInt>(i) & TAG_MASK) == 0) {
            BalInt *p = reinterpret_cast<BalInt *>(i + HEADER_SIZE_IN_BYTES);
            return *p;
        } else {
            abort(); // type cast panic
        }
    }
}

@manuranga , can you please go through above code suggest if have any mistakes.

**Comment by ruvi-d** [comment]
@ramakotareddy can you format code snippets and put them inside a code block so that syntax highlighting works?

**Comment by ruvi-d** [comment]
Missing the reinterpret_cast type in the `any_to_int` function
```C
BalInt any_to_int(uint8_t * i) {
  if (reinterpret_cast(i) & 1) [[likely]] {
    return (reinterpret_cast(i) >> 1);
  } else {
    if ((reinterpret_cast(i) & TAG_MASK) == 0) {
...
```

**Comment by ramakotareddy** [comment]
`#include <iostream>

size_t HEADER_SIZE_IN_BYTES = 1;
//typedef uint64_t BalValue;
typedef int64_t BalInt;
uint64_t TAG_MASK = 0b11;

uint8_t * int_to_any(BalInt i) {
    if (0x3FFFFFFFFFFFFFFF >= i && i >= -0x4000000000000000) [[likely]] {
        return reinterpret_cast<uint8_t *>((i << 1) | 1);
    } else {
        auto *boxHeader = static_cast<uint8_t *>(malloc(sizeof(uint8_t *) + HEADER_SIZE_IN_BYTES));
        // casted to unit8 so we can do pointer arithmetic in byte sizes, necessary for HEADER_SIZE_IN_BYTES addition
        BalInt *boxBody = reinterpret_cast<BalInt *>(boxHeader + HEADER_SIZE_IN_BYTES);
        *boxBody = i;
        return reinterpret_cast<uint8_t *>(boxHeader);
    }
}

BalInt any_to_int(uint8_t * i) {
    if (reinterpret_cast<BalInt>(i) & 1) [[likely]] {
       return (reinterpret_cast<BalInt>(i) >> 1);
    } else {
        if ((reinterpret_cast<BalInt>(i) & TAG_MASK) == 0) {
            BalInt *p = reinterpret_cast<BalInt *>(i + HEADER_SIZE_IN_BYTES);
            return *p;
        } else {
            abort(); // type cast panic
        }
    }
}`

**Comment by ramakotareddy** [comment]
```
#include <iostream>

size_t HEADER_SIZE_IN_BYTES = 1;
//typedef uint64_t BalValue;
typedef int64_t BalInt;
uint64_t TAG_MASK = 0b11;

uint8_t * int_to_any(BalInt i) {
    if (0x3FFFFFFFFFFFFFFF >= i && i >= -0x4000000000000000) [[likely]] {
        return reinterpret_cast<uint8_t *>((i << 1) | 1);
    } else {
        auto *boxHeader = static_cast<uint8_t *>(malloc(sizeof(uint8_t *) + HEADER_SIZE_IN_BYTES));
        // casted to unit8 so we can do pointer arithmetic in byte sizes, necessary for HEADER_SIZE_IN_BYTES addition
        BalInt *boxBody = reinterpret_cast<BalInt *>(boxHeader + HEADER_SIZE_IN_BYTES);
        *boxBody = i;
        return reinterpret_cast<uint8_t *>(boxHeader);
    }
}

BalInt any_to_int(uint8_t * i) {
    if (reinterpret_cast<BalInt>(i) & 1) [[likely]] {
       return (reinterpret_cast<BalInt>(i) >> 1);
    } else {
        if ((reinterpret_cast<BalInt>(i) & TAG_MASK) == 0) {
            BalInt *p = reinterpret_cast<BalInt *>(i + HEADER_SIZE_IN_BYTES);
            return *p;
        } else {
            abort(); // type cast panic
        }
    }
}
```

**Comment by ramakotareddy** [comment]
@ruvi-d , exactly where i miss the reinterpret_cast type in the any_to_int function ?
i think i miss in the below line right ?

' ' ' BalInt *p = reinterpret_cast<BalInt *>(i + HEADER_SIZE_IN_BYTES); ' ' '

**Comment by ramakotareddy** [comment]
@ruvi-d , exactly where i miss the reinterpret_cast type in the any_to_int function ?
i think i miss in the below line right ?

``` BalInt *p = reinterpret_cast<BalInt *>(i + HEADER_SIZE_IN_BYTES); ```
