### ISSUE TITLE
Implement `!is` operator

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#271]
Follow on from #144 

Specified https://github.com/ballerina-platform/ballerina-spec/issues/752

**Comment by jclark** [comment]
@ushirask If you haven't started on this yet, then don't. Better to help with some of the things needed for #262.

**Comment by ushirask** [comment]
> @ushirask If you haven't started on this yet, then don't. Better to help with some of the things needed for #262.

I've already started on this, I'll try to finish up by today and start on the other

**Comment by ushirask** [comment]
There are 2 ways BIR instructions for this can be created for this.
1. Use existing BooleanNot and TypeTest instructions and add two instructions (change only frontend)
2. Create a new NotTypeTest instruction

Which approach would be more suitable?

**Comment by jclark** [comment]
I would actually suggest a third way: add a negated field to the TypeTestInsn. This parallels what EqualityInsn does. Do the same thing with the AST.

Be sure to test conditional variable type narrowing with `!is`.
