### ISSUE TITLE
Types should be narrowed as for `else` after `if` that cannot complete normally

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#272]
Follow on from #129 and #156

Specified https://github.com/ballerina-platform/ballerina-spec/issues/73

**Comment by manuranga** [comment]
Simple case can be handled by adding a narrowing just after `if` (or `else`).
```ballerina
import ballerina/io;

public function main() {
    int|boolean x = 2;
    if x is boolean {
        boolean _ = x;
        return;
    }
    int _ = x;
}
```
A more involved case:

```ballerina
import ballerina/io;

public function main() {
    int|boolean|float x = 0.1;
    if x is int|boolean {
        if x is int {
            return;
        }
        boolean _ = x;
    }
    boolean|float _ = x;
}
```
At the end of the outer `if`, we need `x` to be narrowed to `narrowing.ifFalse ∪ narrowing-at-end-of-body`.

Another case:
```ballerina
public function func(boolean y) {
    int|boolean|float x = 0.1;
    if y == true {
        if x is int|boolean {
            return;
        }
    }
    else {
        if x is boolean|float {
            return;
        }
    }
    float|int _ = x;
}
```
Merging of narrowings has to happen for all `if`s. Even the ones without a narrowing in the condition.

**Comment by manuranga** [comment]
My current plan is to modify `codeGenStmts` to return bindings, and at the end of if-else combine bindings from both paths into a new binding.

**Comment by manuranga** [comment]
Was able to handle above 3rd case with above approach. That is, get the bindings from if-body and else-body via modified `codeGenStmts`, diff it with current binding, union two sets of bindings and add `CondNarrowInsn`s after else body. I am not giving the correct `basis` yet.

Two more interesting cases that got handled : [multi-var-narrow](https://gist.github.com/manuranga/fafc963fd152b3b862973d2bd8401c08), [tighten-inner.bal ](https://gist.github.com/manuranga/bec1902d3c12dd65c8f0e15569784f03)
