### ISSUE TITLE
Migrate String new representation

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#273]
**Description:**

Migrate string in the on consent section to be represented in the following structure.
Get rid of the `new_string` rust function.
Migrate `print_string` and other rust functions to use this format.

```
typedef BalAsciiString struct {
   [64bit] uint64_t header = 0b000110;
   [64bit] size_t nBytes;
   [nBytes] char bytes[0]; // UTF-8 bytes go here
};
```

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shubhamnarlawar** [comment]
Reference document - https://docs.google.com/document/d/1wH9T-VTz-Ad9YnrAoT4f05nh6EpBrZxqvfhSzfWng3s/edit?ts=6063f600#heading=h.dyksfb506vbw

**Comment by shubhamnarlawar** [comment]
Process - 

1. Create a pointer to struct `BalAsciiString`.
2. Add `CodeGenUtils::storeValueInBalAsciiString()` to fill members of `BalAsciiString` object.
3. Generate Store instruction
4. Modify rust `print_string` to handle `BalAsciiString` struct object.
