### ISSUE TITLE
Call external function that allocates GC-able memory from ballerina

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#277]
**Description:**

Call an external function (We could use C to write this function) using extren support from the ballerina, allocate memory on the ballerina side by calling GC_MALLOC. Link the generated binary with the bhorm gc.. Check if repeated calling form ballerina will deallocate memory.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
Please follow the discussion for more details https://github.com/ballerina-platform/nballerina/discussions/267

**Comment by KavinduZoysa** [comment]
Closing this issue, because expected things are tested and verified here. https://github.com/KavinduZoysa/test-GCs/tree/master/boehm
