### ISSUE TITLE
Restore code coverage after constant folding

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#277]
The implementation of constant folding in #267 will mean that some tests that previously tested codeGen and the backend get folded away. So we need some revised tests to ensure we have the same coverage as before.

**Comment by KavinduZoysa** [comment]
@jclark, I found that before the constant folding the method [intSubtypeWidenUnsigned](https://github.com/ballerina-platform/nballerina/blob/f5192d944cc4e36be35cd56fb82ca738652370f1/compiler/modules/types/int.bal#L53) was covered by the example (1|1) == 2 (a test available in front/test/testConst.bal). This method was called via [widenUnsigned](https://github.com/ballerina-platform/nballerina/blob/f5192d944cc4e36be35cd56fb82ca738652370f1/compiler/modules/types/core.bal#L568). AFAIU, that method gets hit for a type which is less that int32. Can we test this method at this moment?

**Comment by jclark** [comment]
@KavinduZoysa Don't think it's possible to test it via a complete `.bal` file right now. Can you do a unit test instead? It's implementing the rules here: https://ballerina.io/spec/lang/2021R1/#section_6.30
