### ISSUE TITLE
Implement equality for `float`

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#279]
Part of #262 is to make the equality operators work for float.

This will require splitting _bal_eq into two functions, one for `==` and one for `===`.

This is follow on from #278

**Comment by manuranga** [comment]
From what I can see, spec uses the word `exact equality`. Word `identity` is only used in conjunction with the word `storage`.
> The === operator tests for exact equality.

So I think the function should also be called `_bal_exact_eq` or slimier.

**Comment by jclark** [comment]
I agree it should be called `_bal_exact_eq`.

I suggest the following staging:

1. Implement _bal_float_eq and _bal_float_exact_eq  (leaving _bal_eq unchanged) #278
2. Split _bal_eq at the same time as we fix buildEquality to handle floats

**Comment by manuranga** [comment]
I looked into whether we can optimize this to two comparisons but I couldn't find a way.

It comes down to finding a way to check if **both** operands are NaNs. Single `fcmp` doesn't give us that. `ord` and `uno` gives us the same information, only negated.

| op1 | op2 | ord | uno | oeq  | ueq  | andpd   | We need |
|-----|-----|-----|-----|------|------|---------|---------|
| n   | n   |   1 |   0 | n==n | n==n | garbage | n==n    |
| NaN | n   |   0 |   1 |    0 |    1 | garbage |       0 |
| n   | NaN |   0 |   1 |    0 |    1 | garbage |       0 |
| NaN | NaN |   0 |   1 |    0 |    1 | NaN     |       1 |

I did look at what v8 does. Full details [available here](https://gist.github.com/manuranga/e8c8e50e666ed44fbbc871267a6ad1cd). It's output is not very clean. Still I can see 3 mmx comparisons, bit extract (`vpextrd`), and bitwise comparison, for `is` check which is similar to our `===`.

I am going ahead three fcmp version.
```
define zeroext i1 @_bal_float_eq(double %0, double %1) {
 %3 = fcmp oeq double %0, %1
 %4 = fcmp uno double %0, 0.000000e+00
 %5 = fcmp uno double %1, 0.000000e+00
 %6 = and i1 %4, %5
 %7 = or i1 %3, %6
 ret i1 %7
}
```
(I also tried and-ing and then checking NaN, which is perhaps slightly better.)

**Comment by jclark** [comment]
I see the problem.  The following C:

```
#include <math.h>
#include <stdbool.h>

bool _bal_float_eq(double x, double y) {
    return x == y | (isnan(x) == isnan(y));
}
```

gives

```
define dso_local zeroext i1 @_bal_float_eq(double %0, double %1) local_unnamed_addr #0 !dbg !7 {
  %3 = fcmp oeq double %0, %1, !dbg !17
  %4 = fcmp ord double %0, 0.000000e+00, !dbg !18
  %5 = fcmp uno double %1, 0.000000e+00, !dbg !19
  %6 = xor i1 %4, %5, !dbg !20
  %7 = or i1 %3, %6, !dbg !21
  ret i1 %7, !dbg !22
}
```

(which I think is equivalent). So I think you might as well do this in C.

We should probably add a langlib function to float to do the equivalent of C `==`.

**Comment by jclark** [comment]
This gives exactly the same as yours:

```
bool _bal_float_eq(double x, double y) {
    return x == y | (isnan(x) & isnan(y));
}
```

which is reassuring.

**Comment by jclark** [comment]
This discussion ought to be in #278.

**Comment by jclark** [comment]
But on ARM the LLVM IR code generates much better assembly code than the C, so we should stick to the LLVM IR.

**Comment by jclark** [comment]
I also wonder how it compares against a branch:

```
define zeroext i1 @_bal_float_eq2(double %0, double %1) {
 %3 = fcmp oeq double %0, %1
 br i1 %3, label %4, label %5
4:
 ret i1 %3
5:
 %6 = fcmp uno double %0, 0.000000e+00
 %7 = fcmp uno double %1, 0.000000e+00
 %8 = and i1 %6, %7
 ret i1 %8
}
```

I am guessing that in real life comparing two NaNs for equality is pretty unlikely and I was reading that branches never taken are basically free https://blog.cloudflare.com/branch-predictor/

**Comment by manuranga** [comment]
I also wrote that first, thought the branch might have a negative impact. Maybe predictor will come out on the top.

**Comment by jclark** [comment]
I just did a very quick and dirty measurement and they seem pretty similar, so I suggest sticking with your non-branching version.

**Comment by jclark** [comment]
Remaining part of the is to add support for float to buildEquality using bal_float_eq and bal_float_exact_eq. This requires having separate functions for bal_eq and bal_exact_eq.

We need to do this before we can test #274.

**Comment by jclark** [comment]
We need to make sure this works in const too. foldBinaryEqual does this

```
        SimpleConst left = leftExpr.value;
        SimpleConst right = rightExpr.value;
        boolean equal = left == right;
```

Is that going to work right in jBallerina when left and right are float NaN?

**Comment by manuranga** [comment]
Ah it's not going to work in beta2, will use a function, it'll be fixed in beta3.
BTW, I'll need a NaN to write the tests, so will need `0.0/0.0` to work.

**Comment by jclark** [comment]
There shouldn't be anything special needed for `0.0/0.0` to work.
