### ISSUE TITLE
Implement conversions between `float` and `int` in runtime

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#288]
Implement conversions between `float` and `int` in runtime
Part of #262

**Comment by manuranga** [comment]
- Int to float should be straightforward using `sitofp`. Could be done in build.bal itself. Yet I am unsure how to send this part as a PR, since I haven't done the BIR yet, let me try.

- Float to int should panic for some cases, but `fptosi` produces a silent `undef`. I propose to pre-check and panic. Clang is doing something similar when `sanitize` is enabled. https://godbolt.org/z/ajoM1hWPE

**Comment by jclark** [comment]
If int-to-float can be done in `build.bal`, then it doesn't need any runtime support and you can do it when you implement float support in `build.bal`.

**Comment by jclark** [comment]
Pre-check and panic seems like a good approach. In the case where there should be a panic, the C runtime function should return a  value saying there has been an error, rather than panicking directly: build.bal will check for this and generate a panic with the correct line number.

**Comment by manuranga** [comment]
How about a signature that looks like below in that case?

```llvm
define { i64, i1 } @_bal_float_to_int(double %0) {
    ...
}
```

**Comment by jclark** [comment]
Looks good.

**Comment by jclark** [comment]
I noticed this:

https://llvm.org/docs/LangRef.html#llvm-lrint-intrinsic

Not sure if it helps.

**Comment by manuranga** [comment]
`@llvm.lrint.i64.f64` did work. It gets compiled to a single instruction `cvtsd2si`, whereas `fptosi` gets compiled to `cvttsd2si`
