### ISSUE TITLE
Implement `decimal` basic type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#289]
We can use the decNumber package from 

https://github.com/hercules-390/decNumber-icu-368

or

https://github.com/SDL-Hercules-390/decNumber

This has a more permissive license than the copy that comes with GCC.

Sub issues:

- [x] #755
- [x] #766
- [x] #759
- [x] #779
- [x] #777
- [x] #778
- [x] #782
- [x] #780
- [x] #781
- [x] #783

**Comment by jclark** [comment]
Note that Ballerina uses the simplified X3.274 subset described here

http://speleotrove.com/decimal/dax3274.html

**Comment by jclark** [comment]
We should have an immediate format for decimals. decNumber uses DPD format for encoding decimals, described here:

http://speleotrove.com/decimal/DPDecimal.html

This packs 3 decimal digits into 10 bits.

We have 56 bits available. So one possibility is

- 1 sign bit
- 5 bits representing an integer in the range 0-31 saying where the decimal point goes
- 50 bits encoding 15 digits (10 bits for each of 5 groups of 3 digits)

Another possibility would be BCD:

- 1 sign bit
- 7 bits representing an integer in the range 0-128 saying where the decimal point goes
- 48 bits encoding 12 digits (4 bits per digit)

or

- 1 sign bit
- 3 bits representing an integer in the range 0-7 saying how many digits after the decimal point
- 52 bits encoding 13 digits (4 bits per digit)

**Comment by jclark** [comment]
@KavinduZoysa I suggest following steps

- [ ] Familiarize yourself with http://speleotrove.com/decimal/
- [ ] Look at the two versions of decNumber I linked to, analyze the differences and figure out which one we should use
- [ ] Bring chosen one into third-party
- [ ] Figure out how to integrate into our build (as you did with libbacktrace)
- [ ] Determine whether library has built-in support for X3.274 subset, or do we need to do it ourselves

**Comment by jclark** [comment]
We could also consider this library: https://www.bytereef.org/mpdecimal/

**Comment by KavinduZoysa** [comment]
I was able to build the two versions of decNumber and run a simple example. 
If we consider about the diff between these two version there is not a difference in the core implementation (in `include` `folder` and source folder). In the [forked version](https://github.com/SDL-Hercules-390/decNumber) authors has done some build related changes such as improve and refactor build sripts, add visual studio support for windows etc and fixed some formating issues. 

My next step is,

- consider https://www.bytereef.org/mpdecimal/ and compare it with decNumber.
- check how we can support immediate format using these libraries.

Based on these steps we will be able to choose one library and continue.

**Comment by jclark** [comment]
Don't worry about immediate format for now.  Main thing is to focus on is memory allocation: the less the library does memory allocation itself, the better.

Might also be worth looking at the code gcc generates for `_Decimal128` which is built on top of decNumber.

**Comment by KavinduZoysa** [comment]
I have compared some examples in libraries `decNumber` and `mpdecimal` to identify the memory allocation. I have added the sample code with built libraries in [this repository](https://github.com/KavinduZoysa/decimal). 
For a simple addition `mpdecimal` is doing memory allocations but `decNumber` does not do. The reson is, `mpdecimal` represents data(decimal value) in a pointer and `decNumber` represents it as an array. Therefore `mpdecimal` always have to allocate memory (For that they have a method called `mpd_new` and `mpd_del` for free the memory). Please check the following structures. 

mpdecimal:
```
typedef struct mpd_t {
    uint8_t flags;
    mpd_ssize_t exp;
    mpd_ssize_t digits;
    mpd_ssize_t len;
    mpd_ssize_t alloc;
    mpd_uint_t *data; // store decimal value
} mpd_t;
```
decNumber:
```
typedef struct {
    int32_t digits;
    int32_t exponent;
    uint8_t bits;
    decNumberUnit lsu[DECNUMUNITS]; // store decimal value
} decNumber;
```

Also we can see the same thing in some other examples. 
So I think it is better if we can use decNumber because it has less number of memory allocations. 
@jclark WDYT?

**Comment by jclark** [comment]
Sounds like decNumber will be a better fit

**Comment by KavinduZoysa** [comment]
I will start to add decNumber into runtime/third-party

**Comment by jclark** [comment]
I mentioned two repos for decNumber. Which one are you planning to use and why?

**Comment by KavinduZoysa** [comment]
@jclark, as mentioned in this comment https://github.com/ballerina-platform/nballerina/issues/289#issuecomment-955961718, [forked version](https://github.com/SDL-Hercules-390/decNumber) was improved by refactoring build scripts, adding visual studio support for windows etc and fixing some formatting issues. In both versions source files and header files are not changed. Since the build has changed in the forked version, My plan is to use it. https://github.com/SDL-Hercules-390/decNumber

**Comment by jclark** [comment]
What is your plan for integrating this into our build system?  Do the improvements in the fork matter for us? If not, we should not use the fork.

**Comment by KavinduZoysa** [comment]
@jclark, To integrate this into our build system we can create object files with their CFLAGS and integrate them with our `balrt.a`. (Currently, they have libdecNumbericu36864.a/libdecNumber64.a)
My concern is in the two versions, CFLAGS are different.
1. initial version:
`C_FLAGS = -O2 -g -DNDEBUG  -D DECLITEND=1 -D DECPRINT=0 -D HAVE_PLATFORM_H -m64 -fPIC`
2. forked version:
`C_FLAGS = -O2 -g -DNDEBUG  -D DECPRINT=0 -D LITTLE_ENDIAN=1234 -D BIG_ENDIAN=4321 -D BYTE_ORDER=LITTLE_ENDIAN -D DECLITEND=1 -D HAVE_PLATFORM_H -D VERS_STRING=3.68.0.99-gda66509  -fPIC -fPIC `

Currently, I am trying to understand the exact use of these flags.

**Comment by jclark** [comment]
`-fPIC` is a shared library thing, which I don't think we need or want.

nballerina only supports little-endian currently, so we can assume that (the flags are effectively sayign BYTE_ORDER is 1234.

We want to keep our binaries as small as possible, which means that it important to compile it with only the features we need, and to compile it  to minimize what always gets linked in. Please have a look at how gcc does things (since gcc uses decNumber to support the _Decimal128 type in C).

**Comment by KavinduZoysa** [comment]
ACK.

**Comment by KavinduZoysa** [comment]
@jclark, In `decNumber` library, they support both arbitrary precision format and fixed precision formats (128 bits, 64 bits, 32 bits). In gcc, they are using fixed precision formats. Those are named as decQuad(128 bits), decDouble(64 bits), and decSingle(32 bits). In our case, I think initially we only need to use `decQuad`, and we can minimize the files we link to our runtime.
Also in gcc, their CFLAGS only contains the -g and -O2.

**Comment by jclark** [comment]
Right, we need only 128-bit support.

**Comment by KavinduZoysa** [comment]
Then we can start our work with the initial version of `decNumber` https://github.com/hercules-390/decNumber-icu-368

**Comment by jclark** [comment]
> Determine whether library has built-in support for X3.274 subset, or do we need to do it ourselves

The answer to this is that it _does_ have support for the subset:

- compile with `DECSUBSET` defined as 1
- at runtime, set `extended` in  `decContext` to 0

This is going to make things a lot easier.

**Comment by jclark** [comment]
There's a difficulty:

- the decNumber library provides two distinct implementations of decimal
   - an arbitrary precision implementation that uses the decNumber type
   - a fixed precision implementation that supports decSingle, decDouble, decQuad
- Ballerina's decimal type is fixed precision (128-bit) type, corresponding to decQuad
- the decQuad is much preferable to decNumber, because it is faster and does no memory allocation
- but from a superficial look at the source, it appears that while the decNumber type supports DECSUBSET, decQuad does not

So that means we need to implement the subset ourselves, which is going to require some deeper understanding.

Other non-trivial things that will need doing:

1. implement int64 to decQuad conversion; decFloat only provides conversion to int32
2. compile-time support for going from a `decimal` to `byte[]` that is the IEEE representation (DPD variant); this should really be a langlib function

**Comment by jclark** [comment]
There's also an Intel library for this (which I saw referenced from the Julia project)

https://www.intel.com/content/www/us/en/developer/articles/tool/intel-decimal-floating-point-math-library.html
http://www.netlib.org/misc/intel/

**Comment by jclark** [comment]
The decNumber module is also in ICU here:

https://github.com/unicode-org/icu/blob/main/icu4c/source/i18n/decNumber.cpp

But that looks not like what we want.

The canonical location looks to me to be:

http://speleotrove.com/decimal/decNumber-icu-368.zip

(The library is written by Mike Cowlishaw, and speleotrove.com is his site.)

So I think we should unpack that and import it. Not sure about the git details of this. @manuranga Any thoughts?

**Comment by jclark** [comment]
I had a look at how gcc handles these conversions. I was surprised to find it handles them by going via a string.

**Comment by jclark** [comment]
Actually I think the best source will be this: https://github.com/dnotq/decNumber

This is linked to from http://speleotrove.com/decimal/

**Comment by jclark** [comment]
The defines we need are:

```
-DHAVE_STDINT_H -DHAVE_STDBOOL_H -DDECPRINT=0
```

**Comment by KavinduZoysa** [comment]
> Actually I think the best source will be this: https://github.com/dnotq/decNumber
> 
@jclark, are we going to use the resource files available in this repository instead of https://github.com/hercules-390/decNumber-icu-368

**Comment by jclark** [comment]
We should use the dnotq directory or the unpacked zip from speleotrove, because there is a clearer provenance than the hercules repo.

**Comment by jclark** [comment]
I want to end up with a directory `runtime/third-party/decNumber` that contains the files from the zip like this: https://github.com/dnotq/decNumber/tree/main/decNumber-icu-368

**Comment by jclark** [comment]
The spec has only this on the subset:

> The decimal type corresponds to the ANSI X3.274 subset of IEEE 754-2008, which has the following simplifications:
>
> * +0 and -0 are not distinguished; if the coefficent is zero, then the sign is also constrained to be zero;
> * NaN, infinities and subnormals are not supported; operations that would result in one of these values according to the normal rules of IEEE 754-2008 instead result in a panic.

This is not really the full story, which is here:

http://speleotrove.com/decimal/dax3274.html

So I think for now, we can just implement what the spec says, and have a spec issue to flesh out exactly how much of X3.274 we want to adopt. (I added the spec issue https://github.com/ballerina-platform/ballerina-spec/issues/989.)

In practical terms, this means that after each decimal operation (and for constants)

- check for NaN, Infinity or subnormal, and give an error if we got one (we can get this from the status flags)
- if its mathematically, equal to 0, then fix the sign to be positive

**Comment by jclark** [comment]
Let's just use the zip file. That is the ultimate source of truth.  http://speleotrove.com/decimal/decNumber-icu-368.zip

@manuranga Can you please do the necessary git incantation to get this into our repo at runtime/third-party/decNumber?

**Comment by jclark** [comment]
There's a lot of scope for clever optimizations with decimal, but we need to resist the temptation to start optimizing at this stage, since it has no importance for self-hosting.  What we need at this stage is the simplest thing that can work correctly and is in the right direction.

This means we should have a single (tagged) representation, which is just a decQuad on the heap.  We don't want to include decNumber include files in balrt.h. We can just declare

```
typedef struct {
  uint64_t longs[2];
} decimal128;
```

and have an inline function to cast to decQuad.

Conversions to/from float/int will go via C (nul-terminated, ASCII) strings ); we can use fixed-sized buffers on the stack for this.

We can also C strings to store decimal constants, and then call `decQuadFromString` at runtime.

**Comment by manuranga** [comment]
So far we have got all of our sources from git, but the third party script should work with zip file as well. I'll use `wget` and `unzip`.

**Comment by jclark** [comment]
@KavinduZoysa I will add this to the Makefile

**Comment by jclark** [comment]
@KavinduZoysa We need to figure out 

- which status fields in decContext should turn into Ballerina errors
- whether all cases that should be Ballerina errors can be detected from the status fields (I think so, but not sure)

Not sure about the underflow case.  I think that's not an error: just the value becoming zero. But I'm not 100% sure.

**Comment by KavinduZoysa** [comment]
This is the summerize we had based on negative zero.

The places where negative zero can occur are mentioned in http://speleotrove.com/decimal/daops.html (last point of `Arithmetic operation notation`)
Here we only need to consider points 1 and 4.

We do not need to consider point 2, because we are not giving negative zero input. We can remove point 3 because we are not using the round-floor rounding. The last 5 cases belong to langlib operations.

**Comment by KavinduZoysa** [comment]
@jclark, these are my findings about underflow case.

- If adjusted exponent or exponent of conversion is less that E_min (`-6143`) then the result is called subnormal. If we check decQuadClass of 1E-6144 we can get `+Subnormal`. DEC_Subnormal flag is set if result is a subnormal value. But this flag is set only in decNumber module.
- For submornal result minimum exponent value is defined as `E_min - (precision - 1)`. It is called E_tiny. In our case it is -6176
- If a result is rounded in order to ensure exponent is not less than E_tiny, inexactness occurs in the result and underflow occurs. If we check the flags for a value `0.1E-6176` we can see flags underflow and inexact. Also result is `0E-6176` and class id `+Zero`
- In any underflow case, exponent is E_tiny

**Comment by jclark** [comment]
The question we need to answer is what code do we put in `finish` to give effect to the Ballerina spec's requirement that the decimal type does not include subnormal values. 

First part of this is how do we detect whether we have a subnormal value. Looks like we check whether decClass is POS_SUBNORMAL or NEG_SUBNORMAL. Right?

Second part of this is what do we do if we get a subnormal value.  This needs to follow the X3.274 subset. Two possibilities are zero or an error.  My understanding is that zero is the correct answer. But we should double-check to be sure to with the decNumber behaviour. Create a test program using decNumber compiled with DECSUBSET=1 and set context->extended  = 0.

My guess is that `finish` needs to simply set the result to zero if the decClass is any of NEG_ZERO, POS_SUBNORMAL or NEG_SUBNORMAL.

Next stage is to implement mul, div, rem arithmetic operations, which will allow us to test subnormal handling.

For rem we need to be careful about IEEE remainder semantics vs C/LLVM/Ballerina remainder semantics and make sure we get the right one.

**Comment by jclark** [comment]
Other functions we need (all starting with `_bal_decimal_`):

- `neg` - used for unary negation
- `cmp` - returns 1/0/-1 used for == and relational operators
- `exact_eq` - used for `===` ; probably needs to canonicalize and then use memcmp
- `from_float` - argument is a C double; needs to return a panic code if the argument is NaN or infinite; goes via a C string
- `from_int` - argument is an int64_t; cannot panic; when the argument fits in an int32_t use the decQuad functions for 32-bit ints; otherwise go via a C string
- `to_float` - result is a double; cannot panic; go via a C string
- `to_int` - returns a struct with an int64_t and a bool; bool indicates overflow as with the LLVM intrinsics for int arithmetic with overflow; fractional values should be rounded; this one is quite tricky

**Comment by jclark** [comment]
Please also start to create some tests in `testSuite/11-decimal/opN-uv.bal` to capture the various tricky points we are discussing (where op is e.g. `add`).  If jBallerina gets any of them wrong, you can report those.

**Comment by KavinduZoysa** [comment]
> The question we need to answer is what code do we put in `finish` to give effect to the Ballerina spec's requirement that the decimal type does not include subnormal values.
> 
> First part of this is how do we detect whether we have a subnormal value. Looks like we check whether decClass is POS_SUBNORMAL or NEG_SUBNORMAL. Right?

Yes, `DEC_Subnormal` flag is not raised in decQuad module, it is only available in decNumber module. So we need to check the decClass

> 
> Second part of this is what do we do if we get a subnormal value. This needs to follow the X3.274 subset. Two possibilities are zero or an error. My understanding is that zero is the correct answer. But we should double-check to be sure to with the decNumber behaviour. Create a test program using decNumber compiled with DECSUBSET=1 and set context->extended = 0.
> 
> My guess is that `finish` needs to simply set the result to zero if the decClass is any of NEG_ZERO, POS_SUBNORMAL or NEG_SUBNORMAL.
> 
Yes that is correct. Some examples are mentioned below.
|Value|full spec|subset|
|-------|-----------|---------|
|1E-6176|+Subnormal, 1E-6176|+Zero, 0|
|0.1E-6176|+Zero, 0E-6176|+Zero, 0|
|0*-1|-Zero, -0|+Zero, 0|

**Comment by KavinduZoysa** [comment]
@jclark, according to ballerina spec, subnormals should be panic.

```
NaN, infinities and subnormals are not supported; operations that would result in one of these values according to the normal rules of IEEE 754-2008 instead result in a panic.
```
But here, we are going to make it zero. Are we going to change the spec accordingly?

**Comment by jclark** [comment]
Ahh, that's a bug in the spec: it contradicts the statement that decimal "corresponds to the ANSI X3.274 subset".

**Comment by jclark** [comment]
I made an issue: https://github.com/ballerina-platform/ballerina-spec/issues/995

**Comment by jclark** [comment]
There's a problem with remainder: https://github.com/ballerina-platform/ballerina-spec/issues/998

**Comment by KavinduZoysa** [comment]
@jclark, related to `from_float` conversion, is that okay to use `emyg_dtoa_non_special` (from `third-party/dtoa`) in order to generate C string for given double value?

I have tried to generate c string with `sprintf`, but it does not give correct result as expected.

**Comment by jclark** [comment]
@KavinduZoysa We should be using third-party/dtoa not sprintf.

**Comment by jclark** [comment]
We should implement https://github.com/ballerina-platform/ballerina-spec/issues/943 when were are doing literals

**Comment by KavinduZoysa** [comment]
@jclark, Related to `to_int` conversion, 
Initially, I check the overflow case and convert decQuad value to decString. Then I have tried `strtol` and `sscanf` method to convert decString to int. 
But for examples like `1e3` which available exponent(`e`), the above methods do not work. It only parses the coefficient. Also for fractional values, the rounding is incorrect. So what I thought was to use `_bal_decimal_to_float  and `_bal_float_to_int` together.
WDYT?

**Comment by jclark** [comment]
Converting to int is a straightforward operation: it should not require going through float (which are very complicated conversions).

Try to find some decQuadXXX functions that will turn it into a decQuad that will convert to a string that strtol will understand. Look at decQuadToIntegralExact and decQuadQuantize
