### ISSUE TITLE
Add prebuild LLVM packages in CI script

### ISSUE THREAD

**Issue by shubhamnarlawar** [ballerina-platform/nballerina#29]
- Installing prebuild llvm binaries are required for the build process of nballerina. Using this, building llvm project from scratch could be avoided.

**Comment by shubhamnarlawar** [comment]
@dulvinw - Can you please put below lines of code in the CI script?

It will download and extract LLVM-11.0 release packages.

`cd $HOME`
`wget https://debian.pkgs.org/sid/debian-main-amd64/llvm-11-dev_11.0.0-5+b1_amd64.deb.html`
`dpkg -x llvm-11-dev_11.0.0-5+b1_amd64.deb $HOME/llvm-11-dev`

`https://debian.pkgs.org/sid/debian-main-amd64/llvm-11-tools_11.0.0-5+b1_amd64.deb.html`
`dpkg -x llvm-11-tools_11.0.0-5+b1_amd64.deb $HOME/llvm-11-tools`


(Post build commands)

`rm -rf $HOME/llvm-11-dev`
`rm -rf $HOME/llvm-11-tools`

**Comment by dulvinw** [comment]
Don't we need another wget for the tools as well? @shubhamnarlawar

**Comment by shubhamnarlawar** [comment]
> Don't we need another wget for the tools as well? @shubhamnarlawar

Yes. Corrected in above comment.

**Comment by dulvinw** [comment]
I think the links are invalid. I get 403 trying locally.

**Comment by shubhamnarlawar** [comment]
> I think the links are invalid. I get 403 trying locally.

Let me check!

**Comment by shubhamnarlawar** [comment]
> I think the links are invalid. I get 403 trying locally.

The links are not working now. Maybe some server issue at debian.pkgs.org

I had used the same links and downloaded the packages. Let me come up with the solution.

**Comment by dulvinw** [comment]
Sure. Thanks

**Comment by shubhamnarlawar** [comment]
Should we put these packages somewhere inside nballerina? Will it be a correct approach?

Sometimes the link may not work(just now it happened) and hence CI will fail whenever a new PR will be sent if links are not working.

**Comment by shubhamnarlawar** [comment]
@dulvinw - Try these links - 

`wget http://ftp.br.debian.org/debian/pool/main/l/llvm-toolchain-11/llvm-11-dev_11.0.0-5+b1_amd64.deb`
`wget http://ftp.br.debian.org/debian/pool/main/l/llvm-toolchain-11/llvm-11-tools_11.0.0-5+b1_amd64.deb`

**Comment by dulvinw** [comment]
They are working. Let me try with them

**Comment by dulvinw** [comment]
Should I also remove the llvm building steps or that should be done in a separate stage?

**Comment by shubhamnarlawar** [comment]
> Should I also remove the llvm building steps or that should be done in a separate stage?

No. Please keep llvm building process as same. Currently the testing infrastructure is dependant on llvm project present inside nballerina.

Once, nballerina is independent of llvm project, then we can remove it and use above prebuilt binaries.
