### ISSUE TITLE
Implement `string:Char` type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#292]
Need a simple way to represent this that

- is closed under union, intersection, difference operations
- combines with the existing list of singletons

**Comment by jclark** [comment]
May be this. Additional field:

```
   boolean? isChar;
```

Semantics are:
- true - value belongs to type only if it is of length 1
- false - value belongs to type only if it is not of length 1
- () - no constraint on value

This is in addition to the constraint from the existing two fields.  Then we need to have a function that removes from the existing singleton list anything that the isChar constraint makes redundant.

**Comment by rdhananjaya** [comment]
Same as https://github.com/ballerina-platform/nballerina/issues/477
