### ISSUE TITLE
Allow type descriptor in constant declarations

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#293]
Const declarations should be able to specify a type descriptor so as to provide the expression with a contextually expected type.

**Comment by jclark** [comment]
@manuranga Not sure what  `add const expressions` meant.

I guess you meant #294.

**Comment by manuranga** [comment]
I was thinking we'd have to select a sub set of [const expressions](https://ballerina.io/spec/lang/2021R1/#const-expr) to be consistent.

**Comment by jclark** [comment]
We already support const expressions (as specified in https://github.com/ballerina-platform/nballerina/blob/main/docs/subset05.md): const-ness is enforced semantically.

**Comment by jclark** [comment]
This is defined in the subset

https://github.com/ballerina-platform/nballerina/blob/main/docs/subset06.md

**Comment by manuranga** [comment]
> This is defined in the subset ... 6 ...

Not sure I understand this statement, I still need to change 
`const-decl = ["public"] "const" [basic-type-name] identifier "=" const-expr ";"`
to 
`const-decl = ["public"] "const" [type-desc] identifier "=" const-expr ";"`
Isn't that correct?

**Comment by jclark** [comment]
No: in the subset the only kind of type-desc that is allowed following `const` is a basic-type-name.

**Comment by manuranga** [comment]
Ah got it.

**Comment by jclark** [comment]
Note that when an expression references an identifier declared with `const`, the type of the identifier will be a singleton. For example:

```
const int X = 1;
const int Y = 2;
type XY = X|Y;
XY n = X;  // type of X on RHS is singleton `1` not `int`
```

The purpose of the type in the `const` declaration is to give the contextually expected type for the expression. It is also a constraint on the value of the constant.
