### ISSUE TITLE
Allow floating point literals in expressions

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#294]
This is part of #286.

**Comment by jclark** [comment]
Includes
- startPrimaryExpr needs to create FpLiteralExpr from DECIMAL_FP_NUMBER
- ConstValueExpr needs to allow float
- const.bal needs to support folding on floats
- Expr needs to allow NumericLiteralExpr instead of just IntLiteralExpr

**Comment by jclark** [comment]
This is all straightforward apart from #274.

**Comment by jclark** [comment]
Also needs support in types module for float as a constant e.g. t:containsConst, t:singleton, t:singleShape

**Comment by jclark** [comment]
@manuranga This is now done, apart from #274, right?

**Comment by manuranga** [comment]
Yes, let me close this.
