### ISSUE TITLE
Add support for Float and Boolean Types in the TypeCast framework

### ISSUE THREAD

**Issue by ayonam** [ballerina-platform/nballerina#31]
**Description:**
Add the support for Floating Point and Boolean data types to the Type cast framework.  Currently the framework only handles integers.

**Suggested Labels:**

**Suggested Assignees:**
@ramakotareddy @shubhamnarlawar @ayonam 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ruvi-d** [comment]
support was added in #41 
good to close
