### ISSUE TITLE
Implement constReal in jni.llvm

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#310]
Catch up with print.llvm changes in #306.

Needed for #262.

@heshanpadmasiri Can you look at how it decides whether to use hex vs decimal formats for float?

**Comment by heshanpadmasiri** [comment]
Documentation says "the only time hexadecimal floating-point constants are required (and the only time that they are generated by the disassembler) is when a floating-point constant must be emitted but it cannot be represented as a decimal floating-point number in a reasonable number of digits". Based on my testing this "reasonable number of digits" is 7 (ex :1.12345 => 1.123450e+00 will be decimal float but 1.23456 will be hex).
It always uses hex for special values such as

- Infinity = 0x7FF0000000000000
- Nan = 0x7FF8000000000000

**Comment by jclark** [comment]
@heshanpadmasiri Thanks. Please take #307 and fix to be consistent with jni.llvm.
