### ISSUE TITLE
Determine right code to generate for `%` operator on floats

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#313]
Ballerina semantics for `%` for float are based on Java: https://ballerina.io/spec/lang/2021R1/#section_6.23

LLVM provides `frem` instruction: https://llvm.org/docs/LangRef.html#i-frem

Need to check whether these are the same and if not what to generate.

**Comment by jclark** [comment]
Needed for #262. Relates to #312

**Comment by heshanpadmasiri** [comment]
Based on my testing `frem` generates the expected results (including "negative" 0, NaN and Infinity) according to the ballerina spec. (Officially it is suppose to be identical to libm ‘fmod’ function )

**Comment by jclark** [comment]
Thanks. Could you write a `FVfmod00.bal` test case for `%` this? We can use this when #319 is implemented. Then we can close this issue.
