### ISSUE TITLE
Enable disabled tests as we make progress in BalValue 

### ISSUE THREAD

**Issue by ramakotareddy** [ballerina-platform/nballerina#314]
Disabled some tests from any, anydata, array, union and optiona-types. We will have to add them back as we make progress in BalValue Representation.

Currently we are supporting only int_to_any and any_to_int typecast.

_Originally posted by @ruvi-d in https://github.com/ballerina-platform/nballerina/issues/308#issuecomment-841759342_

**Comment by ramakotareddy** [comment]
#252

**Comment by ruvi-d** [comment]
@ramakotareddy : better create separate issues for each functionality that you had to disable

**Comment by ramakotareddy** [comment]
Created separate issues for each disabled functionality.
