### ISSUE TITLE
Add LLVM module support for `fnegate` instruction

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#314]
Need support for `fnegate` in order to implement unary `-` on float.

**Comment by jclark** [comment]
Needed for #262

**Comment by heshanpadmasiri** [comment]
@jclark is this [`fneg`](https://llvm.org/docs/LangRef.html#fneg-instruction) instruction? 
If so I'll add a new function `fNeg(Value val, string? name=()) returns Value` similar to  [`LLVMBuildFNeg`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga93de3da5c9ab84b1fb2a167b96e37e1a)  to builder

**Comment by jclark** [comment]
Yes I meant fneg
