### ISSUE TITLE
Add support for handling strings in nBallerina

### ISSUE THREAD

**Issue by ayonam** [ballerina-platform/nballerina#32]
**Description:**
Currently the nBallerina implementation does not handle strings.  Need to add support for the same in order to implement the typecast operations for strings in nBallerina.

**Suggested Labels:**

**Suggested Assignees:**
@shubhamnarlawar @ramakotareddy @ayonam 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ramakotareddy** [comment]
Added support in #41

**Comment by shubhamnarlawar** [comment]
+1 to close this issue.
