### ISSUE TITLE
Implement BIR instructions for float/int conversion

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#323]
Issue #321 will introduce new BIR instructions for float/int conversion.

These need to be implemented in the backend using #288.

This issue should wait for #321.

This is part of #262.

**Comment by jclark** [comment]
The necessary front-end support has been added, but there is a line disabling it in codeGenTypeCast.  This is because it causes many existing tests to fail. This is because a cast  `<int>x` where x has type `any` needs to generate a conversion to int to cover the possibility that x is a float.

**Comment by manuranga** [comment]
consider the following case
```
import ballerina/io;

public function main() {
    int i = <int>f(); // @panic bad type cast
    io:println(i);
}

function f() returns float|int|boolean {
    return true;
}
```
I get a `ConvertToInt` instruction and no `TypeCast` instruction. So, I though it's the responsibility of the `ConvertToInt` to panic. Is that a correct assumption?

**Comment by jclark** [comment]
If it's only generating a ConvertToInt in that case, then it's a bug in my code: it needs to generate a TypeCast also.

Edited. It's a bug: this https://github.com/ballerina-platform/nballerina/blob/62d8d42e28db5aa92879c74182f73ce578226130/compiler/modules/front/codeGen.bal#L1121 is not computing the right type

**Comment by jclark** [comment]
The concept is that ConvertToInt panics only if the float-to-int conversion fails

**Comment by jclark** [comment]
There's some things that don't look quite right yet:

https://github.com/ballerina-platform/nballerina/pull/363#discussion_r696201859

**Comment by jclark** [comment]
In the verification, need to check that all the non-numeric part of the operand is in the result.
