### ISSUE TITLE
Add support for String objects to the Type Cast framework

### ISSUE THREAD

**Issue by ayonam** [ballerina-platform/nballerina#33]
**Description:**
Add support for String objects in the typecast framework.  The support is dependent upon the Issue #32 

**Suggested Labels:**

**Suggested Assignees:**
@shubhamnarlawar @ramakotareddy @ayonam 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Issue #32

**Comment by ramakotareddy** [comment]
Added Support in #41

**Comment by shubhamnarlawar** [comment]
+1 to close
