### ISSUE TITLE
Need git process for third-party libraries

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#335]
We need a proper git process for incorporating third party libraries that have their own github repos.

Goals

1. Be able easily to merge in new upstream versions while preserving local changes
2. Each local change should be clearly distinguished in our github history
3. Preserve third party history (not essential but nice)

We should document this.

**Comment by jclark** [comment]
@manuranga can use this for #334 

@KavinduZoysa should use this for libbacktrace and llvm-statepoint-utils for #165 #300 #46

**Comment by jclark** [comment]
I did something similar when incorporating the semtype repo. It was some combo of cloning the repo with the third-party library, pruning it and then adding it to this repo. I don't remember the details.

I suspect we should have a branch in which all third party libraries are as they are in their original repos.

**Comment by manuranga** [comment]
How about we keep original repos in `third-party` branch as [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules), along with a `.diff` file and list of selected files/dir.

We could have a script that:
1) checks branch is clean
2) switch to `third-party` branch
3) do `git submodule update --recursive`
4) apply diff
5) copy selected files to a tmp location
6) switch back
7) move from tmp location to `third-party` dir

**Comment by jclark** [comment]
The git submodules stuff looks way too complicated to me. Normal git clone no longer works in a useful way.

**Comment by manuranga** [comment]
Yes, git submodules are over complicated, but since we are doing it in a separate branch it shouldn't affect normal development activities, such as cloning, only third party dependency updatining has to deal with it.

**Comment by jclark** [comment]
I don't understand the process you are suggesting then. What does the main branch look like?

**Comment by manuranga** [comment]
I am proposing the main branch to contain just the relevant files (not full repos), with modifications.
### `main` branch
```
third-party
├── emyg
│   ├── emyg_dtoa.c
│   └── emyg_dtoa.h
└── update.sh
```
### `third-party` branch
```


third-party
└── emyg
    ├── dtoa-benchmark
    │   ├── src
    │   │   ├── emyg
    │   │   │   ├── emyg_dtoa.c
    │   │   │   └── emyg_dtoa.h
    │   │   └── ...
    │   ├── license.txt
    │   └── ...
    ├── modifications.diff
    └── mapping.txt
```

**Comment by jclark** [comment]
Ok, that sounds fine then.  I just want the keep the main branch nice and simple: no submodules and correct history. Any way of handling the third-party branch that delivers this and allows merging from upstream is good for me.

**Comment by manuranga** [comment]
After yesterday's chat I have a better understanding of what the requirement is. I think it's even better if the original files are not committed by an actual user, but rather by a bot. So mofificanon will stand out in both git history and git blame.

We already have a bot in other ballerina-platform repos to keep versions uptodate ([example bot commit](https://github.com/ballerina-platform/ballerina-distribution/commit/e9c7d8ea7e0f1e73601794d658d91e24016c447a)). 

Easiest way to do this is to use the GitHub API. Is it OK if I write this part in python like we have done in other repos? Actual developers don't have to run it, it will be executed by github, and create a PR, which we'll manually merge. The script will live in `.github` dir.

**Comment by jclark** [comment]
OK, but I don’t want to get updates from third-party repos automatically. That should be an explicit decision.

**Comment by manuranga** [comment]
Had to do a bit of experimenting but managed to do without third party actions or python.
Most online tutorials ask you to use a lot of third party actions to achieve even the simplest thing.

I am still not sure if the `github-actions` bot has enough permission in ballerina-platform organization, in my fork it does. If not, I'll change to a different bot later.
