### ISSUE TITLE
Allow `_`  on LHS of assignment

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#356]
This means another alternative for lvexpr is `_`.

In the spec, this corresponds to the combination of

https://ballerina.io/spec/lang/2021R1/#destructuring-assignment-stmt
https://ballerina.io/spec/lang/2021R1/#wildcard-binding-pattern

This is important because it allows tests to avoid unused variables.

**Comment by jclark** [comment]
Also in variable declaration to support the idiom described here: https://github.com/ballerina-platform/ballerina-spec/issues/887#issuecomment-902334830

**Comment by jclark** [comment]
Identifiers should be able to start with `_`  and `_` by itself should become a keyword.

**Comment by KavinduZoysa** [comment]
@jclark, I have started to implement the tokenizer for this issue as shown here https://github.com/ballerina-platform/nballerina/commit/327a01d9eac488dbcbd098b15c1be041f4b03d2e

Appreciate your comments on this. I can send a draft PR if it is easy to discuss.

**Comment by jclark** [comment]
Draft PR is good

**Comment by KavinduZoysa** [comment]
> Draft PR is good

Created https://github.com/ballerina-platform/nballerina/pull/485

**Comment by jclark** [comment]
Let's make the variable declaration part a separate issue #492.
