### ISSUE TITLE
Make unused local variables be an error

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#357]
The spec currently says nothing about unused variables, but my expectation is that this will become an error.

We should implement this now to avoid accumulating test cases with unused variables.

To make this convenient, we should first implement #356 (so you can so `_ = x;` to "use" `x`).

**Comment by jclark** [comment]
As part of this issue, we should fix any test cases with unused variables.

**Comment by KavinduZoysa** [comment]
@jclark, this is my plan to fix this issue. We need to identify both unused module variables and unused local variables. 
1. Add field called `boolean isUsed = false` to both records `ConstDefn` and `VarDeclStmt`.
2. Inside `lookupVarRef` we can modify `isUsed` to true.
3. At the end of codeGenFunction, we can iterate through `VardeclStmt`s and find unused local variables.
4. Create a method in `class Module` to find unused module variables, and call it at the end of `compileBalFile`.

Appreciate your suggestions on this.

**Comment by manuranga** [comment]
I think we only need to detect unused local variables, not module level variables.
Consider doing that in verifier instead of codeGen.

**Comment by jclark** [comment]
This issue is only for local variables (not constants, not parameters). I clarified the title.

**Comment by jclark** [comment]
Call the field `used` (as `Import` type does). It's better not to annotate the AST if you can avoid it. In this case you can put it in `Binding` or `Environment`. You need to be careful about the shadow bindings created for narrowed variables.  You should be able to check when a variable goes out of scope (i.e. in codeGenStmts).

Please spend some time understanding the code in codeGen.bal and come up with a new plan.

**Comment by jclark** [comment]
Note that we need to fix all our existing e cases so that they do not generate an unused variable error.
