### ISSUE TITLE
Update test suite to use same format as conformance test suite

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#358]
Development has started an a conformance test suite for the language in the spec repo, which is using a test format similar to us, but with multiple tests in a single `.balt` file:

https://github.com/ballerina-platform/ballerina-spec/blob/ac5724f6bfd36ee76d473b1ccf7064c4e158d664/conformance/lang/values-types-and-variables/array.balt

We should update our test suite to use this.

I would suggest that for each subset, we have just a few balt files (one for each feature added) e.g. subset06-float.balt

**Comment by jclark** [comment]
We should also make this work for semtype tests, so we can share these between @rdhananjaya 's port and here cc @MaryamZi

**Comment by manuranga** [comment]
Q: In the test run output, should it list each `balt` file or each case?
A: It should be each case, so that we can select to run a single case using `--tests` flag.

Q: In that case what should be the name? 
A: I think an incrementing number should work.

Eg:
```
	nballerina
		[pass] testBalt#'float.balt-00'
		[pass] testBalt#'float.balt-01'
...
		[pass] testBalt#'string.balt-00'
```

**Comment by jclark** [comment]
Instead of an incrementing number, I suggest Lnnn where nnn is the line number of the Test-Case line in the .balt file.

**Comment by manuranga** [comment]
I changed it slightly,
```
                [pass] testBalt#'map_types.balt:1'
                [pass] testBalt#'map_types.balt:17'
                [pass] testBalt#'map_types.balt:25'
                [pass] testBalt#'map_types.balt:33'
                [pass] testBalt#'map_types.balt:49'
```
This way when you ctrl+click the name, VSCode opens up the file and jump to correct location.

**Comment by manuranga** [comment]
This is where I am at right now,
https://github.com/manuranga/nballerina/compare/8334939cacdc0621edee35a54414ae553cfb0916..f074cb21d434f90828c9e9b611959cef7deaa8a3

What I am working on
1. I am in  the process of breaking up `subset01.balt` into `loops.balt`, `int.balt`, `boolean.balt`, `conditional.balt`, `function.bal`.
2. Find a way to run balt. Current public api in `main.bal` accepts file path.
   opt 1. write to separate bal files
   opt 2. create an api that accepts lines and compile
3. How to call from Makefile in batch mode
   opt 1. write to separate bal files (reuse the files from above)
   opt 2. cli option to run balt

**Comment by jclark** [comment]
On point 1, I would like the subset number included in the balt name: eg `01-loops.balt`

On point 2, change front:loadModule so that it takes a list of lines and a filename (the filename in this case would be a fake filename giving the balt plus the starting line number of the test case).

On point 3:
- we won't have persistent .ll filenames, so I think we will have to stop checking in .ll files
- I want to make sure we preserve the Makefile's ability to do the minimum work after a change; the current Makefile has a lot of time invested in getting that working
- I also want to preserve the current Makefile's ability to run in parallel
- the expected output comes each bal file separately, so cli option to run the balt would need to produce both the .ll and the expected output
- probably should have one output directory per balt file

Let's discuss.

**Comment by jclark** [comment]
For Test-Case `output`, we should automatically add an `import ballerina/io;`. The conformance test suite is doing this. Later it will turn into `ballerinai/io`, which is a subset of `ballerina/io`.

**Comment by jclark** [comment]
I added an `07-type.balt` with two tests, but it's not working properly for me, because `make -f new.mk` with no changes causes it to rerun java.

```
mkdir -p out/01-int
make -C out/01-int -f ../../sub.mk tdir=01-int
make[1]: Entering directory '/mnt/c/Users/jjc/Documents/GitHub/nballerina/test/out/01-int'
rm -fr llnew
rm -fr expectnew
/usr/lib/ballerina/dependencies/jdk-11.0.8+10-jre/bin/java -jar ../../../compiler/target/bin/nballerina.jar --outDir llnew --expectOutDir expectnew ../../../compiler/testSuite/01-int.balt
mkdir -p ll
mkdir -p expect
../../update.sh expectnew expect txt
../../update.sh llnew ll ll
rm -fr llnew
rm -fr expectnew
make -f ../../sub.mk tdir=01-int testll
make[2]: Entering directory '/mnt/c/Users/jjc/Documents/GitHub/nballerina/test/out/01-int'
testll
make[2]: Leaving directory '/mnt/c/Users/jjc/Documents/GitHub/nballerina/test/out/01-int'
make[1]: Leaving directory '/mnt/c/Users/jjc/Documents/GitHub/nballerina/test/out/01-int'
mkdir -p out/07-type
make -C out/07-type -f ../../sub.mk tdir=07-type
make[1]: Entering directory '/mnt/c/Users/jjc/Documents/GitHub/nballerina/test/out/07-type'
rm -fr llnew
rm -fr expectnew
/usr/lib/ballerina/dependencies/jdk-11.0.8+10-jre/bin/java -jar ../../../compiler/target/bin/nballerina.jar --outDir llnew --expectOutDir expectnew ../../../compiler/testSuite/07-type.balt
mkdir -p ll
mkdir -p expect
../../update.sh expectnew expect txt
../../update.sh llnew ll ll
rm -fr llnew
rm -fr expectnew
make -f ../../sub.mk tdir=07-type testll
make[2]: Entering directory '/mnt/c/Users/jjc/Documents/GitHub/nballerina/test/out/07-type'
testll
make[2]: Leaving directory '/mnt/c/Users/jjc/Documents/GitHub/nballerina/test/out/07-type'
make[1]: Leaving directory '/mnt/c/Users/jjc/Documents/GitHub/nballerina/test/out/07-type'
```

When there are no changes, `new.mk` should simple recurse and then discover it has nothing to do.

**Comment by jclark** [comment]
It's creating an `out/07-type/out/` directory with a single `actual` directory. That doesn't seem clean to me.

**Comment by jclark** [comment]
We're now doing #419, but we'll keep the .balt stuff to work with the spec conformance work.
