### ISSUE TITLE
Add libbacktrace as third-party library

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#367]
To support backtraces, we should add libbacktrace as a third-party library using the process described in third-party/README.md

This is a prerequisite for #46

**Comment by manuranga** [comment]
The file are there now. @KavinduZoysa Please make any changes if needed, otherwise we can consider this done.

**Comment by KavinduZoysa** [comment]
Lets close this since the libbacktrace is merged to main.
