### ISSUE TITLE
Add runtime support for creating error values

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#376]
Add runtime function for creating an error value. Looks like this to start with:

```
TaggedPtr _bal_error_construct(TaggedPtr msg, int64_t lineNumber);
```

msg is a string.

Part of #167.

**Comment by jclark** [comment]
Also need the error:message lang lib function.

**Comment by jclark** [comment]
These should be in a new error.c file.

**Comment by jclark** [comment]
Define an ErrorPtr type in balrt.h and be able to print it out according to ToString spec.  Add some tests also.

**Comment by jclark** [comment]
Initially this will just contain the string with the message and the line number.  After you have finished this, you can enhance it to capture a snapshot of the stack (as part of #46).

**Comment by KavinduZoysa** [comment]
> Define an ErrorPtr type in balrt.h and be able to print it out according to ToString spec. Add some tests also.

@jclark, here is it mentioned testing the _B_io_println or create a method to get toString value and test it?
