### ISSUE TITLE
Run llvm_jni tests on GitHub action

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#378]
Run `gradle testBuild` in `llvm_jni` for each PR build to keep jni module in sync.

**Comment by manuranga** [comment]
I have added the changes for the GitHub action in above pr (#380). 

But I am not sure `gradle testBuild` is doing the correct thing, It seems to run all the compiler tests again. But I think we only need to generate ll files for VPO cases in testSuite, other tests have no effect from changing to llvm_jni. 

@heshanpadmasiri Are my observations correct? You may selectively run tests you need using `--tests` flag. eg `--tests "nballerina:testCompileVPO"`.

**Comment by heshanpadmasiri** [comment]
Yes currently it run all the test cases. I'll send a PR to update `gradle testBuild` to only run those test cases
