### ISSUE TITLE
Avoid undefined behavior for LLVM "sdiv" with RHS of 0 w/o explicit checks

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#38]
LLVM defines its sdiv instruction to have undefined behaviour when the right operand is zero. Similarly, when the left operand is INT_MIN and the right operand is -1.

One way to solve this is to generate code that explicitly tests for these cases before using the sdiv instruction. This issue is to investigate whether there is a better way.

At the assembly code level, at least for x86, we would ideally produce a x86 IDIV instruction. This would result in a CPU exception which would the OS would turn into a signal, which we can then catch. Is there a way to make LLVM generate this assembly, that is portable and supported?

Rust has the same semantics for integer division that we do, and uses LLVM, so we should look at how they do it.

We should also look at how Swift does integer division.

There are similar problems with remainder also.

**Comment by KavinduZoysa** [comment]
```
fn foo() -> i32 {
    return 0;
}

fn main() {
    let _x =  1/foo();
}
```

@jclark, I have generated the llvm IR for the above simple test case. In rust, they are doing the operand check before call `sdiv`. If RHS is 0, they call `panic()` function with file name, line number, column number and error message(In this case it is "attempt to divide by zero") as parameters. After that, the rest of the code is `unreachable`. Full llvm IR is available [here](https://github.com/KavinduZoysa/llvm/blob/master/panic_on_div.ll) and I have extracted the necessary information below only to represent.

```
define i32 @foo() {
start:
  ret i32 0
}

define void @main() {
start:
  %_2 = call i32 @foo()
  br label %bb1

bb1:                                              
  %_3 = icmp eq i32 %_2, 0
  %0 = call i1 @llvm.expect.i1(i1 %_3, i1 false)
  br i1 %0, label %panic, label %bb2

bb2:                                              
  %_x = sdiv i32 1, %_2
  ret void

panic:                                           
  call void @panic(@str.1, i64 25, @alloc24)
  ; @str.1 : the error message constant
  ; @alloc24 : a vector constant that contains file name, line num and col num
  unreachable
}
```

If we pass the flag to print the backtrace, it starts to unwind using their `backtrace_rs` lib. I am investigating more on this.

**Comment by jclark** [comment]
Can you also check for the overflow case (i.e. INT_MIN/-1)? Something like:

```
fn lhs() -> i32 {
    return std::i32::MIN;  
}

fn rhs() -> i32 {
    return -1;  
}

fn main() {
    let _x = lhs()/rhs();
}
```

**Comment by manuranga** [comment]
@KavinduZoysa can you please take a look at [@llvm.experimental.constrained.fdiv](https://llvm.org/docs/LangRef.html#llvm-experimental-constrained-fdiv-intrinsic) as well. It has the`"fpexcept.strict"` argument.

> If the exception behavior argument is “fpexcept.strict” all transformations must strictly preserve the floating-point exception semantics of the original code. Any FP exception that would have been raised by the original code must be raised by the transformed code, and the transformed code must not raise any FP exceptions that would not have been raised by the original code. This is the exception behavior argument that will be used if the code being compiled reads the FP exception status flags, but this mode can also be used with code that unmasks FP exceptions.

Sounds like what we are looking for.

**Comment by KavinduZoysa** [comment]
> Can you also check for the overflow case (i.e. INT_MIN/-1)? Something like:
> 
> ```
> fn lhs() -> i32 {
>     return std::i32::MIN;  
> }
> 
> fn rhs() -> i32 {
>     return -1;  
> }
> 
> fn main() {
>     let _x = lhs()/rhs();
> }
> ```

Yes, in this case also, LHS and RHS operands are check accordingly and call panic if result overflows. Please check below llvm IR.

```
; @str.1 : the error message constant (attempt to divide with overflow)
; @alloc28 : a vector constant that contains file name, line num and col num

define internal void @main() {
start:
  %_2 = call i32 @lhs()
  br label %bb1

bb1:                                              
  %_3 = call i32 @rhs()
  br label %bb2

bb2:                                             
  %_5 = icmp eq i32 %_3, -1
  %_6 = icmp eq i32 %_2, -2147483648
  %_7 = and i1 %_5, %_6
  %1 = call i1 @llvm.expect.i1(i1 %_7, i1 false)
  br i1 %1, label %panic, label %bb3

bb3:                                             
  %_x = sdiv i32 %_2, %_3
  ret void

panic:                                           
  call void @panic(@str.1, i64 31, @alloc28)
  unreachable
}
```

**Comment by jclark** [comment]
OK. Thanks. I think that means that our implementation needs to explicitly check its operands rather than relying on a CPU exception.

Can you also see how it handles the `%` case? We want INT_MIN/-1 to be 0. Not sure what Rust does here.

**Comment by KavinduZoysa** [comment]
@jclark, for the `%` case, rust is following the same pattern that is checking the operands and panicking. In `INT_MIN%-1` case, they are panicking with the error message `attempt to calculate the remainder with overflow`. But in our case, we can handle this case to return 0 without panicking.

**Comment by jclark** [comment]
OK, great. I think the conclusion is clear: we need to have explicit checks.  This feeds into #44.
