### ISSUE TITLE
Build libbacktrace as part of runtime build

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#390]
This follows on from #367.

libbacktrace uses autoconf as its build system, but we are not using (and don't want to use) autoconf.

We also don't want libbacktrace as a separate library: we want it as part of balrt.a. Furthermore, we want to make sure we get only as much as we need of libbacktrace in any build. For example, if we have a non-debug build without symbols, there is no point in including a pile of code in our binary that can interpret debug symbols.

Another important point is that, unlike libbacktrace, we are not trying to be portable to every obsolete Unix variant ever invented: we have a very limited range of systems that we need to be portable to.

This is a prerequisite to #6 and #46.

**Comment by jclark** [comment]
My suggestion would be to run configure on Ubuntu to generate config.h. Also do it on OS  X and see if there are any differences.  Then create our own config.h from this with appropriate #ifdefs. See how it builds and then write our own Makefile that does not build as a shared library. Check in both this config.h and our Makefile.

**Comment by KavinduZoysa** [comment]
@manuranga, can you please clone this repo https://github.com/ianlancetaylor/libbacktrace to your OS X machine and run the command `./configure`. This command will generate a config.h file. Please send that file.

**Comment by manuranga** [comment]
https://gist.github.com/manuranga/7d76846ffa699af8836f77f7f5a8b111
I have also attached a full diff of all the files that changed.

**Comment by KavinduZoysa** [comment]
@jclark, I have compared two config.h files and there are 4 differences.

I will write a new Makefile as you mentioned and that Makefile will generate relevant object files. Then in our runtime Makefile, I will archive them to balrt.a

This is an exact single command libbacktrace uses to generate object file.
`gcc -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=mmap.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c mmap.c -o mmap.o`

**Comment by jclark** [comment]
What are the 4 differences?

Can you run configure with options so that it uses clang rather than gcc as the compiler? Otherwise, you will need to look at each of these options and determine whether it is needed and if so what the corresponding clang flag is.

"-funwind-tables" may be important and we may need that for the rest of the runtime.

**Comment by KavinduZoysa** [comment]
> What are the 4 differences?
>

| macOS  | Ubuntu |
| ------------- | ------------- |
| #define BACKTRACE_ELF_SIZE unused  | #define BACKTRACE_ELF_SIZE 64  |
| not defined  | #define HAVE_DL_ITERATE_PHDR 1  |
| not defined  | #define HAVE_LINK_H 1 |
| #define HAVE_MACH_O_DYLD_H 1 | not defined |
 
> Can you run configure with options so that it uses clang rather than gcc as the compiler? Otherwise, you will need to look at each of these options and determine whether it is needed and if so what the corresponding clang flag is.
> 

Yes, after running configure for clang-11 the command is shown below. All the flags are available as GCC command.

`clang-11 -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=mmap.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c mmap.c -o mmap.o
`

**Comment by KavinduZoysa** [comment]
@manuranga, can you run the below command in your MacOS and paste the output here.
`clang-11 -x c /dev/null -dM -E`

**Comment by manuranga** [comment]
https://gist.github.com/manuranga/678f36f069d14cbd6c53e88da14d1ca0

**Comment by jclark** [comment]
This is useful

http://web.archive.org/web/20191012035921/http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#OSXiOSandDarwin

**Comment by jclark** [comment]
I would suggest at the beginning do:

```
#ifndef __APPLE__
#ifndef __linux__
#error Unsupported platform: only Linux and OS X supported for now
#endif
#endif

#ifdef __APPLE__
#ifndef __MACH__
#error Unsupported platform: APPLE but not MACH
#endif
#endif
```

Thereafter, just test using `__APPLE__` and `__linux__`.

**Comment by manuranga** [comment]
stranded output from running make on libbacktrace under macOS : https://gist.github.com/manuranga/116f39ed6c5147a7f206fb4ce790e7a5

**Comment by KavinduZoysa** [comment]
@manuranga, can you run below command and attach the log, it will give the clang related flags.

`./configure CC=clang-11 && make`

**Comment by manuranga** [comment]
Both diff and the log are [here](https://gist.github.com/manuranga/2fb31ff7c3d4ac4a2ce3f56c9343881a).
