### ISSUE TITLE
`simpleArrayMemberType` , `simpleMapMemberType` has repeated condition in If statement

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/nballerina#400]
**Description:**
simpleArrayMemberType, simpleMapMemberType functions in core.bal has a possible bug where there's repeated condition in If statement [bdd.right != false]
```
if bdd.left != true || bdd.right != false || bdd.right != false {
                    return ();
 }
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ushirask** [comment]
@jclark , @rdhananjaya

**Comment by jclark** [comment]
One `right` should be a `middle`.
