### ISSUE TITLE
Make `front:SourceFile` include `ScannedLine[]`

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#408]
This will enable:

- Provide columns in units of UTF-8 and UTF-16 code unit in addition to code points
- Support display of line in which error occurred with location highlighted (similar to clang)

(These things are not part of this issue.)

**Comment by jclark** [comment]
A Tokenizer will then be constructed just from a SourceFile. This means the construction of ScannedLines will happen up from rather than during tokenization.

**Comment by manuranga** [comment]
I plan to add `public function nextLine() returns ScannedLine?` to `SourceFile`.

**Comment by jclark** [comment]
SourceFile is readonly, so should be

```
function scannedLines() returns readonly & ScannedLine[]
```

and I don't think it needs to be public.
