### ISSUE TITLE
Extend CompareInsn to arrays

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#410]
If `T` is an ordered type, then `T[]` is an ordered type.

This is similar to #362.

Part of #328.

**Comment by jclark** [comment]
There's a front-end and back-end part to this.

**Comment by jclark** [comment]
Three parts:
- extend front:operandPairOrderType to bir:ArrayOrderType
- extend verifyCompare to deal with bir:ArrayOrderType
- extend nback:buildCompare to deal with arrays

**Comment by jclark** [comment]
If we use:

* -1 for UN
* 0 for LT
* 1 for EQ
* 2 for GT

then `x == LT || x == EQ` becomes `(unsigned)x <= 1` (using `icmp ule`), and `x == GT || x == EQ` becomes `x >= 1` (using `icmp sge`)

**Comment by heshanpadmasiri** [comment]
To the runtime I'm planning to add fallowing functions

1. `int compareTagged(TaggedPtr* lhs, TaggedPtr* rhs)` (I am using this instead of `compareArrays` because array elements can be `TaggedPtr` (including arrays) and I can call this recursively)

    - Inside this function first check if it is an array, and if so iterate over elements and compare by either calling it self or primitive comparisons
    - Else do the nil checks (which is currently done in [`buildCompareTagged`](https://github.com/ballerina-platform/nballerina/blob/fe7ae5c9f6266804b034bc00cd2f615406b389e1/compiler/modules/nback/build.bal#L1091)) and call the primitive comparisons after un-tagging
    - Change current  [`buildCompareTagged`](https://github.com/ballerina-platform/nballerina/blob/fe7ae5c9f6266804b034bc00cd2f615406b389e1/compiler/modules/nback/build.bal#L1091) to call this function and interpret result based on `bir:CompareInsn`.

2. Either a single primitive comparison function that takes two pointer for lhs and rhs in addition to function pointer for comparator or seperate comparision functions for int, float, boolean and string(Reuse the already implemented one). These primitive comparision functions will return an int as well (same meaning as compareTagged)

**Comment by jclark** [comment]
External functions in the runtime look like e.g. _bal_string_cmp

`*cmp` suffix should mean a function that returns -1/0/1.  We can then perhaps use `*compare` for returning -1/0/1/2.

For each of the following Ballerina, types there should be a runtime function

* int? - _bal_int_compare
* float? - _bal_float_compare
* string? - _bal_string_compare
* int?[] - bal_array_int_compare
* float?[] - bal_array_float_compare
* string?[] - bal_array_string_compare

In all of the above cases, the C function type would be  `int64_t compare(TaggedPtr, TaggedPtr)`. The last three can be implemented in terms of the first three via a function that takes the comparison as a parameter (either a function pointer or an integer).

**Comment by jclark** [comment]
I think I would pass TAG_INT/TAG_FLOAT/TAG_STRING to the function.

To make the inlining work, you will probably need an inline version e.g. taggedIntCompare, which is called by the external version _bal_int_compare (which would go in int_inline.c).

**Comment by jclark** [comment]
Do the runtime stuff as a separate pull request before you do the build.bal bit
