### ISSUE TITLE
Diff `test/ll` against produced ll via Makefile

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#430]
Remove `test/diff.sh` and do it via Makefile.
Output should just be a list of files instead of full diffs.

**Comment by manuranga** [comment]
Doing this in sub.mk produces too much noise, putting on root Makefile will be better.
I am planing the output to be like:
```
> make diff
out/cpmll/01-boolean/equal1-v.diff
out/cmpll/07-type/1-v.diff
```
I am **not** planing `make diff` to create the `ll` files if they don't exist.

**Comment by jclark** [comment]
Do you mean the second line of output to be a .diff file?

**Comment by manuranga** [comment]
Yes, corrected.

**Comment by manuranga** [comment]
One issue with the way I am doing diff (and update) is, when a test case gets removed from the working set, it doesn't show up as a change.
Is this something that needs fixing?

**Comment by jclark** [comment]
It would be very useful if make update removed .ll files whose .bal file no longer exists.
