### ISSUE TITLE
Support `check` and `checkpanic` in call statements

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#439]
In #406 we implemented `check` and `checkpanic` in expressions. We should also allow `check` and `checkpanic` before statements consisting of a function call or method call.

**Comment by manuranga** [comment]
According to spec `check check a();` is syntactically valid (even though it can't be semantically valid). I guess implementation should follow the same, even it might be easier to reject it in the parser itself.

**Comment by jclark** [comment]
`check check a();` is fine and should be accepted.

The spec does not say that e.g. `check 1` is an semantically invalid: it's just a no-op (like `+ 0`).

**Comment by manuranga** [comment]
I am also unsure about `check (a());` I think this should fail according to spec, but since `parsePrimaryExpr` doesn't make a distinction between that and `check a();`, it'll require some changes.

**Comment by jclark** [comment]
`check (a())` should fail
