### ISSUE TITLE
BIR parsing bug

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#44]
**Description:**
`typeTag` is not set for `PackagesCpInfo` at https://github.com/ballerina-platform/nballerina/blob/b2b985d473ac589aae90c53e92939aba651ccf92/BIR2llvmIR/BIRReader.cpp#L818
causing this block to be always skipped:
https://github.com/ballerina-platform/nballerina/blob/b2b985d473ac589aae90c53e92939aba651ccf92/BIR2llvmIR/BIRReader.cpp#L931 

**Suggested Labels:**
Bug

**Comment by shubhamnarlawar** [comment]
Thanks @ruvi-d for pointing it out. I have opened PR #46 for this bug.

**Comment by KavinduZoysa** [comment]
FIxed in https://github.com/ballerina-platform/nballerina/pull/46
