### ISSUE TITLE
Support full syntax for import declarations

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#443]
Subset 08 supports full syntax for import declarations.

This issue is to parse those declarations and built the AST.

Part of #438.

**Comment by jclark** [comment]
Please describe changes to ImportDecl here first.

**Comment by heshanpadmasiri** [comment]
I think we need to add fallowing to `ImportDecl`

- string import-prefix
    To deal with `import org/module-name as import-prefix`. In cases where explicit import-prefix is not given we can set this to the last identifier in module-name

I am not certain whether the fallowing information is needed for the rest of the compiler but I think it will be useful to locate the module that has been imported for things like type checking

- string[] names
    This will hold all the identifiers in module-name

**Comment by jclark** [comment]
I don't remember what we have at the moment, but we need

```
string? org;
string[] names;
string? prefix;
```
