### ISSUE TITLE
Count attribute values need to be checked

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#45]
**Description:**
In a few places where `count` attributes (e.g. `importCount`, `constCount` ) are being parsed, the read value is assumed to be zero and the next bits are read for parsing. A non-zero check needs to be done and if non-zero `readS4be()` needs to be called appropriately to advance the reader. 
https://github.com/ballerina-platform/nballerina/blob/b2b985d473ac589aae90c53e92939aba651ccf92/BIR2llvmIR/BIRReader.cpp#L950

**Suggested Labels:**
Bug, Low priority

**Comment by shubhamnarlawar** [comment]
importCount, constCount and typeDefinitionCount were `0` till now. Yes, We should handle them if they are non zero. I will send a PR for this bug.

**Comment by shubhamnarlawar** [comment]
@ruvi-d - Is import count refers to multiple packages present in a module?

Currently, there is only one package present per module.

**Comment by shubhamnarlawar** [comment]
Does simple assertions help here? Like - 

assert(importCount != 0);
assert(constCount != 0);
assert(typeDefinitionCount != 0);

In this way, if those count needs to be evaluated, then I can add the implementation for it.

Both ways are fine to me - 
1. Adding simple assertions
2. Loop the count and store it in BIRPackage

**Comment by ayonam** [comment]
Shubham,
    Actually here the assertions should be like assert(importCount ==
      0).  Because currently those counts are indeed zero and you want
      to know when they turn non-zero so that you can then add the
      further implementation.
    
    
    
    On 20/01/21 23:50, shubhamnarlawar
      wrote:
    
    
      
      Does simple assertions help here? Like -
      assert(importCount != 0);
        assert(constCount != 0);
        assert(typeDefinitionCount != 0);
      In this way, if those count needs to be evaluated, then I can
        add the implementation for it.
      Both ways are fine to me -
      
        Adding simple assertions
        Loop the count and store it in BIRPackage
      
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/issues/45#issuecomment-763839990",
"url": "https://github.com/ballerina-platform/nballerina/issues/45#issuecomment-763839990",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ruvi-d** [comment]
Assert with a `TODO` comment would be my preference

**Comment by shubhamnarlawar** [comment]
Addressed in #297
