### ISSUE TITLE
Parenthesized method call expr should not parse as a statement

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#466]
The parser accepts

```
(v.push(48));
```

but should not.

[Spec](https://ballerina.io/spec/lang/2021R1/#call-stmt) doesn't allow parentheses around method call statements.

When fixed enable [call1-fe.bal](https://github.com/ballerina-platform/nballerina/blob/7f74a271fb4b9292ce297711f51c715e0cda0a92/compiler/testSuite/future/call1-fe.bal)

**Comment by jclark** [comment]
I think this can be fixed by changing parseMethodCall to

1. call startPrimaryExpr
2. give an error if the current token is not "[" or "."
3. call finishPrimaryExpr
4. give an error of we didn't get a MethodCallExpr
