### ISSUE TITLE
Implement `string:Char` type 

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/nballerina#477]
**Description:**
For the moment, we should be able to parse `string:Char` as we have done for `int` subtypes.
Need to figure out how to represent this within `StringSubtype`.

On top of my mind we should be able to do:
```ballerina
type StringSubtype StringSubtypeData|STRING_CHAR;

const string STRING_CHAR = "char";

type StringSubtypeData readonly & record {|
    boolean allowed;
    string[] values;
|};
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rdhananjaya** [comment]
@jclark what do you think about the above approach?

**Comment by manuranga** [comment]
I think we should be able to represent `!string:Char` as well. But `STRING_CHAR` can't  be a `boolean`, because it already has a separate meaning (ie: all of string, non of string).

**Comment by rdhananjaya** [comment]
@manuranga thanks, I forgot about that, I think we can do `type StringSubtype StringSubtypeData|STRING_CHAR|STRING_NOT_CHAR`.

I'm failing to come up with how the `diff` function should work.

```ballerina
type T "A";
```

What should `diff(T, string:char)` be? And this should extend for `!T`.

**Comment by jclark** [comment]
The representation is wrong. You need to come up with a way of describing sets of values including string:Char that is closed under diff, union and intersection. So you need a representation that can describe e.g. string:Char|"foo" or string:Char & !"x".

**Comment by jclark** [comment]
At the moment, we can represent

- a specified set of strings
- any string other than a specified set of strings

string:Char requires that we also be able to represent at least:

- a specified (possibly empty) set of strings (not of length 1) or a string of length 1
- any string of length 1 other than a specified (possibly empty) set of strings (of length 1)
- any string other than a specified set of strings that is not of length 1

Are there others? You can tell by doing diff/union/intersection on these and see if you get any others.

**Comment by jclark** [comment]
There's another more complex case, which is something like `"foo"|"bar"|(string:Char & !("x"|"y"))`.

**Comment by jclark** [comment]
I suggest

```
type StringSubtype readonly & record {|
    CharStringSubtype char;
    NonCharStringSubtype nonChar;
|};

type CharStringSubtype readonly & record {|
    boolean allowed:
    string:Char[] values;
|};

type NonCharStringSubtype readonly & record {|
    boolean allowed;
    string[] values;
|};
```
