### ISSUE TITLE
Importing the root module result in an error

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#490]
Importing the root module from another module gives `error: unsupported module 'root'` error of type `Unimplemented`.

There shouldn't be an error, even though this is not useful in the current subset because there is no way to refer to it without creating a circular import.

**Comment by jclark** [comment]
Just need to fix resolveImport in compile.bal to do `if id == DEFAULT_ROOT_MODULE_ID { return IMPORT_CYCLE_ERROR; }`

**Comment by manuranga** [comment]
Can a different package import a submodule directly ? In that case, it won't be a cycle. So I though, this should be handled in a way that dosn't specal-case root.

**Comment by jclark** [comment]
We're not doing that in this subset: cross that bridge when we come to it.
