### ISSUE TITLE
Allow a variable declaration to use `_`

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#492]
Allow `_` in a variable declaration to support the idiom described here: https://github.com/ballerina-platform/ballerina-spec/issues/887#issuecomment-902334830

_Originally posted by @jclark in https://github.com/ballerina-platform/nballerina/issues/356#issuecomment-905958650_

Follow on from #356

**Comment by KavinduZoysa** [comment]
Since this feature belongs to the `local-init-var-decl-stmt` and wildcard is a binding-pattern under typed-binding-pattern, I suggest to model this in AST as shown below. 

```
public const WILDCARD = "_";

public type VarDeclStmt record {|
    TypeDesc td;
    string|WILDCARD varName;
    Expr initExpr;
    boolean isFinal;
|};

```
@jclark WDYT?

**Comment by jclark** [comment]
Doesn't work because WILDCARD is a subtype of string.

**Comment by KavinduZoysa** [comment]
We can keep the wildcard as a separate field in `VarDeclStmt` as shown below.
```
public type VarDeclStmt record {|
    TypeDesc td;
    string? varName = ();
    boolean wildcard = false;
    Expr initExpr;
    boolean isFinal;
|};
```

Or we can create a separate node for this as shown below.

```
public type WildcardDeclStmt record {|
    TypeDesc td;
    Expr initExpr;
|};
```

I prefer to use the second approach because it will be more clear to model this outside the `VarDeclStmt`. 
@jclark, can you please check and comment on this?

**Comment by manuranga** [comment]
In the first options you don't need a separate boolean, since `varName = ()` already imply wildcard.

**Comment by jclark** [comment]
We should have an approach where wildcard binding pattern is handled consistently in an AssignStmt and in a VarDeclStmt.

@manuranga it would be useful learning exercise for @KavinduZoysa to figure this one out himself...

**Comment by KavinduZoysa** [comment]
I suggest to change both AssignStmt and VarDeclStmt as shown below. We can represent wildcard-binding-pattern when lValue or varName is nil.

```
public type AssignStmt record {|
    *PositionFields;
    LExpr? lValue = ();
    Expr expr;
|};

public type VarDeclStmt record {|
    *PositionFields;
    TypeDesc td;
    string? varName = ();
    Expr initExpr;
    boolean isFinal;
|};
```
@jclark, @manuranga WDYT?

**Comment by jclark** [comment]
```
const WILDCARD = ();
```
