### ISSUE TITLE
Add LLVM module support for aliases

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#494]
When implementing #402, we are going to want to be able to have two names for the same global data.

We can do this using aliases:

https://llvm.org/docs/LangRef.html#aliases

**Comment by heshanpadmasiri** [comment]
@jclark  for this I am planning to add `addAlias(Type aliasTy, ConstValue aliasee, string? Name=()) returns ConstValue` to module (corresponds to [LLVMAddAlias](https://llvm.org/doxygen/group__LLVMCoreValueConstantGlobalAlias.html#gaa424cbdf2fb15653fdd64a5995664ff4)) If we are to set the optional fields such as linkage, PreemptionSpecifier, etc. I think the best way is to add a `AliasProperties` record (similar to `GlobalProperties`) and accept it as an argument in `addAlias`

**Comment by jclark** [comment]
Can we make AliasProperties be the same as GlobalProperties?

**Comment by heshanpadmasiri** [comment]
> Can we make AliasProperties be the same as GlobalProperties?

GlobalProperties have fields that don't apply for alias like `align`, `isConstant`, etc. We can of course ignore such fields and just use the ones that apply to alias.

**Comment by heshanpadmasiri** [comment]
> @jclark for this I am planning to add `addAlias(Type aliasTy, ConstValue aliasee, string? Name=()) returns ConstValue` to module (corresponds to [LLVMAddAlias](https://llvm.org/doxygen/group__LLVMCoreValueConstantGlobalAlias.html#gaa424cbdf2fb15653fdd64a5995664ff4)) If we are to set the optional fields such as linkage, PreemptionSpecifier, etc. I think the best way is to add a `AliasProperties` record (similar to `GlobalProperties`) and accept it as an argument in `addAlias`

For the alias type c api expects a pointerType. For example in the fallowing
```
@0 = alias i64, i64* @g
```
first i64 (not i64*) comes from the alias type of i64 pointer. So I persume our api should change to `addAlias(PointerType aliasTy, ConstValue aliasee, string? Name=()) returns ConstPointerValue`

**Comment by jclark** [comment]
> GlobalProperties have fields that don't apply for alias like `align`, `isConstant`, etc. We can of course ignore such fields and just use the ones that apply to alias.

Sounds like properties of the symbol vs the definition. So then we should have a record type (e.g. GlobalSymbolProperties)  used by addAlias and then GlobalProperties should include GlobalSymbolProperties.

BTW addGlobal should clone the props argument.

**Comment by jclark** [comment]
> For example in the fallowing
> 
> ```
> @0 = alias i64, i64* @g
> ```
> 
> first i64 (not i64*) comes from the alias type of i64 pointer.

Not sure I understand.  Can you use an example where only one of the types uses i64?

I would expect the first arg to be the same type as occurs immediately after `alias` in the IR.

Shouldn't it be `string name` (as with addGlobal) not `string? name`?

**Comment by heshanpadmasiri** [comment]
> > For example in the fallowing
> > ```
> > @0 = alias i64, i64* @g
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > first i64 (not i64*) comes from the alias type of i64 pointer.
> 
> Not sure I understand. Can you use an example where only one of the types uses i64?
> 
> I would expect the first arg to be the same type as occurs immediately after `alias` in the IR.
> 
> Shouldn't it be `string name` (as with addGlobal) not `string? name`?

If you have a global variable `g` defined with type at `i64`. Then you can pass to the aliasTy argument pointer type of i32 (It must be a pointer type) and get the fallowing.
```
@g = external global i64

@0 = alias i32, i64* @g
```
You can set the name to be an empty string and have the llvm generate names. But I am not sure whether this is desirable or useful for our application

**Comment by jclark** [comment]
Can we make the type be i32 in our API for uniformity with addGlobal?

How is this going to work with non-zero address spaces?

I think name should be required (as with addGlobal).

**Comment by heshanpadmasiri** [comment]
> Can we make the type be i32 in our API for uniformity with addGlobal?
> 
> How is this going to work with non-zero address spaces?
> 
> I think name should be required (as with addGlobal).

I'll make the type non-pointer type (i32 instead of i32*) and make the name required. It respects the address spaces for example c api will generate code like this when we have non-zero address spaces.
```
@g = external addrspace(2) global i64

@0 = alias i32, i64 addrspace(2)* @g

define i64 @test() {
  %1 = load i32, i32 addrspace(1)* @0, align 4
  ret i32 %1
}
```
