### ISSUE TITLE
Improve semtypes testing

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#499]
Need to improve both tests and test framework.

**Comment by ushirask** [comment]
Need to implement a better representation for expected relationships of the types. 
If S is a proper subtype of T represent by `// @type S < T`
If S and T are equivalent types represent by `// @type S = T`
If neither S or T are a subtype of the other `// @type S <> T`

Ex: -
```
// @type One < int
type One 1;
```
```
// @type X = int 
type X int|never;
```

**Comment by jclark** [comment]
This can be implemented in compiler/tests/testSuite.bal.
