### ISSUE TITLE
Implement fixed length array types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#502]
Logically equivalent to a tuple.

**Comment by jclark** [comment]
At the moment we have:

```
public type ListAtomicType readonly & record {|
    SemType[] members;
    SemType rest;
|};
```

The semantics is that after `members`, you can repeat `rest` 0 or more times. We would extend this to provide field(s) that say how many times `rest` is to be repeated e.g.

```
  // if non-nil, rest must be repeated exactly restCount times
  int? restCount;
```

We have to figure out what we need so that the functions in list.bal all work out.

**Comment by jclark** [comment]
Alternative idea

```
   (SemType[]|[SemType,int]) members;
```

**Comment by jclark** [comment]
We should normalize tuples into this representation where possible i.e. `[int, int]` should produce the same ListAtomicType as `int[2]`. `T[0]` should be normalized into an empty `SemType[]`.

**Comment by jclark** [comment]
Using a tuple `[Semtype, int]` won't work because a SemType can be a UniformTypeBitSet which is an int. So it would need to be a record instead e.g.

```
record {|
   SemType repeated;
   int count;
|}
```

**Comment by jclark** [comment]
As part of this, we should add a function `listAtomicTypeIsArray` which we can use where the code now does `x.members.length() == 0`.

**Comment by jclark** [comment]
I still feel a bit uneasy about this representation. It is allowing us a `rest` part as well as the fixed length array part, which is more than what we need.

I also suspect it's going to make the logic in list.bal rather awkward.

**Comment by jclark** [comment]
Would something like this work better for list.bal?

```
public type ListAtomicType readonly & record {|
    SemType[] members;
    record {|
       SemType semType;
       int? fixedCount;
    |}? repeated;
|};
```

**Comment by jclark** [comment]
Or maybe this:

```
public type ListAtomicType readonly & record {|
    SemType[] members;
    // repeat the last member of SemType this number of times more
    // must be zero, if members is empty
    int repeatLastMember;
    SemType rest;
|};
```

So `int[5]` would turn into `{ members: [INT], repeatLastMember: 4, rest: NEVER }`.

Then:

- replace `members.length()` by `members.length() + repeatLastMember`
- replace `members[i]` by `members[int:max(i, members.length() - 1]`

Testing for an array then remains just testing `members.length() == 0`.

@rdhananjaya My gut feeling is that this representation will work better.

**Comment by manuranga** [comment]
Are we maintaining the invariant that `repeatLastMember` is always maximal possible value?

**Comment by jclark** [comment]
We need to deal with the conclusion of https://github.com/ballerina-platform/ballerina-spec/issues/1001

This means the AST needs to have multiple dimensions for an array, and resolveTypes needs to reorder them.

@rdhananjaya We can either handle this in the same pull request or do it in a follow-on.
