### ISSUE TITLE
A reference to a type equivalent to `never` should be rejected in subset 8

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#506]
This
```ballerina
type Never string & int;
function foo(Never t) {
}
```

gets an internal error. It should get an unimplemented error.

**Comment by jclark** [comment]
That sort of check would stop `--showTypes` working. The way it is intended to work is that any type that is referenced in a function must be equivalent to a type that can be specified in the grammar.

**Comment by jclark** [comment]
This should get an unimplemented error in resolveSubsetTypeDesc.

It needs to add `&& ty != t:NEVER`.
