### ISSUE TITLE
BIR verification should limit where widening can occur

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#508]
BIR verification should limit where widening can occur to be consistent with https://github.com/ballerina-platform/nballerina/issues/204#issuecomment-917780707

This means that in several cases it needs to switch from checking for a subtype relationship to checking for an equivalence relationship.  

Equivalence between two subtypes should be tested by first using `==` on the SemType and then, if that fails, by checking whether each is a subtype of the other.

**Comment by manuranga** [comment]
I am wondering how to test this.

**Comment by manuranga** [comment]
Reopening to address [#590 (comment)](https://github.com/ballerina-platform/nballerina/pull/590#issuecomment-947266369).
