### ISSUE TITLE
Implement field access lvalues

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#510]
This is x.y.z on the LHS of an assignment or compound assignment statement.

https://ballerina.io/spec/lang/2021R1/#field-access-lvexpr

**Comment by manuranga** [comment]
@jclark
​​In the current subset, record fields can only be (unions of) basic types. So valid filed access lvalues will only be in the form `x.y` not `x.y.z`. Therefore I should keep `FieldAccessLExpr` as is, instead generalizing `mapping`. Is this understanding correct?

**Comment by jclark** [comment]
Correct.  We will generalize lvalues when we support arbitrary member types for structures.
