### ISSUE TITLE
Create an initialization module for each program

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#511]
Currently, we create an LLVM module for each Ballerina module. With this issue, we will create an additional initialization module.

This module will be responsible for defining the program's main function, which will have a fixed name like `_bal_main`, and is called by C `main` function. This will call the user-defined main function in the root module, whose name depends on the name of root module (call this the "user main"). This will allow us to fix #456.

The initialization module will expand to deal with other things (which will be separate issues):
 * initialize every module in the program #512
 * process command-line arguments, turning the OS-provided arguments into the form expected by the user main
 * deal with possibility that LLVM return type of user main may be void or a tagged ptr
 * provide data structures the the program modules need for performing runtime type-checking #402 
 
For a root module `foo.bal` we will generate the initialization module into `foo._init.ll`. (We should implement #444 to ensure this cannot clash with a user module name.) The testing Makefile needs to deal with this.

nback will export a function that builds an initialization module, which will be called by compile.bal. The parameters to that will include
- a list of the module ids of all the programs modules, in the order in which the modules should be initialized (or the reverse of that)
- the ModuleExports for the root module (so that we know how to call main)

This is a prerequisite for #495.

**Comment by jclark** [comment]
This should be in a separate file (e.g. `init.bal`).

**Comment by manuranga** [comment]
> the ModuleExports for the root module (so that we know how to call main)

Instead passing all the exports, I propose modifying `validMain` to return a `bir:FunctionSignature` and passing that.

**Comment by jclark** [comment]
> > the ModuleExports for the root module (so that we know how to call main)
> 
> Instead passing all the exports, I propose modifying `validMain` to return a `bir:FunctionSignature` and passing that.

Please don't do that. Eventually we will want startup code to be able call public functions other than `main` in the root module.

compileBalFile can get the ModuleExports from ResolvedModule without any interface change required.

**Comment by manuranga** [comment]
`ExportedDefn` is defined in `front`, importing in form `back` felt wrong. Should I move it to `bir`?

**Comment by jclark** [comment]
That's a good point. How about passing a `map<bir:FunctionSignature>` (extracted from ModuleExports) to nback, since we only care about public _functions_?
