### ISSUE TITLE
Add positions to AST nodes

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#513]
Every AST node should have a Position for its start and its end. The start position should be the start of the first token that is part of what it represents; the end position should be the end of the last token that is part of what it represents.

This can be done with startPos, endPos fields in the AST nodes.

**Comment by jclark** [comment]
We can split AST nodes into groups
1. Top-level declarations: ModuleLevelDefn and ImportDecl
2. Statements
3. Expressions
4. Type descriptors

Let's do each of these in a separate pull request, starting with ModuleLevelDefns.

**Comment by jclark** [comment]
For ModuleLevelDefn, the existing pos should be renamed to namePos and should correspond to the start of the name being defined by the defn.

**Comment by jclark** [comment]
Create a record type

```
type PositionFields record {|
   Position startPos;
   Position endPos;
|};
```

And then use `*PositionFields;` to include it in AST nodes.

**Comment by jclark** [comment]
We also need to come up with a good test strategy.  For group 1: everything other than whitespace or comments should be within exactly one top-level defn.  I think you will need to write code that maps from a Position onto an index of a fragment within a ScannedLine (you have to count the length of each fragment).

Do top-level defns first; then come up the testing strategy.

**Comment by jclark** [comment]
I think we will need a test function: 

```
function testIsWhitespace(SourceFile file, Position startPos, Position endPos) returns boolean
```

that tests whether all fragments between startPos and endPos are whitespace (e.g. FRAG_WHITESPACE or FRAG_COMMENT).

**Comment by heshanpadmasiri** [comment]
I have a suggestion for a possible test strategy for general case

1. We extend the tokenizer so that we can move forward it up to a given position
2. We'll use 1 to seek the tokenizer forward up to start position 
3. Then call the parser function for the given node (ex:`TypeDefn` -> `parseTypeDefinition`)
4. If the start position is wrong parser will fail
5. Else after the parser function we look at the tokenizer's current position and see if that is same as the end position for the ast node

**Comment by heshanpadmasiri** [comment]
@jclark for the line ([testcase](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/05-const/2-v.bal))
```
const N1 = 100;
```
I am getting fragcodes as `[135, 0, 3, 0, 61, 0, 4, 59]` (with fragments being `[" ",  "N1",  " ", " ", "100"]`) is this the expected behavior. (problem being fragcodes having FRAG_WHITESPACE(0))

**Comment by jclark** [comment]
Looks like what I would expect. You don't get a fragment for any FragCode that always has the same string. So `const`, `=` and `;` won't have a fragment associated with them, and everything else will.  The idea is that you can reconstruct the exact original line from the ScannedLine.

What is it that doesn't look right to you?

**Comment by jclark** [comment]
@heshanpadmasiri One difficulty I see is how to set the right mode (MODE_NORMAL vs MODE_TYPE_DESC); but perhaps you can deduce from the kind of AST node.

It will be useful functionality to be able to set the Tokenizer to a particular Position.  It requires some care to implement correctly. Probably we restrict it initially to a position between tokens. We could use this to replace saving the TokenizerState in ScannedModulePart.

**Comment by heshanpadmasiri** [comment]
> Looks like what I would expect. You don't get a fragment for any FragCode that always has the same string. So `const`, `=` and `;` won't have a fragment associated with them, and everything else will. The idea is that you can reconstruct the exact original line from the ScannedLine.
> 
> What is it that doesn't look right to you?

It's a `ModuleLevelDefn` with white spaces. I thought they were suppose to be free of white spaces. Are we trying to test everything not covered by the Top-level declarations with `testIsWhitespace` or everything that is a Top-level declaration

**Comment by jclark** [comment]
Test that everything that is not within a top-level definition (including ImportDecl) is whitespace. Something is within a top-level definition if it is between the startPos and endPos of that definition.

Also test that the startPos/endPos of top-level definitions do not overlap.

**Comment by jclark** [comment]
We should also check that whitespace is in the right place: startPos should not be the start position of a whitespace token; endPos should not be the end position of a whitespace token.

**Comment by jclark** [comment]
@heshanpadmasiri Please think about #538 while you are doing this (and perhaps start to do it also).
