### ISSUE TITLE
Implement xml subtypes in types module

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#526]
The types module supports the `xml` type. This adds support for xml subtypes.

**Comment by jclark** [comment]
There's some material in [NOTES](https://github.com/ballerina-platform/nballerina/blob/main/compiler/modules/types/NOTES.md#xml)

**Comment by jclark** [comment]
Assuming the representation proposed in the notes, the difficult part is to write the isEmpty function on the BDD. On any path, you can intersect all the positive ones to give you a single bit vector (call this P). You then have to test whether all the negated atoms on the path makes this empty. I think this only happens if there is an N such that P <: N.

**Comment by rdhananjaya** [comment]
From [NOTES](https://github.com/ballerina-platform/nballerina/blob/main/compiler/modules/types/NOTES.md#xml)

> - a flag saying whether the empty sequence is allowed
> - a bit vector with one bit for each of the 7 singleton subtypes, saying whether a singleton of that type is allowed
> - a Bdd for the concatenation of two or more items, where the atom is the bit vector for the singleton subtypes

If we have a bit for `nil` and a flag to say if this is a sequence or a singleton, then whether the empty sequence is allowed is inferable from the type alone, right? 

`xml<xml:Element>` can't have an empty sequence, whereas `xml<xml:Text>` and `xml<never>` can.

**Comment by jclark** [comment]
Remember we have to design this in a way that is closed under intersection/union/difference. So "a flag to say if this is a sequence or singleton" won't work.

The idea is to partition the set of xml values into 3 disjoint sets:

- the empty sequence
- sequences of length 1
- sequences of length > 1

Then we have a representation of each of these 3 parts. So...

`xml<never>` contains just the empty sequence

`xml<xml:Element>` contains

- the empty sequence
- a length 1 sequence if it is of type Element
- length > 1 sequence if all its constituents are of type Element

xml:Text is a bit special since it means either an xml:Text singleton or the empty sequence. So xml:Text contains

- the empty sequence
- a length 1 sequence if it is of type Text
- no sequences of length > 1

`xml:Text & !xml<never>` would consist of

- a length 1 sequence if it is of type Text
- no sequences of length > 1

and not the empty sequence.

`xml<xml:Text>` contains

- the empty sequence
- a length 1 sequence if it is of type Text
- length > 1 sequence if all its constituents are of type Text

**Comment by jclark** [comment]
There's also some complexity between mutable and immutable subtypes. This works rather differently from lists/mappings where the list/mapping is either immutable or not. Here it's the XML singleton (element/comment/processing instruction) that is mutable or not. (This is a bit like the situation with readonly record fields.)

**Comment by jclark** [comment]
Thinking in terms of values: an xml value has its readonly bit set if and only if the readonly bit of each of its constituent singletons is set. A value of xml basic type is in XML_RO uniform type if its readonly bit is set and otherwise is in XML_RW.

So for XML_RO, the subtypes must exclude mutable singletons (i.e. we mask out the mutable types from the bit vector). This is easy.

Similarly XML_RW must exclude subtypes that cannot include a mutable singleton:

1. empty sequence is not allowed
2. singleton sequence must exclude immutable singletons
3. length > 2 sequences must allow a mutable singleton

The difficult one is case 3: we need to treat the BDD as empty if it does not allow a mutable singleton. We can intersect all the positive atoms on a path to give us a bit vector. If this doesn't include any mutable singletons, then it's empty. If any of the negated atoms removes all the mutable singleton types from that intersection, then it's empty. Is that sufficient?

**Comment by jclark** [comment]
@rdhananjaya For the xml type to fit in with how we have done readonly, we need to split the description of a set of xml values into two independent parts:

1. a description of a set of xml values that are readonly
2. a description of a set of xml values that are not readonly

For each of these two descriptions, we need to be able independently to perform union/diff/intersection and to determine emptiness.

**Comment by rdhananjaya** [comment]
```ballerina
public type XmlSubtype readonly & record {|
    XmlRoData ro;
    XmlRwData rw;
|};

public type XmlRoData readonly & record {|
    boolean hasEmpty;
    int singleton;
    BddNode? sequence;
|};

public type XmlRwData readonly & record {|
    int singleton;
    BddNode? sequence;
|};

const int TEXT = 1;
const int ELEM_RO = 1 << 1;
const int PI_RO = 1 << 2;
const int COMMENT_RO = 1 << 3;
const int ELEM_RW = 1 << 4;
const int PI_RW = 1 << 5;
const int COMMENT_RW = 1 << 6;
type XmlSingletonUT TEXT|ELEM_RO|ELEM_RW|PI_RO|PI_RW|COMMENT_RO|COMMENT_RW;

const int XML_RO_MASK = TEXT | ELEM_RO | PI_RO | COMMENT_RO;
const int XML_RW_MASK = ELEM_RW | PI_RW | COMMENT_RW;

// These functions are for resolving types
function xmlSingleton(XmlSingletonUT xmlUT) returns SemType {
    int roBitset = xmlUT & XML_RO_MASK;
    int rwBitset =  xmlUT & XML_RW_MASK;
    XmlSubtype st = {
        ro: {
            hasEmpty: false,
            singleton: roBitset,
            sequence: () 
        }, 
        rw: {
            singleton:rwBitset,
            sequence: () 
        }
    };
    UniformTypeCode typeCode = rwBitset == 0 ? UT_XML_RO : UT_XML_RW;
    return uniformSubtype(typeCode, st);
}

public function xmlSequence(SemType[] constraints) returns SemType {
    int roBitset = 0;
    int rwBitset = 0;
    foreach SemType st in constraints {
        XmlSubtype t = <XmlSubtype> (<ComplexSemType> st).subtypeDataList[0];
        roBitset |= t.ro.singleton;
        rwBitset |= t.rw.singleton;
    }

    XmlSubtype st = {
        ro: {
            hasEmpty: true,
            singleton: 0,
            sequence: { atom: roBitset, left: true, middle: false, right: false }
        }, 
        rw: {
            singleton: 0,
            sequence: { atom: rwBitset, left: true, middle: false, right: false }
        }
    };
    UniformTypeCode typeCode = rwBitset == 0 ? UT_XML_RO : UT_XML_RW;
    return uniformSubtype(typeCode, st);
}
```

@jclark @manuranga what do you think?

**Comment by jclark** [comment]
I can provide detailed comments with a pull request, but this is in the right direction.

I suspect it will be less code if you make XmlRwData and XmlRoData be the same record type. I also think it will be simpler to do empty as an additional flag in singleton (and rename accordingly).

BddNode? should be Bdd (with the usual convention that true means everything and false means nothing).

**Comment by rdhananjaya** [comment]
Thanks for the input, will proceed with the proposed changes.

The idea I had to reuse the logic was to have another super type used for common code `record { int singleton; BddNode? sequence; }`, this is the parameter type for common functions, accepting either `XmlRoData` or `XmlRwData`.

**Comment by jclark** [comment]
> The idea I had to reuse the logic was to have another super type used for common code `record { int singleton; BddNode? sequence; }`, this is the parameter type for common functions, accepting either `XmlRoData` or `XmlRwData`.

It's going to be much simpler to put hasEmpty as a flag in singleton and use the exact same type.

`xmlSequence` is not the right function. `xml<T>` is a type operator on a **single** type, which must be a subtype of `xml`. Unions inside `T` are normal unions. So xml.bal should provide

```
function xmlSequence(SemType constituentType) returns SemType;
```

Precondition for this is that constituentType is a subtype of `xml`.

**Comment by jclark** [comment]
You need a function that creates a SemType from a XmlRoData/XmlRwData pair recognizing the case when either member of the pair is equivalent to all or none of the uniform type. This would be analogous to createStringSubtype.
