### ISSUE TITLE
Migrate to jBallerina swan lake beta3

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#548]
Migrate to jBallerina swan lake beta3, available at https://github.com/ballerina-platform/ballerina-distribution/releases/tag/vswan-lake-beta3

**Comment by manuranga** [comment]
Word `linux` is dropped form the zip file name for some reason, but not the `windows`, need update OS picking for this.

**Comment by jclark** [comment]
When it's available on ballerina.io, the documentation should be updated to require it.

We should also remove JBUGs that are not longer necessary.

**Comment by manuranga** [comment]
jre has been removed form the linux zip, I'll have to use deb file.

**Comment by manuranga** [comment]
I think with beta 3, we are expected to commit the `Dependencies.toml` file.

**Comment by jclark** [comment]
Why do we need to commit `Dependencies.toml`? What will happen if we don't?

**Comment by manuranga** [comment]
It will just create a new one on `bal build`, so everyone will have their own copy of it. But as far as I understand, the purpose of this file is to be committed so there will be a single copy of it specifying the exact dependencies for the project, at any given time (commit).

**Comment by jclark** [comment]
So effectively it would be locking our dependencies? I see no need for us to do this at this point.

**Comment by jclark** [comment]
This issue can wait until beta3 is up on ballerina.io and available via `bal dist pull`.

**Comment by manuranga** [comment]
I started this since #547 was failing due to method too large on beta 2 which is fixed in beta 3. I'll split the method for now.

**Comment by manuranga** [comment]
Updated the pr #552. 
What's left to do is to update the nightly build and to revert the large method `testParser`.
I don't think documentation needs any updating since it says to uses the latest form the ballerina.io.

**Comment by sameerajayasoma** [comment]
@manuranga @jclark It is not mandatory to commit the generated `Dependencies.toml` file. Also, the existence of this file does not mean that the dependency versions are locked. 

If you run the `bal build` with `--sticky` option, then we use the `Dependencies.toml` as a lock file, otherwise, we use this file as an aid to perform compatible version updates. 

We generally recommend committing the `Dependencies.toml` file, because it stops you from getting incompatible version updates.

**Comment by jclark** [comment]
@sameerajayasoma Thanks for the explanation. At this stage, I prefer to get incompatible version updates as soon as possible, so we can fix our code. (Plus we have very few external dependencies, so this is unlikely to be much of a problem for us.) When we get further along, we can commit `Dependencies.toml`.

**Comment by manuranga** [comment]
Looks like jBallerina nightly doesn't produce a deb file, so we'll keep using the zip. I only updated the the action to use the correct JRE #584.

@keizer619 mentioned we are shipping a patched version of Java now. Hope above way of getting it works. Please verify and re-open if this is not the case.

Also reverted the large method in testParser. Please close without merging if this is unnecessary #585.
