### ISSUE TITLE
Need semtype testing strategy for set difference/complement

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#551]
Conditional type narrowing gives rise to semtypes that have use set difference (or equivalently complement/negation). We need a way to be able to test subtype relationships and projection with types that use set difference.

One possibility is to implement a `!` type operator. Is there another way?

**Comment by manuranga** [comment]
Another option is to extended assertion grammar.

Currently planned grammar is:
```
type-projection := identifier ("[" number "]")?
type-assertion := type-projection("<"|"="|"<>") type-projection
```

We could extend it to support something like
```
// @test T = S - R
```
Or 
```
// @test T < S & !R
```

**Comment by jclark** [comment]
We need to be able to test the projection of a difference, which would require something like

```
// @test (S - T)[1] = R
```

That feels too complicated to me.

**Comment by jclark** [comment]
With #623 we can just support a not `!` when we are testing types.
