### ISSUE TITLE
 Make operations on list values go through function pointers in the descriptor

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#583]
This is a prerequisite to #329. Follows on from #582.

**Comment by jclark** [comment]
I suggest we handle filler value by have a create_filler_value function in the descriptor (rather than having the filler value itself in the descriptor): this is so it will work for records where we have to create a new filler value.

**Comment by manuranga** [comment]
I think set/get operations should look like below
```C
typedef struct {
    TaggedPtr (*get)(TaggedPtr lp, int64_t index);
    PanicCode (*set)(TaggedPtr lp, int64_t index, TaggedPtr val);
    uint32_t bitSet;
} ListDesc, *ListDescPtr;
```

I may also need to have `bool (*contains)(TypeTestPtr ttp)`.


I didn't understand why `create_filler_value` should be in the descriptor yet. I assume it should have a signature like `PanicCode (*create_filler_value)(TaggedPtr* to)`. Since it's only used in `set` I think I can do this part later (separate pr).

(edited to move `bitSet` to bottom)

**Comment by jclark** [comment]
It's OK to do `get` like that for now, but this requires that the get instruction

1. assumes the length is immediately after the descriptor pointer
2. checks that the index is within range, and branches if it is not
3. makes a call through the get pointer

i.e. it's a precondition to the `get` function in the descriptor that the index is in range; the `get` function will not call panic (this is because the get insn is a PPI and PPIs have to report their panics via branching).

The approach I suggested to the filler value is an optimization that we can do later.

**Comment by jclark** [comment]
You don't need `contains`: the `set` needs to check that `val` is allowed by the `bitSet`.  A TypeTest will need to be able to check that a particular list belongs to it, but it can do that via the descriptor.

**Comment by jclark** [comment]
This should be pointerType not heapPointerType, because the descriptors are not heap-allocated.

https://github.com/ballerina-platform/nballerina/blob/d4717963bc3f248682b02f75b3b17d7a13339190/compiler/modules/nback/types.bal#L15

Edited: Not sure. Please check.
