### ISSUE TITLE
Support `null` as synonym for `()`

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#598]
Ballerina allows `null` as a synonym for `()` both as a type descriptor and a literal.

https://ballerina.io/spec/lang/2021R1/#nil-type-descriptor
https://ballerina.io/spec/lang/2021R1/#nil-literal

**Comment by jclark** [comment]
subset spec will need to be fixed to match also.

**Comment by heshanpadmasiri** [comment]
@jclark are we going to allow `null` to become a synonym of `()` in the type descriptor as well? The spec [says](https://ballerina.io/spec/lang/2021R1/#nil-type-descriptor)
```
nil-type-descriptor :=  ( )
nil-literal :=  ( ) | null
```
which I understood as only the `nil-literal` supports `null` as a synonym for `()` (We currently have the same as above in the subset spec as well)

**Comment by jclark** [comment]
Sorry I missed that. You are right: `null` should only be accepted as a nil-literal not a type-descriptor.
