### ISSUE TITLE
Remove Symbol, Scope, ScopeEntry and TypeSymbol classes

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#6]
**Description:**

Remove frontend classes such as Symbol, Scope, ScopeEntry and TypeSymbol and simplify PackageID.

**Comment by ayonam** [comment]
We need those classes once we start emitting the DWARF debug info.  So may be a good idea to keep them around as placeholders.  May be we will need to add some more information in them to match the requirements of the DWARF standards.

**Comment by Kishanthan** [comment]
@manuranga @ayonam should we close this issue?
