### ISSUE TITLE
Add LIT test that uses the runtime

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#60]
**Description:**
Add LIT tests to cover the functionality added by the runtime

**Suggested Labels:**
Priority/High

**Suggested Assignees:**
shubhamnarlawar

**Comment by ruvi-d** [comment]
@shubhamnarlawar for your attention

**Comment by shubhamnarlawar** [comment]
@ruvi-d - Do you mean porting current LIT tests to use runtime functions like print64() instead of echo $?

**Comment by ruvi-d** [comment]
I was thinking that for the functionality that was added to the runtime like `new_int_array`, `printf32`, etc.. we need to have some LIT tests to invoke them to confirm the functionality.
I suppose we don't need to port all the existing tests. But shall we add new tests to cover the existing runtime features?

**Comment by shubhamnarlawar** [comment]
> I was thinking that for the functionality that was added to the runtime like `new_int_array`, `printf32`, etc.. we need to have some LIT tests to invoke them to confirm the functionality.
> I suppose we don't need to port all the existing tests. But shall we add new tests to cover the existing runtime features?

I will add new tests to cover those functionalities.

**Comment by ruvi-d** [comment]
@shubhamnarlawar I have a suggestion as to how to call our runtime print routines from Ballerina. 
e.g. to call `int32_t printu32(uint32_t num32)`
Write the following .bal code, defining our runtime functions with the `external` keyword.
```
public function printu32(int val) returns int = external;

public function main() {
  _ = printu32(42);
}
```
The ballerina compiler will throw an error when you compile this, but a BIR dump will get created.

The BIR will contain an empty function for `printu32` with no basic blocks. From the codegen logic, we need to detect these functions that are from our runtime and replace the empty functions with just a function declaration so that they can be linked with the runtime lib.

Hope that makes sense?

**Comment by shubhamnarlawar** [comment]
> @shubhamnarlawar I have a suggestion as to how to call our runtime print routines from Ballerina.
> e.g. to call `int32_t printu32(uint32_t num32)`
> Write the following .bal code, defining our runtime functions with the `external` keyword.
> 
> ```
> public function printu32(int val) returns int = external;
> 
> public function main() {
>   _ = printu32(42);
> }
> ```
> 
> The ballerina compiler will throw an error when you compile this, but a BIR dump will still get created.
> 
> The BIR will contain an empty function for `printu32` with no basic blocks. From the codegen logic, we need to detect these functions that are from our runtime and replace the empty functions with just a function declaration so that they can be linked with the runtime lib.
> 
> Hope that makes sense?

Makes sense! Thank you for the suggestion.

Edit -  `printu32()` does not return

**Comment by shubhamnarlawar** [comment]
> @shubhamnarlawar I have a suggestion as to how to call our runtime print routines from Ballerina.
> e.g. to call `int32_t printu32(uint32_t num32)`
> Write the following .bal code, defining our runtime functions with the `external` keyword.
> 
> ```
> public function printu32(int val) returns int = external;
> 
> public function main() {
>   _ = printu32(42);
> }
> ```
> 
> The ballerina compiler will throw an error when you compile this, but a BIR dump will still get created.
> 
> The BIR will contain an empty function for `printu32` with no basic blocks. From the codegen logic, we need to detect these functions that are from our runtime and replace the empty functions with just a function declaration so that they can be linked with the runtime lib.
> 
> Hope that makes sense?

Apart from the function has 0 basic blocks, Can you suggest a way to detect current function is not a runtime function based on name?

**Comment by manuranga** [comment]
In java side we are relying on the flags, flag is checked as follows `(functionFlags & NATIVE) == NATIVE;` where `NATIVE = 2`.

reference: 
[1] https://github.com/ballerina-platform/ballerina-lang/blob/3b3832f96dfdcafc3cd5630c950a12cccc6c92fa/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/util/Flags.java#L31

[2] https://github.com/ballerina-platform/ballerina-lang/blob/4510139d40b86cca4025de9889eb0d4b3ef0fde8/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L355
