### ISSUE TITLE
Call _bal_panic after ret instruction

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/nballerina#61]
**Description:**
If bal file contains a function call, it is considered as potentially panicking instruction and call `_bal_panic` after return

https://github.com/ballerina-platform/nballerina/blob/5efb9e205bc8e743edf2bb9fb83d65d8502fa506/compiler/modules/bir/bir.bal#L395

**Steps to reproduce:**
ball file:
```
public function main() {
    int x = foo();
}

function foo() returns int {
    return 2;
}
```
generated llvm for the main function:
```
define void @_B_main () {
  %R0 = alloca i64, align 8
  %R1 = alloca i64, align 8
  %R2 = alloca i64, align 8
  %R3 = call i64 @_B_foo ()
  store i64 %R3, i64* %R0, align 8
  %R4 = load i64, i64* %R0, align 8
  store i64 %R4, i64* %R1, align 8
  ret void ; below thress line are not executed
  %R5 = load i64, i64* %R2, align 8 
  call void @_bal_panic (i64 %R5)
  unreachable
}```

**Comment by jclark** [comment]
Thanks! I guess the easy fix for now is not to consider "call" to be a potentially panicking instruction.
