### ISSUE TITLE
Call inst contains extra llvm instructions

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/nballerina#62]
**Description:**
$subject. It seems there are two extra load and store instruction which are not needed. 

**Steps to reproduce:**
bal file:
```
public function main() {
    int x = foo();
}

function foo() returns int {
    return 2;
}
```

llvm ir for the main function:
```
define void @_B_main () {
  %R0 = alloca i64, align 8
  %R1 = alloca i64, align 8
  %R2 = call i64 @_B_foo ()
  store i64 %R2, i64* %R0, align 8

  ; these two instructions are not needed.
  %R3 = load i64, i64* %R0, align 8
  store i64 %R3, i64* %R1, align 8

  ret void
}
define internal i64 @_B_foo () {
  ret i64 2
}
```

This can be verified by generating a llvm ir for a similar C code.

**Comment by KavinduZoysa** [comment]
@jclark, WDYT about this?

**Comment by KavinduZoysa** [comment]
I found this when writing test cases for function call. Still, I am not sure whether it is okay to continue with these extra instructions.

**Comment by jclark** [comment]
This is fine.

There are 3 BIR instructions call/assign/ret, and 2 BIR registers R0 and R1: R0 is a temporary for the result of the call; R1 is for variable x. The translation of the call instruction does the first store. The load and second store are the translation of the assign instruction.

The input source code has a dead store, and the resulting BIR is faithfully reproducing that.

LLVM will optimize it all away.
