### ISSUE TITLE
Func call inside if block contains extra store instruction

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/nballerina#63]
**Description:**
$subject

**Steps to reproduce:**
bal file for main function:
```
public function main() {
    int x = 3;
    if (x == 3) {
        bar(100);
    } 
}
```

llvm ir for the main function:
```
define void @_B_main () {
  %R0 = alloca i64, align 8
  %R1 = alloca i1, align 8
  %R2 = alloca i1, align 8
  store i64 3, i64* %R0, align 8
  %R3 = load i64, i64* %R0, align 8
  %R4 = icmp eq i64 %R3, 3
  store i1 %R4, i1* %R1, align 8
  %R5 = load i1, i1* %R1, align 8
  br i1 %R5, label %L1, label %L2
L1:
  call void @_B_bar (i64 100)
  store i1 0, i1* %R2, align 8 ; This is an extra instruction
  br label %L2
L2:
  ret void
}
```

**Comment by jclark** [comment]
This one is fine.  Ballerina functions without an explicit return type return nil. This is storing the return value of `bar` into a register.

The objective of the front end is to generate correct code, not the minimum number of instructions.

(Please always include complete test case.)
