### ISSUE TITLE
LIT test simpleMain fails

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#64]
**Description:**
The LIT test [simpleMain.bal](https://github.com/ballerina-platform/nballerina/blob/master/test/functions/simpleMain.bal.skip) fails. Returning `16` instead of the expected `128` on Ubuntu 20.04 / clang11

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**
shubhamnarlawar

**Comment by shubhamnarlawar** [comment]
Now that simple rust print routines are already present in the master. Let us find a way to port the LIT unit tests to use these print routines instead of `echo $?`.

**Comment by ruvi-d** [comment]
Fixed with #43
