### ISSUE TITLE
Parse all type descriptors starting with an identifier in local var decl statements

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#640]
future/fieldexpr1-uv.bal is giving a parse error, which is not right.

**Comment by jclark** [comment]
This is something that should have been fixed in #412.

**Comment by manuranga** [comment]
In the 09 subset grammar, `type-reference` only appears at the top level of `type-desc`, and `type-desc` is not recursive. So I believe this case is ruled out by the grammar. If we are to fix this, a grammar change is needed.
It might as well include other type reference related generalizations such as `A? a = ();` and `B[] b = [];`.

**Comment by jclark** [comment]
The type subset is enforced semantically not via the grammar: we should support the same type descriptors in a local variable declaration as we do elsewhere, for example in a type cast or a function parameter.

See https://github.com/ballerina-platform/nballerina/blob/main/docs/subset09.md#notes

**Comment by manuranga** [comment]
Hmm I misunderstood extent to which the statement grammar should be allowed. So I should fix `A? a = ();` `B[] b = [];` ect. along with this.

I think we discussed briefly about implementing this by factoring some `parse`* functions in `parseTypeDesc.bal` into `finish`* functions. Let me try that with `parsePostfixTypeDesc`.

**Comment by manuranga** [comment]
Draft PR #641 illustrate the above idea. (I have yet to refactor the `parseTypeDesc.bal` such that normal type parsing uses `finish`* functions , and to get the positions correct)

**Comment by jclark** [comment]
Yes, we want those things too.

The idea is that when we add full support for new types that are already supported in semtypes, we should not have to do any work on parsing: all we have to do is not disallow them in resolveTypes.

We don't need to call this a bug, since we are handling our subset properly.  We really do need this for subset 11, since our type desc grammar will be very general by then; not yet sure what to put in subset 10.

**Comment by jclark** [comment]
Draft PR #641 looks promising, but quite a lot of work/complexity.

Maybe worth thinking for a bit if we can find a simpler way to do this. I thought at first of some combo of peek plus save/restore state, but I guess that's not going to work, because of qualified identifiers. Arghh.

**Comment by jclark** [comment]
@manuranga We have a problem only with type descriptors starting with an identifier, right?

**Comment by manuranga** [comment]
I think `1 one = 1;` vs `1.toHex();` (semantically invalid) case will also have a similar issue. Also with string literals.

**Comment by jclark** [comment]
And boolean literals and (in the future) tuple types, I guess. I think for these we can do what we did with `(`, since they are not common.

**Comment by manuranga** [comment]
As you mentioned, using `peek` is elegant for most cases (given we extend peek see past `:` of qualified identifiers). But `A[] a = x;` vs `a[x] = x` will be difficult, we'll need `peek(2)` or some other trick.

Then again, this case will get even harder with fixed length arrays `A[n] a = x;`. I think once we peek `A[`, we should do a preparse. This solution will continue to work with fixed length arrays.

**Comment by jclark** [comment]
Not obvious to me whether extending peek to qualified identifiers + preparse is going to simpler than left factoring.

**Comment by manuranga** [comment]
Please take a look at #648 that uses peek + preparse approach, I think it turn out to be a much elegant approach than the other.
