### ISSUE TITLE
Fix breaking changes with jBallerina Swan Lake Beta4

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#644]
Current breaking changes are here:
https://github.com/ballerina-platform/nballerina/actions/runs/1392592562

(Some of these warnings should go away with https://github.com/ballerina-platform/ballerina-lang/pull/33435 but this has not landed in dist yet.)

**Comment by jclark** [comment]
I will fix the one in llvm.bal. Instead of panic we can use this idiom:

```
else {
            GeneralIntrinsicName _ = name;
```

where previously we would panic if it's not a GeneralIntrinsicName.

**Comment by KavinduZoysa** [comment]
Getting `redeclared symbol` error is a JBUG bug, created an issue for that https://github.com/ballerina-platform/ballerina-lang/issues/33510

**Comment by KavinduZoysa** [comment]
There is a fix for the warning `this function should explicitly return a value` in release branch, but it is not available in the beta4 rc1 release. It will be available from next release.

**Comment by manuranga** [comment]
Some warninga will go away with ballerina-platform/ballerina-lang#33435, whatever remains we should fix under this issue.

**Comment by manuranga** [comment]
@KavinduZoysa since the first RC is out, we need to close this issue as soon as possible. We need to report back issues before the voting mail closes.

**Comment by manuranga** [comment]
Found https://github.com/ballerina-platform/ballerina-lang/issues/33694, I could inline `VariableLengthToken` as a workaround for now.

**Comment by jclark** [comment]
Can we get this fixed for beta4?

**Comment by hasithaa** [comment]
Yes, we are checking this.

**Comment by jclark** [comment]
Does beta4 fix https://github.com/ballerina-platform/ballerina-lang/issues/33532? We need that in order to get rid of some of the warnings.

**Comment by manuranga** [comment]
Yes it's fixed.

**Comment by jclark** [comment]
We'll leave the rest of this for when beta4 is out.
