### ISSUE TITLE
LIT test floatTypecast fails to compile

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/nballerina#65]
**Description:**
The LIT test [floatTypecast.bal](https://github.com/ballerina-platform/nballerina/blob/master/test/casting/floatTypecast.bal.skip) fails generate a .ll throwing the following error.
```
./nballerinacc temp-dump
nballerinacc: /home/ruvinda/projects/nballerina/compiler/BIRReader.cpp:120: float ConstantPoolSet::getFloatCp(uint32_t): Assertion `poolEntry->getTag() != ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_FLOAT' failed.
Aborted (core dumped)
```

**Suggested Labels:**
Type/Bug Priority/High 

**Suggested Assignees:**
shubhamnarlawar

**Comment by shubhamnarlawar** [comment]
Thanks for pointing it out. It is silly updation miss.

It should be - 

``poolEntry->getTag() == ConstantPoolEntry::tagEnum::TAG_ENUM_CP_ENTRY_FLOAT'`

I will push this change!
