### ISSUE TITLE
Test failures in master

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/nballerina#67]
**Description:**
Running the command `bal test --tests "testCompile*" ../compiler` says that two tests are failing. 
```
		[fail] testCompileError:

		    wrong error position /home/kavindu/WSO2-GIT/nbal/nballerina/tests/../tests/Eassign01.bal
		    	
		    	expected: <int> '4'
		    	actual	: <()> ''

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertEquals(assert.bal:75)
		    	wso2.nballerina.0_1_0.tests.integration:testCompileError(tests/integration.bal:33)

		[fail] testCompileError:

		    wrong error position /home/kavindu/WSO2-GIT/nbal/nballerina/tests/../tests/Eassign00.bal
		    	
		    	expected: <int> '4'
		    	actual	: <()> ''

		    	at ballerina.test.0_8_0:createBallerinaError(assert.bal:43)
		    	ballerina.test.0_8_0:assertEquals(assert.bal:75)
		    	wso2.nballerina.0_1_0.tests.integration:testCompileError(tests/integration.bal:33)
```

Also running script (`sh testll.sh`) says,
```
Aborted (core dumped)
Aborted (core dumped)
Aborted (core dumped)
Aborted (core dumped)
```

**Steps to reproduce:**

```
bal test --tests "testCompile*" ../compiler
sh testll.sh
```

**Comment by jclark** [comment]
Please also say what system you are running on, including clang version.

**Comment by KavinduZoysa** [comment]
Please find the environment details,

```
OS: ubuntu 16.04
clang: 11.1.0
```

**Comment by manuranga** [comment]
1) I'll fix the `wrong error position` one
2) I used to get `testll.sh: line 11: 68508 Abort trap: 6           ./a.out > /dev/null 2> $b-actual.txt` printed by sh (`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)`) but I was able to git rid of it by [wrapping with a sub-shell](https://github.com/ballerina-platform/nballerina/blob/4b9b45a82bca6922f668efec712dca1d85f6f12c/tests/testll.sh#L15). Looks like that doesn't work on your shell. It'll be great if you can find a workaround for that since it's hard to replicate on my machine.

**Comment by KavinduZoysa** [comment]
> 2. I used to get `testll.sh: line 11: 68508 Abort trap: 6           ./a.out > /dev/null 2> $b-actual.txt` printed by sh (`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)`) but I was able to git rid of it by [wrapping with a sub-shell](https://github.com/ballerina-platform/nballerina/blob/4b9b45a82bca6922f668efec712dca1d85f6f12c/tests/testll.sh#L15). Looks like that doesn't work on your shell. It'll be great if you can find a workaround for that since it's hard to replicate on my machine.

I will work on that.

**Comment by jclark** [comment]
I updated the testll.sh. See if it works for you now (I used /bin/bash instead of /bin/sh).

**Comment by jclark** [comment]
@KavinduZoysa If you still have the problem, please reopen
