### ISSUE TITLE
Support semtype tests that result in errors

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/nballerina#686]
**Description:**

After doing this add back the xml intersection test cases where result is empty, which were removed with the commit: https://github.com/ballerina-platform/nballerina/pull/562/commits/56622283e0a2ff6e8e9723654bd8d0b32e6c76c1

We will have to introduce a new test type; a combination of `-t` and `-e`.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by jclark** [comment]
We should probably also rename the existing `-t` cases to `-tv`.
