### ISSUE TITLE
Add ability to set initializer after creating global variable in llvm

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#689]
Currently we expect `initializer` value to be given at the time of defining a global variable using `addGlobal` function. We need to add the ability to set this after creating the global value similar to [`LLVMSetInitializer`](https://llvm.org/doxygen/group__LLVMCoreValueConstantGlobalVariable.html#gaecc937af154a1d4fd5d337e5783a8387).
For this I will add a function `setInitializer(ConstPointerValue global, ConstValue|Function? initializer)` to `Module`

**Comment by jclark** [comment]
Prerequisite for #571

**Comment by jclark** [comment]
Why the `?` in the type of the initializer argument?

**Comment by heshanpadmasiri** [comment]
It's a typo it should be `setInitializer(ConstPointerValue global, ConstValue|Function initializer)`
