### ISSUE TITLE
Fix relational operators on lists to handle arrays with arbitrary member types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#706]
At the moment, the implementation assumes that member type is a bitset (in the front-end, it uses simpleArrayMemberType).

**Comment by manuranga** [comment]
Progress:
I first tried having something like below, where `mt` is the smallest comparable super type of lhs type and rhs type. 
```C
int64_t READONLY _bal_array_generic_compare(TaggedPtr lhs, TaggedPtr rhs, MemberType mt)
```
But I realized, I don't need `mt`, because at most lhs type and rhs type is going to differ in nilability. Now I have
```C
int64_t READONLY _bal_array_generic_compare(TaggedPtr lhs, TaggedPtr rhs)
```
I have implemented about, needs testing and cleanup.

**Comment by manuranga** [comment]
@jclark  What should be a the OrderType in the BIR for following comparison ?
```ballerina
()[] a = [()];
()[] b = [(), ()];
io:println(a > b);
```

**Comment by jclark** [comment]
Not an ordered type.

**Comment by manuranga** [comment]
Can you please explain why the above relational expression is invalid.
Spec says 
> There must be an ordered type to which the static type of both operands belong.

I interpret "belong" here as "subtype". In above case, since `()[]` is a subtype of `int?[]`, and `int?[]` is an ordered type, shouldn't it be valid?

(btw, above is currently working in jBallerina)

**Comment by jclark** [comment]
`()[]` isn't an ordered type, but you are right that `int?[]` is, and _belong to_ must mean subtype of. So it doesn't make sense that the spec does not include nil in the basic types that are ordered. Can you create a spec issue?

We should add t:UT_NIL to UniformOrderType.

**Comment by manuranga** [comment]
To accommodate nil arrays I plan to change BIR to

```ballerina
public type OrderType UniformOrderType|OptOrderType|ArrayOrderType;
public type UniformOrderType t:UT_FLOAT|t:UT_INT|t:UT_BOOLEAN|t:UT_STRING|t:UT_NIL;
public type OptOrderType readonly & record {|
    t:UT_FLOAT|t:UT_INT|t:UT_BOOLEAN|t:UT_STRING|ArrayOrderType opt;
|};

// pr-todo: check if it's a JBUG that I can't use [OrderType] here
public type ArrayOrderType readonly & record{| OrderType memberOrderType; |};
```

Also I'll have to pass `MemberType mt` to `_bal_array_generic_compare` as well.

**Comment by manuranga** [comment]
we discussed having 
```ballerina
public type OptOrderType readonly & record {|
    ArrayOrderType|UniformOrderType? opt;
|};
```
This works. But since we use `bir:OrderType?` during calculation of order type, as an intermediate representation, where `()` means 'non order type', code becomes obtuse. I am thinking of using `bir:OrderType|"UNORDERED"`. This will not go into BIR.

**Comment by manuranga** [comment]
I'll have to move https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/01-nil/rel-e.bal

**Comment by jclark** [comment]
You could do something like:

```
ArrayOrderType|UniformOrderType|NoOrderType opt
```

where

```
const NoOrderType = false; 
```

Here `NoOrderType` is effectively never.

**Comment by manuranga** [comment]
Found a corner case
```ballerina
import ballerina/io;

public function main() {
    int[] v1 = [];
    if v1 is string[] {
        string[] s = ["one"];
        io:println(v1 < s);
    }
}
```
Looks like it should compile, I might need a way to represent an empty tuple. Is there any other ways I can end up with `[]` type in current subset?
