### ISSUE TITLE
Refactor and move code to list.c form balrt.h and list_inline.c

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#744]
Move relevant code to list.c.
Use `NIL` and `COMPARE` macros.

**Comment by jclark** [comment]
_bal_string_cmp returns <0, 0 or >0 (like strcmp)

The *_compare functions return one of 4 values allowing for unordered possibility.  We should use a typedef to make this clear e.g. `typedef int64_t CompareResult`.

There's a bug in taggedStringCompare which is incorrectly assuming that _bal_string_cmp returns -1,0,1.

**Comment by manuranga** [comment]
Need to address following comments:
https://github.com/ballerina-platform/nballerina/pull/742#discussion_r759178282
https://github.com/ballerina-platform/nballerina/pull/742#discussion_r759185017
