### ISSUE TITLE
Handle cases when store through exact pointer can fail

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#754]
Normally static type checks are enough to ensure that a store into a structure can fail at runtime only if the inherent type at runtime is not the same as the static type. But there are some cases when they are not enough, for example:

```ballerina
type C record {|
    int i;
|};

public function main() {
    C c = { i: 0 };
    string m = "j";
    c[m] = 8;
}
```

**Comment by jclark** [comment]
This is a really interesting case because `c[m]` as an expression would give us nil.
