### ISSUE TITLE
SemType bug related to order of definitions

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#757]
This gets a compile error:

```
// If A follows B, the bug goes away.
type A int?[];
type B int[];
type C A|B;

function foo(C v) returns A {
    return v;
}
```

The problem is that C is not recognized as being a subtype of A.  `--showTypes` gives:

```
A<:C
B<:A
B<:C
```

But if we reorder of the definitions of A and B, we get the right result:

```
A<:C
B<:A
B<:C
C<:A
```

**Comment by jclark** [comment]
We get the same thing if `int[]` is replaced by `map<int>`.

**Comment by jclark** [comment]
Different order of definitions would lead to different ordering of BDD atoms.

**Comment by jclark** [comment]
On page 15:35 of the [Castagna paper](https://arxiv.org/pdf/1809.01427.pdf), we have

B<sub>1</sub> \ B<sub>2</sub> = a<sub>1</sub> ? C<sub>1</sub> \ C<sub>2</sub> : U<sub>1</sub> \ U<sub>2</sub> : D<sub>1</sub> \ D<sub>2</sub> for a<sub>1</sub> = a<sub>2</sub>

(The Castagna notation uses 1 and 0 where we use true and false and uses \ means diff.)

where

B<sub>1</sub> = a<sub>1</sub> ? C<sub>1</sub> : U<sub>1</sub> : D<sub>1</sub>

and

B<sub>2</sub> = a<sub>2</sub> ? C<sub>2</sub> : U<sub>2</sub> : D<sub>2</sub>

But consider:

(A<sub>1</sub>|A<sub>2</sub>) \ A<sub>1</sub>

where

A<sub>1</sub> = a<sub>1</sub> ? 1 : 0 : 0
A<sub>2</sub> = a<sub>2</sub> ? 1 : 0 : 0

If we apply this rule, we get:

A<sub>1</sub>|A<sub>2</sub> = a<sub>1</sub> ? 1 : (a<sub>2</sub> ? 1 : 0 : 0) : 0

(A<sub>1</sub>|A<sub>2</sub>)\A<sub>1</sub> = a<sub>1</sub> ? (1 \ 1) : ((a<sub>2</sub> ? 1 : 0 : 0) \ 0) : (0 \ 0) = a<sub>2</sub> ? 1 : 0 : 0 = A<sub>2</sub>

which is not correct unless A<sub>1</sub>  and A<sub>2</sub> are disjoint.

**Comment by jclark** [comment]
This is exactly the same formula where the AMK tutorial had a different formula from the Castagna paper (which I reported as a bug): https://github.com/pnwamk/sst-tutorial/issues/3

If we look at the [Frisch PhD thesis](http://www.cduce.org/papers/frisch_phd.pdf) (in French) on page 213, it provides formulas for union, intersection, and complement but not difference. Also worth noting is that the formula for intersection materializes the lazy unions in the case where the atoms are the same and the formula for complement in general also materializes the lazy union.

I think the Castagna formula is wrong.

**Comment by jclark** [comment]
One natural fix is to materialize the lazy union as in the intersection case, so the formula becomes:

a<sub>1</sub> ? (C<sub>1</sub> &#x2228; U<sub>1</sub>) \ (C<sub>2</sub> &#x2228;  U<sub>2</sub>): &#x1D7D8; : (D<sub>1</sub> &#x2228; U<sub>1</sub>)  \ (D<sub>2</sub> &#x2228; U<sub>2</sub>)

We can be confident this is correct since it follows from

- the formula for set difference in the non-lazy case, and
- the semantics of the lazy union

and it maintains the invariant that the atoms are ordered on every path.

Can we avoid materializing the union? I don't see any way to do so.

Edited: Dr Castagna confirms by email this formula is correct.  Note also that the formula for complement in the Frisch thesis (bottom of page 213) is wrong: t1 and t3 should be swapped. It is correct in the AMK tutorial.

**Comment by jclark** [comment]
Everything seems to work now with the formula I propose in https://github.com/ballerina-platform/nballerina/issues/757#issuecomment-990611016

**Comment by manuranga** [comment]
Does this mean bdd should always be materialize before calling `isEmpty`?
Edit: No, the issue happens in diff not isEmpty

**Comment by jclark** [comment]
> Does this mean bdd should always be materialize before calling `isEmpty`?

As you realized, no.  Lazy unions are handled by `isEmpty` in `bddEvery`. This is why the lazy union concept works well.

**Comment by manuranga** [comment]
>  Lazy unions are handled by `isEmpty` in `bddEvery`

Yes, it's easy to understand that it is correct when atoms in middle doesn't intersect with atoms in left or right. It not obvious to me yet why it works otherwise. I imagined `bddEvery` will have to call itself 4 times not 3, twice for middle with current atom in both positive and negative.

Anyway this is irreverent to current issue.

**Comment by jclark** [comment]
The BDD represents a disjunction of conjunctions, where each conjunction is a path from the root to a leaf that is true. When the path goes through the left of a node, the atom is included in the conjunction positively; when right, negatively; when middle, it's not included.  isEmpty checks that every conjunction is empty, by using bddEvery to accumulate each conjunction.  All bddEvery has to do is for middle is to recurse, without adding anything to the conjunction being accumulated.  If you want to check that X|Y|Z is empty, you just have to check that each of X, Y and Z is empty: it doesn't matter whether they are disjoint or not.

**Comment by manuranga** [comment]
Here is a visual representation of the complement formula.
![not-formula](https://user-images.githubusercontent.com/1686124/146134525-650c6def-6631-47ea-8fe9-e628193d84f2.png)
