### ISSUE TITLE
Update JBUGs for slbeta6

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#765]
Update all JBUG comments to remove any that are fixed for beta6 and add bug numbers for other.

**Comment by manuranga** [comment]
Should we attempt following under this?
https://github.com/ballerina-platform/nballerina/blob/7425876af3164d914055c8b8b9f54c1590b9d2cb/compiler/modules/comm.err/err.bal#L26

**Comment by jclark** [comment]
We use that with match IIRC, and I suspect unreachability doesn't work well enough in that case. So probably not.

**Comment by gimantha** [comment]
Reopening this as there are few more issues left and currently working on them

**Comment by jclark** [comment]
The build has broken...

**Comment by gimantha** [comment]
> The build has broken...

I sent a revert PR here: https://github.com/ballerina-platform/nballerina/pull/868,
I will check what went wrong

**Comment by jclark** [comment]
OK. I don't understand what went wrong.

**Comment by jclark** [comment]
Where are we on this? Can we get this merged?

**Comment by gimantha** [comment]
> Where are we on this? Can we get this merged?

I am having some trouble getting all the test working due to a clang failure. I will try to get it merged ASAP.
