### ISSUE TITLE
Try to clean up AST representation of `else if`

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#794]
We currently represent the `else` part of an if-else statement as a `StmtBlock?`. But this doesn't cleanly represent the `else if` case: we are manufacturing a block that does not exist.  Better to represent it as `StmtBlock|IfElseStmt?`. But can we do this without complicating codeGen too much?

**Comment by jclark** [comment]
Perhaps we can use this to reduce complexity of generated BIR.

**Comment by manuranga** [comment]
Compiler is panicking for following input, therefor marking this issue as a bug.
```ballerina
public function main() {
    if true {
    }
    else if true {
    }
}
```
Error:
```
error: {ballerina/lang.array}IndexOutOfRange {"message":"array index out of range: index: 0, size: 0"}
        at wso2.nballerina.front.0:codeGenIfElseStmt(codeGen.bal:755)
           wso2.nballerina.front.0:codeGenStmtBlock(codeGen.bal:346)
           wso2.nballerina.front.0:codeGenFunction(codeGen.bal:295)
           wso2.nballerina:generateFunctionCode(front.bal:48)
           wso2.nballerina.nback.0:buildModule(module.bal:55)
           wso2.nballerina.0.CompileContext:buildModule(compile.bal:41)
           wso2.nballerina.0:processModule(compile.bal:91)
           wso2.nballerina.0:compileBalFile(compile.bal:76)
           wso2.nballerina.0:main(main.bal:62)
```

**Comment by manuranga** [comment]
Let's consider the above code sample, currently if-else-stmt has three StmtBlocks, with this it will only have two. That means if-false narrowing of first if and if-true narrowing of second if will both be generated into second StmtBlock. `codeGenStmtBlock` will have to accept a list of initial narrowing ([prev](https://github.com/ballerina-platform/nballerina/pull/788#discussion_r777969156)). I am going to explore the possibility to making narrowings also into an immutable linked list (like bindings).

**Comment by jclark** [comment]
Can you instead make codeGenStmtBlock take either a StmtBlock or an IfElseStmt (and rename to e.g. codeGenScope)?
