### ISSUE TITLE
Remove -ltinfo from the nballerina Makefile

### ISSUE THREAD

**Issue by shubhamnarlawar** [ballerina-platform/nballerina#8]
**Description:**
`-ltinfo` give a error while linking

**Comment by shubhamnarlawar** [comment]
If we remove this flag, then at our side, the testcases are failing in the execution phase.

Depending on the ENVIRONMENT, one can alter this flag in the Makefile.

**Comment by ayonam** [comment]
We should add a condition check in the
        Makefile for the OS and if it is MacOS (Or probably Darwin), we
        should omit that flag.
    
    
        
        Ayonam Ray 
        Director
      
      
        
          
            
              R. R. Logic Systems
                  Private Limited 
              
                #89, 1st Floor, V. M. Cosma
                Karthik Nagar, Marathahalli Outer Ring Road
                Bengaluru - 560 037, INDIA
              
            
          
        
      
      
        
          
            Mobile: +91-98456-67483
            Web: https://www.rrlogic.co.in/
          
          
            Fax: +91-80-6688-5757
            E-mail: ayonam@rrlogic.co.in
          
        
      
      
        
      
      
      
      
    
    On 03/10/20 10:28, shubhamnarlawar
      wrote:
    
    
      
      If we remove this flag, then at our side, the testcases are
        failing in the execution phase.
      Depending on the ENVIRONMENT, one can alter this flag in the
        Makefile.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ballerina-platform/nballerina/issues/8#issuecomment-703047105",
"url": "https://github.com/ballerina-platform/nballerina/issues/8#issuecomment-703047105",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shubhamnarlawar** [comment]
The current Makefile status for flag `-ltinfo` is - 

UNAME=$(shell uname)
ifeq ($(UNAME), Linux)
  LTINFO = -ltinfo
endif

In the call, @manuranga mentioned that there is some error while building nballerina. Can you post the reason for the error so that we can alter the Makefile accordingly?

**Comment by manuranga** [comment]
@warunalakshitha shall we verify this using ubuntu.

**Comment by shubhamnarlawar** [comment]
> @warunalakshitha shall we verify this using ubuntu.

Any updates on this?

**Comment by shubhamnarlawar** [comment]
> @warunalakshitha shall we verify this using ubuntu.

Have you checked at your side? I think this is the only issue that is blocking the PR for milestone 2.

**Comment by shubhamnarlawar** [comment]
Have you checked this flag on Linux ENV at your end?

**Comment by ruvi-d** [comment]
@Kishanthan : we can close this since the use of -ltinfo was removed with #52

**Comment by Kishanthan** [comment]
Ack.
