### ISSUE TITLE
Add position to `WildcardMatchPattern`

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#800]
Currently `WildcardMatchPattern` doesn't have  a position attached to it (unlike other `MatchPatterns`)

**Comment by jclark** [comment]
Preparation for #789, #790.

**Comment by jclark** [comment]
Can we do

```
type MatchPattern WildcardMatchPattern|SimpleConstExpr;
```

Then include *PositionFields; in WildcardMatchPattern.

WildcardMatchPattern would have a field whose value is singleton "_".
