### ISSUE TITLE
Implement is_same_type for array type

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#86]
**Description:**
Implement `is_same_type()` for array type in RUST.

Input - one source type mangled string and one destination type mangled string.
Output - `bool` value stating whether typecast is possible or not.

More details are available in discussion - #50 

**Suggested Assignees:**
@shubhamnarlawar

**Comment by shubhamnarlawar** [comment]
Tasks to be done - 

[] - Write wrapper function for is_same_type() to check whether original types of source and destination can be typecasted.
[] - Avoid converting to rust strings from char *

**Comment by shubhamnarlawar** [comment]
> Tasks to be done -
> 
>     * [ ]  Write wrapper function for `is_same_type()` to check whether original types of source and destination can be type casted.
> 
>     * [x]  Find a way to directly operate on char* pointers rather than converting to rust strings from char *. (Here, `char * pointers` are nothing but `pointers` to `mangled strings` received from `LLVM` side.)

Created an issue for 2nd point - Issue #106

**Comment by manuranga** [comment]
Hi @shubhamnarlawar ,
Is it possible to directly call the rust function from generated code, without using a wrapper ?

**Comment by shubhamnarlawar** [comment]
> Hi @shubhamnarlawar ,
> Is it possible to directly call the rust function from generated code, without using a wrapper ?

Yes. there is no need to write wrapper function now. 'is_same_type()' can be called directly from generated code.
