### ISSUE TITLE
Make parentheses explicit in the AST

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#863]
Currently we don't store parenthesis information in the AST and position testing (#816) currently ignore parentheses, both for expressions and type descriptors.

It would be better if we can make parentheses explicit in the AST. We can then

- fully verify the syntax tree
- do #865

**Comment by jclark** [comment]
Obvious approach is to have ParenExpr and ParenTypeDesc, or perhaps GroupingExpr and GroupingTypeDesc (since parentheses are the syntax to express grouping).
