### ISSUE TITLE
Improve verifiability of BIR's representation of conditional type narrowing

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#883]
The BIR is supposed to be _verifiable_. This means that

- there is a definition of when the BIR is valid (we can distinguish well-formed and well-typed)
- the validity of the BIR is the contract between the front-end and back-end: the front-end is required to produce valid BIR and the backend should handle any valid BIR
- there should be a way to verify that when BIR is valid

Probably the most challenging thing from a verification perspective is conditional type narrowing. Currently, the BIR has a conditional narrowing instruction, which includes the "basis" for the narrowing. The basis is the logical combination of instruction references referring back to the instructions that tested the condition; the results of executing the referenced instructions are what justify the narrowing. The basis part of the conditional narrowing instruction is rather unsatisfying, because it has a much more complex internal structure than other instructions.

Using the basis to verify the correctness of the narrowing has not been implemented yet, and I suspect it will be hard, particularly when the basis is a complex and/or combination.

This issue is to develop an idea to improve on this situation. There are a number of elements:

- different representation of conditional type narrowing in the BIR
- revised strategy for codeGen of logical negation
- explicitly distinguishing forward/backward edges

which I will describe below.

These would need to be tested by an implementation.

**Comment by jclark** [comment]
Alternative idea for representation of conditional type narrowing:

- Represent variable narrowing by having a optional 3-tuple of registers associated with a conditional branch insn
   1. unnarrowed register
   2. narrowed register when true
   3. narrowed register when false
- Add a combine narrowings instruction: this would take 2 (or perhaps N >= 2) existing narrowed registers and construct a new narrowed register with a type that was the union of the existing registers

The narrowed registers would be initialized by these two instructions and would not final (i.e. no instructions would assign to them).

The combine narrowings instruction would be allowed at the start of a block, and would be verified based on the forward edges that come into the block (rather like a phi node).

Edited: alternative to first insn is combined BranchOnTypeTest insn.

**Comment by jclark** [comment]
Generating the alternative representation described above would require a new strategy for handling negation.  The idea is

- codeGenExprForBoolean gets an additional negated argument
- it checks for each kind of expression that can produce a narrowing and calls it with a negated argument; other kinds of expression are handled as now
- codeGenTypeTest already has a negated argument: just need to flip it
- codeGenEqualityExpr needs to be refactored to split the op into negated/exact
- codeGen for `&&` and `||` can handle negated by switching `&&` and `||` and passing negated to subexpressions
- codeGen for logical not just does codeGenForBoolean flipping negated

The overall effect is to push `!` down through everything that produces narrowings e.g. `!(x == 1 || x == 2)` gets codeGen'ed like `x != 1 && x != 2`.

If we do this, then we don't need separate ifFalse/ifTrue narrowings, because these are used only for `!` (is that right?)

Edited: we cannot get rid of ifFalse/ifTrue, because we still need both of them with an if/else statement.

I think with this strategy, we could generated the above representation straightforwardly.

**Comment by jclark** [comment]
The Ballerina spec has a constraint that it is an compile error if narrowing results in "the type of a variable reference being affected by assignments that lexically follow the variable reference". This effectively means (I think) that the effects of type narrowing only flow through forward edges in the CFG. (Although this may change with https://github.com/ballerina-platform/ballerina-spec/issues/1032.)

At the moment the CFG does not explicitly distinguish between forward and backwards edges. But it would, I think, be easy to distinguish forward/backward edges as we construct the CFG:

- backwards edges only with loops (foreach/while),  at the end of the loop and with continue; all other edges are forward edges
- every block is reachable from the entry block by a forward edge
- the graph of forward edges is acyclic

If we distinguish forward/backward edges in the CFG, then we can more easily identify how the narrowings flow through the graph.

Concretely, we might implement this by
- having forward edges always go to a block with a higher-numbered label; backwards edges always go to a block with a lower-numbered label
- including in the BIR a list of Loop records, where each Loop record has the index of the first block in the loop (the header) and the index of the last block in the loop

Edited: `break` is a problem: we generate a label for the branch to break to when we come across it; so if we have two break statements in a single loop, the second one will be a branch to a lower-numbered branch even though it is logically a forward edge.

We should also consider whether these changes would

- make it easier to construct an SSA from the BIR (e.g. using the approach of [Single-pass generation of static single-assignment form for structured languages](https://dl.acm.org/doi/abs/10.1145/197320.197331))
- make it easier to generate WASM control flow constructs
- ensure that BIR flow graphs are always reducible

Edited: this isn't sufficient to enable single pass SSA generation: that requires knowing the join nodes up front

**Comment by manuranga** [comment]
Logical operations can't always broken down to if-else without duplicating the body. eg:
```ballerina
int|float|string x = …;
if a is int || a is float {
   f(a); 
}
```
But the same sort of union instruction that will work for combining if-else should work. So general idea of narrowings flowing through the CFG is still valid for logical operations.
![Edit pad 2(1)](https://user-images.githubusercontent.com/1686124/152106196-d9e7dfeb-c142-4202-8247-5c35e99d4350.png)

**Comment by jclark** [comment]
So I think we want two instructions (which would replace the existing ConditionalTypeNarrow insn):

- TypeBranch
- TypeMerge

TypeBranch insn has

- Operand Register to be tested
- SemType to test
- for each of ifTrue/ifFalse case:
   - label of branch to jump to
   - narrowed register to create 

This tests whether the value in the operand register belongs to the SemType. Depending on the result it selects the ifTrue/ifFalse case. For the selected case, it sets the narrowed register to the value and jumps to the branch. Verifying would check that
- the type of the ifTrue case is the intersection of the SemType and the type of the operand register; and
- the type of the ifFalse case is the rodiff of the SemType and the type of the operand register

TypeMerge insn has

- Result register to be created
- List of registers to be merged, and for each register, label of predecessor block

The type of the result register is the union of the type of the registers to be merged. Each merged register must be valid in its predecessor block and that block must end with an unconditional branch to the block containing the TypeMerge insn.  This is very like a phi node.

**Comment by manuranga** [comment]
```
 Current BIR         . Ballerina code                 . Proposed BIR
--------------------.--------------------------------.-----------------
                     . public function main() {       .                 
  Assign             .    int|float|string a = 1;     . Assign          
  TypeTest           .    if a is int                 . TypeBr-         
  CondBr--           .                                . |      |        
  |       |          .                                . |      |        
  |       CondNarrow .                                . |      |        
  |       TypeTest   .                || a is float { . |      TypeBr-  
  |       Assign     .                                . |      |      | 
  |       Br         .                                . |      |      | 
  |       |          .                                . |      |      | 
  Assign  |          .                                . |      |      | 
  Br      /          .                                . |      |      | 
  |      /           .                                . |      |      | 
  CondBr------       .                                . |      |      | 
  |           |      .                                . |      |     /  
  CondNarrow  |      .                                . TypeMerge   /   
  Assign      |      .       int|float _ = a;         . Assign     /    
  Branch     /       .    }                           . |         /     
  |         /        .                                . |        /      
  CondNarrow         .                                . TypeMerge       
  Assign             .    int|float|string _ = a;     . Assign          
  Ret                .                                . Ret             
```

**Comment by manuranga** [comment]
My current plan is to let `codeGenTypeTest` create `TypeBranch`. It will create ifTrue and ifFalse blocks if needed and keep them in `ExprContext`. `if`/`while` will use those blocks if available, and create `Branch`es only if all paths are not covered by the expression itself. `TypeMerge` will be created by the `if`/`while`.

**Comment by jclark** [comment]
> My current plan is to let `codeGenTypeTest` create `TypeBranch`.

This doesn't sound like a good plan to me. If I do:

```
boolean b = x is int;
```

I don't need a TypeBranch.

Can we start by agreeing the changes to bir.bal?

**Comment by manuranga** [comment]
I added an extra flag to `ExprContext` when I am creating it via `codeGenExprForCond`. For above code, BIR is unchanged.
At first stage I am planing to replace `TypeTest`+`CondBranchInsn` with limited version of `TypeBranch`, without `Registers`. 
For the first stage BIR change will be :
```ballerina
public type TypeBranchInsn readonly & record {|
    *InsnBase;
    INSN_TYPE_BRANCH name = INSN_TYPE_BRANCH;
    Register operand;
    t:SemType semType;
    Label ifTrue;
    Label ifFalse;
|}
```

**Comment by jclark** [comment]
OK, but let's leave CondNarrowInsn in until we are sure this new approach will work.

**Comment by manuranga** [comment]
As the second stage, I was trying to add Registers to above `TypeBranchInsn` instruction and replace some uses of `CondNarrowInsn`.
```ballerina
   NarrowRegister ifTrueRegister;
   NarrowRegister ifFalseRegister;
```
My plan is to initialize narrowed registers at the beginning of the target bb, (instead of just before the first usage, which will require more analysis). I save the info needed for it in the `Scaffold`. There can be a potential problem with this, if there is a backward edge from `TypeBranchInsn`.

Solutions:

1. We consider `TypeBranchInsn` to always be forward, verifier can check it
2. Keep `CondNarrowInsn`, it only appears at a target of `TypeBranchInsn`
3. Generate `TypeMergeInsn` even for single narrowing, (we may rename the instruction)

@jclark appreciate your input on this.

**Comment by jclark** [comment]
I prefer (1).

I am hoping we can make all backward branches be unconditional (I think they are currently).

**Comment by manuranga** [comment]
Above PRs implement and test the positive cases. Only remaining item is to test the negative cases which is covered under #1172. Hence closing.
