### ISSUE TITLE
Add README.md to testSuite directory describing test format

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#89]
Can take most of this from https://github.com/ballerina-platform/nballerina/issues/12#issuecomment-859983087

**Comment by manuranga** [comment]
What about test cases that are out of subset but passing ?
eg:
```
type myInt int;
public function main() {
}
```

**Comment by jclark** [comment]
@manuranga This is the O type I talked about this morning. I just made an issue for this #119.
