### ISSUE TITLE
Comparisons of arrays of subtypes of simple type or string do not work

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#895]
Comparing `int` array with sub-type of `int` using the either `<` or `<=` (other comparison operators seems to work fine) will generate invalid output
example: 
```
import ballerina/io;

type A 1|2|3;
public function main() {
    A[] a = [1, 2, 3];
    int[] b = [4, 5, 6];
    io:println(a < b);
    io:println(a <= b);
}
```
expected output:
```
true
true
```

actual output:
```
false
false
```

**Comment by jclark** [comment]
@heshanpadmasiri Please include PR with failing test case ( `14-bug/subtypecompare-fv.bal`).

Please check subtypes of other basic types also (float, string, boolean).

**Comment by jclark** [comment]
More examples in #896.
