### ISSUE TITLE
Take advantage of non-panicking insns for arithmetic on int subtypes

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#899]
Use limited range of int subtypes to determine when there is no possibility of overflow of arithmetic operations.

In the case of 32-bit integer operations other than division (we can have divide by 0 here) we can use `IntNoPanicArithmeticBinaryInsn` instead or `IntArithmeticBinaryInsn`.

 This is a front-end optimization because the panicking instructions are different.

**Comment by jclark** [comment]
For int:Unsigned32, multiplication can overflow; whereas for int:Signed32 it can't (but check and test this).

**Comment by heshanpadmasiri** [comment]
> For int:Unsigned32, multiplication can overflow; whereas for int:Signed32 it can't (but check and test this).

I think int:signed32 can also overflow given max value is 21474836487 so 21474836487 * 21474836487 will overflow

**Comment by heshanpadmasiri** [comment]
> > For int:Unsigned32, multiplication can overflow; whereas for int:Signed32 it can't (but check and test this).
> 
> I think int:signed32 can also overflow given max value is 21474836487 so 21474836487 * 21474836487 will overflow

This is wrong. Please ignore this
