### ISSUE TITLE
Seperate out domain model from Implementation classes

### ISSUE THREAD

**Issue by shubhamnarlawar** [ballerina-platform/nballerina#9]
**Description:**
Keep the domain model (such as BIRFunction) separate from implementation classes (such as LLVMBuilderRef )

**Comment by Kishanthan** [comment]
@shubhamnarlawar @ruvi-d , can this be closed?

**Comment by ruvi-d** [comment]
Yes we can close.
Though we should consider taking a step further and move the files into two separate sub folders. The `compiler` src folder is already getting pretty cluttered.

**Comment by Kishanthan** [comment]
> Yes we can close.
> Though we should consider taking a step further and move the files into two separate sub folders. The `compiler` src folder is already getting pretty cluttered.

@ruvi-d can you create a separate issue to address this?

**Comment by ruvi-d** [comment]
Done! #68
