### ISSUE TITLE
Generate better code for boxing/unboxing int subtypes

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#900]
When we have an int subtype that fits in 56 bits, we know the representation is immediate. Converting the value to a tagged pointer is just a truncate/shift/increment. Similarly converting from a tagged pointer is just a shift/mask/sign extend.

**Comment by jclark** [comment]
Be sure to test with negative numbers.

**Comment by manuranga** [comment]
I added max/min intimidate int consts in my pr https://github.com/ballerina-platform/nballerina/pull/902/files#diff-e816d0935faff2498db272a1ac22b7168bbfe690b42a7a0ca8908c123d03daffR30
