### ISSUE TITLE
Implement anonymous functions w/o variable capture

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#908]
This builds on #907 to add support for anonymous functions.

This means supporting [explicit-anonymous-function-expr](https://ballerina.io/spec/lang/2022R1/#section_6.18) with a block-function-body.

Initially, we would have the restriction that these functions could not refer to block-scope variables defined outside the function body. This would be handled in #909.

Further we would _not_ support
- `=>` syntax (i.e. expr-function-body)
- inferring types for parameters/return type (infer-anonymous-function-expr)

**Comment by heshanpadmasiri** [comment]
~Resolved with https://github.com/ballerina-platform/ballerina-release/pull/2505~
Ignore this wrong issue
