### ISSUE TITLE
Implement closures

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#909]
This builds on #908 to support closures i.e. allow capturing of local variables.

**Comment by jclark** [comment]
BIR concept is ClosureConstruct insn.

This takes
- FunctionCode for the body of the function
- list of registers captured by value
- list of registers captured by reference

The function code for the body of the function would have its own register for each of the registers that it captures from its enclosing scope.

In the backend, when a register in a function body is captured by a ClosureConstruct insn, the memory for that register would be allocated on the heap not on the stack.

At runtime, the value for the constructed closure would have, in addition to a function pointer, a list with a member for each captured variable.  What is stored by in the member depends on how the register was captured:
- if captured by value, the member holds the value of captured register
- if captured by reference, the member holds a pointer to the heap memory for that register

The backend has to arrange that when the code for the body of a closure accesses a register corresponding to the captured variable, the value comes from what is stored in the closure value. Several strategies are possible. For example, for a value captured by value, it can copy the value into a slot on the stack, just like with a parameter; the heap pointer for a value captured by reference can similarly be copied into a slot on the stack (just like in the containing function).

This allows for a variety of implementation techniques: for example you could use lambda lifting within a module for non-public functions (i.e. transforming the function and callers to represent registers captured by value as additional parameters).

**Comment by manuranga** [comment]
When will capturing by value used? Is it only for final variables/consts? Or any type that doesn't have storage identity?

In  jBallerina following will  output 6.
```ballerina
import ballerina/io;

public function main() {
    int i = 5;
    function() f = function() {
        i = i + 1;
    };
    f();
    io:println(i); // @output 6
}
```

**Comment by manuranga** [comment]
Please also consider capturing of narrowed variables. Related spec issue: https://github.com/ballerina-platform/ballerina-spec/issues/1043

**Comment by jclark** [comment]
Capture by value is only for final variables (and variables that could have been declared as final but weren't).

I agree there are spec issues as pointed in https://github.com/ballerina-platform/ballerina-spec/issues/1043, but I think the implementation strategy here can handle it.

**Comment by jclark** [comment]
There's an interaction of capturing and type narrowing. See https://github.com/ballerina-platform/ballerina-spec/issues/1260#issuecomment-1656250520

If it's not final, then once it's captured, there's a possibility of its being assigned to, which invalidates type narrowing. cc @manuranga
