### ISSUE TITLE
Make hello world work on Windows

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#91]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Depends on : #90

**Comment by KavinduZoysa** [comment]
Closing this issue because windows build is working

**Comment by KavinduZoysa** [comment]
> @KavinduZoysa What does the assembly look like for that example?
> 

Please find the below assembly for the checking code above example.

before mem2reg:
```
0000000000401130 <bar>:
  401130:	55                      push   %rbp
  401131:	48 89 e5             	mov    %rsp,%rbp
  401134:	48 83 ec 10          	sub    $0x10,%rsp
  401138:	48 8d 45 f8          	lea    -0x8(%rbp),%rax // 2nd alloca (last one)
  40113c:	48 3b 04 25 40 40 40 	cmp    0x404040,%rax
```

after mem2reg:
```
0000000000401130 <bar>:
  401130:	55                   	push   %rbp
  401131:	48 89 e5                mov    %rsp,%rbp
  401134:	48 83 ec 10          	sub    $0x10,%rsp
  401138:	48 8d 45 fc          	lea    -0x4(%rbp),%rax // 1st alloca (last one)
  40113c:	48 3b 04 25 40 40 40 	cmp    0x404040,%rax
```

After mem2reg optimization, since only one alloca is left, that is taken to compare.
