### ISSUE TITLE
BIR should distinguish different kinds of register

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#920]
BIR should distinguish at least the following kinds of register:

- parameter
- non-final variable
- final variable
- narrowed variable
- intermediate expression result

We need this to determine
- whether they are single assignment
- how (if at all) they correspond to source level variables

This in turn affects for LLVM
- whether they need an alloca slot
- how to generate debug info

This is needed to support #911

**Comment by jclark** [comment]
Names could be

- param
- var
- final
- narrow
- temp

**Comment by heshanpadmasiri** [comment]
@jclark for this I am thinking of doing fallowing changes:

- In `bir.bal`:

  1. Introduce an new `RegisterKind` enum with [above](https://github.com/ballerina-platform/nballerina/issues/920#issuecomment-1042577643) values.
  2. Change `Register` type to be:
  ```
  public type Register readonly & record {|
      int number;
      SemType semType;
      string? varName;
      Position? pos;
      RegisterKind kind;
  |};
  ```
  3.  change the `createRegister` (We don't use this directly to create registers) to be
  ```
  public function createRegister(FunctionCode code, SemType semType, RegisterKind kind, string? varName = (), Position? pos = ()) returns Register
  ```
- In `StmtContext`:

  1.  Change [`createVarRegister`](https://github.com/ballerina-platform/nballerina/blob/ac31f2a6810d711828663e01aa6b442f67cc5298/compiler/modules/front/stmt.bal#L72) function as (this will be used to create `var` and `final` registers
  ```
  function createVarRegister(bir:SemType t, string varName, boolean isFinal, Position pos) returns bir:Register
  ```
  2. Add new function to create `param` registers as 
  ```
  function createParamRegister(bir:SemType t, string paramName, Position pos) returns bir:Register 
  ```
  3. Add new function to create `narrow` registers as (At the momenet all our narrowing registers seems to be added via the [`addNarrowings`](https://github.com/ballerina-platform/nballerina/blob/ac31f2a6810d711828663e01aa6b442f67cc5298/compiler/modules/front/stmt.bal#L777) function. I am not sure if we must have a position for narrowing registers or make it optional)
  ```
  function createNarrowRegister(bir:SemType t, string name, Position pos) returns bir:Register
  ```
(We can reuse the current `createTmpRegister` available in both [StmtContext](https://github.com/ballerina-platform/nballerina/blob/ac31f2a6810d711828663e01aa6b442f67cc5298/compiler/modules/front/stmt.bal#L77) and [ExprContext](https://github.com/ballerina-platform/nballerina/blob/ac31f2a6810d711828663e01aa6b442f67cc5298/compiler/modules/front/expr.bal#L109) to create register of `tmp` kind)

**Comment by jclark** [comment]
You also need to define subtypes of Register corresponding to some of these kinds and then use these subtypes in the definitions of BIR insns. For example, with a few exceptions the result register of an insn should be a temp. So define a type TmpRegister with kind fixed to "tmp", and then use that as the ResultType.

You need to look at every insn that uses Register, figure out the allowed kinds and then use types to capture that.

**Comment by jclark** [comment]
We should also try to enforce with types that varName will be non-nil for specific kinds.

**Comment by heshanpadmasiri** [comment]
@jclark  in that case I'll refactor the [`Register`](https://github.com/ballerina-platform/nballerina/blob/5f132673c3ac91d0788fc011f54d283b03a132de/compiler/modules/bir/bir.bal#L135) type as:
```
public type Register readonly & record {|
    int number;
    SemType semType;
    string? varName;
    Position? pos;
    RegisterKind kind;
|};

public type NamedRegister readonly & record {|
    * Register
    PARAM_REGISTER|VAR_REGISTER|FINAL_REGISTER|NARROW_REGISTER kind;
    string varName;
    Position pos;
|};

public type ParamRegister readonly & record {|
    * NamedRegister
    PARAM_REGISTER kind = PARAM_REGISTER;
|};

public type VarRegister readonly & record {|
    * NamedRegister
    VAR_REGISTER kind = VAR_REGISTER;
|};

public type FinalRegister readonly & record {|
    * NamedRegister
    FINAL_REGISTER kind = FINAL_REGISTER;
|};

public type NarrowRegister readonly & record {|
    * NamedRegister
    NARROW_REGISTER kind = NARROW_REGISTER;
|};

public type TmpRegister readonly & record {|
    *Register
    TMP_REGISTER kind = TMP_REGISTER;
|};
```
and update all the bir `Insn` that has a Register field to use the correct subtype.

**Comment by jclark** [comment]
Minor points
- no space in `* Register`
- Use _REGISTER_KIND rather than _REGISTER
- you may not need all these subtypes

Names aren't quite right yet
- NamedRegister corresponds to something that has a local declaration in the source: something that can be referred to with a variable reference
- varName doesn't go with NamedRegister

Also `varName` is allowed for other variables with a slightly different semantic.

I think `DeclRegister` and `name` would work better.
