### ISSUE TITLE
Add function to types module to compute projection for every index in one call

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#924]
This does a projection for all indices at once 

```
// For each [r, s] in the return value, for an index i in r, the projection for t[i] is r 
function listAllMemberTypes(Context cx, SemType t) returns [Range,SemType][] {}
```

Just iterating over every index is too inefficient for fixed length arrays (consider comparing `int[]` with `int[10000000]`).

**Comment by jclark** [comment]
Then use this to finish comparableNillableList

**Comment by heshanpadmasiri** [comment]
Fallowing tests that has been disabled with #927 must be re-enabled with this:
- 11-nested/order1-v.bal
- 11-nested/order2-v.bal
- 11-nested/order3-e.bal
- 11-nested/order3-v.bal
- 11-nested/order4-v.bal
- 11-nested/order5-v.bal

**Comment by rdhananjaya** [comment]
I see two ways to approach this.
1. Identify all individual ranges in list type and then invoke `listProj` for each of those ranges.
2. Add an alternative version (duplicate) of `listProjExclude` that would return all range-semtype pairs for each path.

@jclark I prefer the first approach, any thoughts?

**Comment by jclark** [comment]
My only thought is that 1 is only going to work if you generate a list of disjoint ranges from the ranges mentioned in the list type.

**Comment by jclark** [comment]
I reworked #927.

In particular, I factored out the difficult logic into a combineRanges function.   You can probably reuse this for 1 in conjunction with listAtomicTypeAllMemberTypes.

You might want to change it to return two parallel arrays i.e. `[Range[], [int?,int?][]]`.
