### ISSUE TITLE
Support for nil type

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/nballerina#94]
**Description:**
$subject.
This issue is a subtype of https://github.com/ballerina-platform/nballerina/issues/74

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by KavinduZoysa** [comment]
Please check the slack channel for [the initial discussion](https://ballerina-platform.slack.com/archives/C01LNSAHK18/p1613363112071700).

**Comment by KavinduZoysa** [comment]
Please check the slack channel for [the initial discussion](https://ballerina-platform.slack.com/archives/C01LNSAHK18/p1613363112071700).

**Comment by KavinduZoysa** [comment]
@ayonam, I have updated the [assembly file](https://github.com/KavinduZoysa/llvm/blob/assembly/assembly_file) with .data section.

**Comment by ayonam** [comment]
@KavinduZoysa Okay, so the contents of 0x603010 should be 0x00000000 for a 32-bit system.  Currently it is showing the hex values for the string "null".  Please make the correction that I suggested earlier and we should be able to get all zeros in that address.

**Comment by KavinduZoysa** [comment]
Thank you @ayonam, I am working on that.

@ramakotareddy , Is the the [API](https://llvm.org/doxygen/classllvm_1_1DataLayout.html#a8fec4e751427335eb21217d29dcce52d), which can be used to get the pointer size.

**Comment by ramakotareddy** [comment]
@KavinduZoysa You need LLVM API or C++ API ?

From LLVM side, you can use "LLVMValueRef LLVMSizeOf(LLVMTypeRef Ty)" this API.

**Comment by KavinduZoysa** [comment]
As I understood, it should be an LLVM API, which can be able to get the size of the pointer for that machine. @ayonam , could you please confirm?

**Comment by ayonam** [comment]
@KavinduZoysa Yes, you need to call that LLVMSizeOf API with the pointer type as a parameter and it will return you a LLVMValueRef which will be a Constant value and the value there is the size of the pointer.  You should have an API in the LLVMValueRef class that will return you this size as an integer.  

@ramakotareddy Can you please check which API in that class gives us the value as an integer?

**Comment by ramakotareddy** [comment]
@ayonam Is LLVMGetPointerAddressSpace() this API will give Size of Pointer ?. 
    unsigned LLVMGetPointerAddressSpace(LLVMTypeRef PointerTy)

**Comment by ayonam** [comment]
@ramakotareddy No.  Not this.  There should be a member function of LLVMValueRef.  If the LLVMValueRef is a Constant value, that member function should give the constant value.

**Comment by manuranga** [comment]
@ayonam Instead of we finding the platform size, can't we use a some pointer type variable, so llvm allocates the correct size.
eg:
```
@bal_null_deref = global i8* null, align 8
```

**Comment by ayonam** [comment]
Yes, that is a good idea.  That way the size gets allocated automatically.  Even the alignment can be made system dependent so that on a 32-bit system it will automatically issue an align 4 instead of an align 8.

**Comment by KavinduZoysa** [comment]
@ayonam , for implement the manu's suggestion, I think we can use `Constant::getNullValue();`. Am I correct?

**Comment by KavinduZoysa** [comment]
I have a concern here. Please consider below function signatures. 

```
function fooWithReturn() returns () {
     return ();
}
```

```
function fooWithOutReturn() {
}
```

In both cases, BIR is modelled to return `nil` type. So when implementing these cases in nballerina, both cases will return nil and there is not a void return. 

Do we need to distinguish these cases? Is that okay to consider both cases as same? 
@Kishanthan, @manu, @warunalakshitha

**Comment by ruvi-d** [comment]
> I have a concern here. Please consider below function signatures.
> 
> ```
> function fooWithReturn() returns () {
>      return ();
> }
> ```
> 
> ```
> function fooWithOutReturn() {
> }
> ```
> 
> In both cases, BIR is modelled to return `nil` type. So when implementing these cases in nballerina, both cases will return nil and there is not a void return.
> 
> Do we need to distinguish these cases? Is that okay to consider both cases as same?
> @Kishanthan, @manu, @warunalakshitha

https://ballerina.io/lang-guide/Ballerina_Language_Presentation-2021-01-29.pdf slide no: 13 suggests that it should be treated the same.

**Comment by warunalakshitha** [comment]
Yes. Both cases are the same. 

As per spec 'The value returned by a function will belong to the type specified in the return-type-descriptor. An empty return-type-descriptor is equivalent to returns ().'

() x = fooWithReturn();
() y = fooWithOutReturn();

AFAIU both should have the same behavior.

**Comment by KavinduZoysa** [comment]
What about the `main function` if it does not have a return type?
`public function main() {}`

**Comment by warunalakshitha** [comment]
The main function also the same as other functions. There is no difference in return type as per spec.

**Comment by KavinduZoysa** [comment]
@warunalakshitha and @ruvi-d , thank you for your response.

**Comment by ruvi-d** [comment]
If i remember correctly main for native binaries (ELF spec) expects a int or void return. So on the codegen side we would need to special case the main function.

**Comment by manuranga** [comment]
ya, we'll need to wrap the ballerina main with a real native main, this is what we have done in java as well.

**Comment by KavinduZoysa** [comment]
ACK.
