### ISSUE TITLE
Fix issues in generated .ll file in windows

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/nballerina#95]
**Description:**
$subject. 
If we generate the .ll file in windows, it does not work. Please check this comment for more details https://github.com/ballerina-platform/nballerina/issues/90#issuecomment-777965374. 

Please check PR for the instruction of windows build. https://github.com/ballerina-platform/nballerina/pull/93

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/ballerina-platform/nballerina/issues/90
https://github.com/ballerina-platform/nballerina/issues/91

**Comment by ayonam** [comment]
@ramakotareddy What we need to do here is that if the platform is Windows, we should not emit the DataModel at the beginning of the .ll file.  Also, the Target Machine description should change.  I think if you see the target that is sent to LLVM through the build process, I think it will be compatible with Windows.  Please check that and, if needed, we will have to correct it.

**Comment by ruvi-d** [comment]
@ayonam / @ramakotareddy : we also need to figure out why the function names are missing in the Windows generated LLVM IR

**Comment by ayonam** [comment]
@ramakotareddy, yes, we need to figure out that too.  On windows, it is only printing the integer IDs instead of the function names.  So you need to figure out why this is happening.
