### ISSUE TITLE
Unclear error messages in fixed length arrays

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/nballerina#958]
Some errors given for fixed length arrays have unhelpful error messages.
```
public function main() {
    int[4] v = [1, 2, 3, 4];
    io:println(v[4]); // @error
}
```
`error: type of member access is never`

```
public function main() {
    int[4] v = [1, 2, 3, 4];
    v[4] = 4; // @error
```
`error: value assigned to member of list is not a subtype of array member type`

**Comment by jclark** [comment]
These cases could arise equally with tuples
