### ISSUE TITLE
Constructing outFileName from inFileName logic in driver.cpp is not working for relative paths in parent directories

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-platform/nballerina#96]
**Description:**
The logic uses following code snippet

```CPP
// if output file name is empty from command line options.
  if (outFileName == "") {
    for (unsigned int i = 0; i < inFileName.length(); i++) {
      char tmpstr = inFileName[i];
      if (tmpstr == '.')
        break;
      outFileName = outFileName + inFileName[i];
    }
    outFileName = outFileName + ".ll";
  }
```
https://github.com/ballerina-platform/nballerina/blob/master/compiler/driver.cpp#L46

If the inFileName is "../compiler/main-bir-dump", then according to above logic, the outFileName will be ".ll", which is not what is expected. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Kishanthan** [comment]
@ushirask
