### ISSUE TITLE
Verify register kinds

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/nballerina#963]
Enhance bir/verify.bal to verify that the kind of a BIR register is consistent with how it is used within the FunctionCode.
Follow-up from #920

**Comment by manuranga** [comment]
Semantics of `narrow` kind are validated under #1170
Semantics of register initialization and `param` kind are validated under #1026
Other semantics are guaranteed statically by the bir types.
Negative testing for this feature moved to #1172

Hence closing.
