### ISSUE TITLE
Tuple subtyping bug

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#975]
I came up with this as a counter example for 4.7 in the paper. I not quite sure if this is a bug or not.

```ballerina
// N2<:N3
// T1A<:T1B
// T1B<:T1A
// Three<:N3

 // 3 *   * T2
 // 2 *
 // 1 * * * T1A, T1B
 //   1 2 3


type Three 3;
type N2 1|2;
type N3 1|2|3;
type T1A [1, Three] | [Three, 1];
type T1B [N3, N3] & ![N2, N2];
type T2 [Three, Three];
```

Running above as `bal test --tests "testSubtype#'tuple3.bal'"` gave me 
```
Assertion Failed!

    expected: '["N2<:N3","T1A<:T1B","T1B<:T1A","Three<:N3"]'
    actual  : '["N2<:N3","T1A<:T1B","T2<:T1B","Three<:N3"]'
 ```

**Comment by rdhananjaya** [comment]
T1A => { [1, 3], [3, 1] }
T1B => { [1, 3], [2, 3], [3, 3], [3, 2], [3, 1] }
T2   => { [3, 3] }

Did I miss any values that should be in these tuples, if not this is not a bug?

**Comment by manuranga** [comment]
You are correct, not a bug.
